# Generated by Skyramp v1.3.40 on 2026-08-27 14:30:31.75570982 +0000 UTC m=+621.218391891
# Command: skyramp generate contract rest http://localhost:8080/api/v4/secrets/move \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output-dir /home/runner/work/infisical/infisical/.skyramp/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"foo":"bar"} \
# 		--response-status-code 400 \
# 		--runtime local

# Import of required libraries
import skyramp
import os


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

# contract test for /api/v4/secrets/move POST
def test_move_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    move_POST_request_body = r'''{
        "foo": "bar"
    }'''

    # Execute Request
    move_POST_response = client.send_request(
        url=URL,
        path="/api/v4/secrets/move",
        method="POST",
        body=move_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert move_POST_response.status_code == 422
    assert skyramp.get_response_value(move_POST_response, "error") == "ValidationFailure"
    assert skyramp.get_response_value(move_POST_response, "message.0.code") == "invalid_type"
    assert skyramp.get_response_value(move_POST_response, "message.0.path.0") == "projectId"
    assert skyramp.get_response_value(move_POST_response, "message.0.message") == "Required"
    assert skyramp.get_response_value(move_POST_response, "message.1.path.0") == "sourceEnvironment"
    assert skyramp.get_response_value(move_POST_response, "message.2.path.0") == "destinationEnvironment"
    assert skyramp.get_response_value(move_POST_response, "message.3.path.0") == "secretIds"
    assert skyramp.get_response_value(move_POST_response, "message.4") is None


if __name__ == "__main__":
    test_move_post()
