# Generated by Skyramp v1.3.40 on 2026-08-27 14:30:41.829654454 +0000 UTC m=+631.292336525
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output move_secrets_override_migration_integration_test.py \
# 		--output-dir /home/runner/work/infisical/infisical/.skyramp/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/infisical/infisical/.skyramp/tests/scenario_move-secrets-override-migration.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    move_POST_request_body = r'''{
        "destinationEnvironment": "staging",
        "destinationSecretPath": "/",
        "projectId": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        "secretIds": [
            "b2c3d4e5-f6a7-8901-bcde-f12345678901"
        ],
        "shouldOverwrite": false,
        "sourceEnvironment": "dev",
        "sourceSecretPath": "/"
    }'''

    # Execute Request
    move_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v4/secrets/move",
        method="POST",
        body=move_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert move_POST_response.status_code == 200
    assert isinstance(skyramp.get_response_value(move_POST_response, "isSourceUpdated"), bool)
    assert isinstance(skyramp.get_response_value(move_POST_response, "isDestinationUpdated"), bool)
    assert skyramp.get_response_value(move_POST_response, "movedOverridesCount") is not None
    assert skyramp.get_response_value(move_POST_response, "movedOverridesCount") >= 0


if __name__ == "__main__":
    test_integration()
