// Generated by Skyramp v1.3.40 on 2026-08-26 19:21:03.808230093 +0000 UTC m=+463.605106207
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output patch_shared_secret_lifecycle_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/.skyramp/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/.skyramp/tests/scenario_patch_shared_secret_lifecycle.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const sharedSecretsPostRequestBody: string = `{
        "accessType": "organization",
        "expiresIn": "1d",
        "secretValue": "my-test-secret-value"
    }`;

    // Execute Request
    const sharedSecretsPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/shared-secrets",
        method: "POST",
        body: sharedSecretsPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(sharedSecretsPostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(sharedSecretsPostResponse, "id")).not.toBeNull();
    expect(getResponseValue(sharedSecretsPostResponse, "accessType"), 'accessType').toBe("organization");
    expect(getResponseValue(sharedSecretsPostResponse, "allowExternalEmails")).toBe(false);
    expect(getResponseValue(sharedSecretsPostResponse, "expiresAt")).toMatch(/^\d{4}-\d{2}-\d{2}T/);
    expect(getResponseValue(sharedSecretsPostResponse, "createdAt")).toMatch(/^\d{4}-\d{2}-\d{2}T/);
    expect(getResponseValue(sharedSecretsPostResponse, "updatedAt")).toMatch(/^\d{4}-\d{2}-\d{2}T/);

    // Request Body
    const sharedSecretsSharedSecretsPatchRequestBody: string = `{
        "expiresIn": "7d",
        "name": "my-updated-secret"
    }`;

    // Execute Request
    const sharedSecretsSharedSecretsPatchResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/shared-secrets/{shared-secrets}",
        method: "PATCH",
        body: sharedSecretsSharedSecretsPatchRequestBody,
        headers: headers,
        pathParams: {"shared-secrets": getResponseValue(sharedSecretsPostResponse, "id")}
    });

    // Generated Assertions
    expect(sharedSecretsSharedSecretsPatchResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(sharedSecretsSharedSecretsPatchResponse, "id"), 'id').toBe(getResponseValue(sharedSecretsPostResponse, "id"));
    expect(getResponseValue(sharedSecretsSharedSecretsPatchResponse, "name"), 'name').toBe("my-updated-secret");
    expect(getResponseValue(sharedSecretsSharedSecretsPatchResponse, "expiresAt")).toMatch(/^\d{4}-\d{2}-\d{2}T/);
    expect(getResponseValue(sharedSecretsSharedSecretsPatchResponse, "updatedAt")).toMatch(/^\d{4}-\d{2}-\d{2}T/);

    // Execute Request
    const sharedSecretsGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/shared-secrets",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(sharedSecretsGetResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(sharedSecretsGetResponse, "totalCount")).toBeGreaterThanOrEqual(1);
    expect(getResponseValue(sharedSecretsGetResponse, "secrets.0.id")).toBe(getResponseValue(sharedSecretsPostResponse, "id"));
    expect(getResponseValue(sharedSecretsGetResponse, "secrets.0.name")).toBe("my-updated-secret");
    expect(getResponseValue(sharedSecretsGetResponse, "secrets.0.accessType")).toBe("organization");
});
