// Generated by Skyramp v1.3.40 on 2026-08-27 14:48:40.475028874 +0000 UTC m=+606.395692957
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output secrets_permanent_delete_requires_archive_first_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/.skyramp/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/.skyramp/tests/scenario_secrets-permanent-delete-requires-archive-first.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const guardrailTestSecretPostRequestBody: string = `{
        "environment": "dev",
        "projectId": "00000000-0000-0000-0000-000000000000",
        "secretPath": "/",
        "secretValue": "guardrail-value",
        "type": "shared"
    }`;

    // Execute Request
    const guardrailTestSecretPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets/GUARDRAIL_TEST_SECRET",
        method: "POST",
        body: guardrailTestSecretPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(guardrailTestSecretPostResponse.statusCode, 'status code').toBe(200);

    // Request Body
    const archivedDeleteRequestBody: string = `{
        "environment": "dev",
        "projectId": "00000000-0000-0000-0000-000000000000",
        "secretNames": [
            "GUARDRAIL_TEST_SECRET"
        ],
        "secretPath": "/"
    }`;

    // Execute Request
    const archivedDeleteResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets/archived",
        method: "DELETE",
        body: archivedDeleteRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(archivedDeleteResponse.statusCode, 'status code').toBe(404);
    expect(getValue(archivedDeleteResponse, "message"), 'guardrail message').toBe("One or more secrets are not archived. Archive a secret before deleting it permanently.");
    expect(getValue(archivedDeleteResponse, "error"), 'error type').toBe("NotFound");
});
