// Generated by Skyramp v1.3.40 on 2026-08-27 15:06:14.207011377 +0000 UTC m=+1660.127675458
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_dashboard_archive_and_trash_flow.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/.skyramp/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_dashboard_archive_and_trash_flow_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1286000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);

    const pageErrors: string[] = [];
    page.on("pageerror", (err) => pageErrors.push(err.message));

    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/`);
    // Wait for network activities to finish
    await page.waitForTimeout(15000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    // Create a fresh project each run (unique name) so the dashboard starts clean
    const projectName = `Archive Test ${Date.now()}`;
    await page.getByRole("button", { name: "Add New Project" }).click();
    await page.getByRole("textbox", { name: "Type your project name" }).fill(projectName);
    await page.getByRole("button", { name: "Create Project" }).click();
    await page.waitForURL(/secret-management\/[0-9a-f-]+\/overview/, { timeout: 30000 });
    await page.waitForLoadState("networkidle");
    await page.waitForTimeout(2000);

    // The project id is generated per run — derive the dashboard URL from the current location
    const ids = page.url().match(/organizations\/([0-9a-f-]+)\/projects\/secret-management\/([0-9a-f-]+)/);
    const orgId = ids![1];
    const projectId = ids![2];

    // Open the Development environment's Secret Dashboard (where the new Trash button lives)
    await page.goto(`${baseUrl}/organizations/${orgId}/projects/secret-management/${projectId}/secrets/dev`);
    await page.waitForLoadState("networkidle");
    await page.getByRole("button", { name: "Trash" }).waitFor({ state: "visible", timeout: 20000 });

    // Create the target secret; commit it if the dashboard stages it as a pending change
    await page.getByRole("button", { name: "Add Secret" }).click();
    await page.getByRole("textbox", { name: "Type your secret name" }).fill("ARCHIVE_ME");
    await page.getByRole("textbox", { name: "secret value" }).fill("secret-value-123");
    await page.getByRole("button", { name: "Create Secret" }).click();
    await page.waitForTimeout(3000);
    const saveAfterCreate = page.getByRole("button", { name: "Save Changes" });
    if (await saveAfterCreate.isVisible().catch(() => false)) {
        await saveAfterCreate.click();
        await page.waitForTimeout(3000);
    }
    await expect(page.getByText("ARCHIVE_ME")).toBeVisible({ timeout: 20000 });

    // Delete the secret. Per this PR, deleting archives the secret so it stays recoverable from
    // the Trash instead of permanently deleting it.
    await page.getByRole("button", { name: "delete-value" }).first().click();
    await page.getByRole("textbox", { name: "Type ARCHIVE_ME here" }).fill("ARCHIVE_ME");
    await page.getByRole("button", { name: "Delete Secret" }).click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/v1/pit/batch/commit**");
    await page.getByRole("button", { name: "Save Changes" }).click();
    const response1 = await responsePromise1;
    expect(response1.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    // The archived secret must no longer appear in the dashboard list
    await expect(page.getByText("ARCHIVE_ME")).toHaveCount(0);

    // Open the Trash (the archived-secrets modal added by this PR)
    await page.getByRole("button", { name: "Trash" }).click();
    const trashDialog = page.getByRole("dialog", { name: "Trash" });
    await expect(trashDialog.getByText("Archived secrets at")).toBeVisible();

    // Expected per the PR: the deleted secret is archived and recoverable from the Trash.
    // This assertion documents the bug — the dashboard delete commits a permanent deletion via
    // /api/v1/pit/batch/commit and never calls POST /api/v4/secrets/archive, so ARCHIVE_ME never
    // reaches the Trash (the modal shows "Trash is empty") and is unrecoverable.
    await expect(trashDialog.getByText("ARCHIVE_ME")).toBeVisible();

    expect(pageErrors).toHaveLength(0);
});
