// Generated by Skyramp v1.3.40 on 2026-08-27 14:48:00.592320173 +0000 UTC m=+566.512984252
// Command: skyramp generate contract rest http://localhost:8080/api/v4/secrets/archive \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output secret_router_archive_post_auth_boundary.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/.skyramp/tests \
// 		--overwrite \
// 		--provider \
// 		--request-data {"projectId":"00000000-0000-0000-0000-000000000000","environment":"dev","secretPath":"/","secretNames":["EXAMPLE"]} \
// 		--response-status-code 401 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

// contract test for /api/v4/secrets/archive POST
test('testArchivePost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const archivePostRequestBody: string = `{
        "environment": "dev",
        "projectId": "00000000-0000-0000-0000-000000000000",
        "secretNames": [
            "EXAMPLE"
        ],
        "secretPath": "/"
    }`;

    // Execute Request
    const archivePostResponse = await client.sendRequest({
        url: URL,
        path: "/api/v4/secrets/archive",
        method: "POST",
        body: archivePostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(archivePostResponse.statusCode, 'status code').toBe(401);
});
