// Generated by Skyramp v1.3.40 on 2026-08-26 19:20:44.985177165 +0000 UTC m=+444.782053269
// Command: skyramp generate contract rest http://localhost:8080/api/v1/shared-secrets/{id} \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method PATCH \
// 		--output-dir /home/runner/work/infisical/infisical/.skyramp/tests \
// 		--overwrite \
// 		--path-params id=c2VjcmV0LWlkZW50aWZpZXI \
// 		--provider \
// 		--request-data {"name":"updated-secret-name","expiresIn":"7d"} \
// 		--response-status-code 200 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

// contract test for /api/v1/shared-secrets/{id} PATCH
test('testSharedSecretsIdPatch', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const id = "mZ3Ii01JCnztyBoaHOcOh1Cg3x19kPdqcp79Dl8INQU";

    // Request Body
    const sharedSecretsIdPatchRequestBody: string = `{
        "expiresIn": "7d",
        "name": "updated-secret-name"
    }`;

    // Execute Request
    const sharedSecretsIdPatchResponse = await client.sendRequest({
        url: URL,
        path: "/api/v1/shared-secrets/{id}",
        method: "PATCH",
        body: sharedSecretsIdPatchRequestBody,
        headers: headers,
        pathParams: {"id": id}
    });

    // Generated Assertions
    expect(sharedSecretsIdPatchResponse.statusCode, 'status code').toBe(200);
    expect(getValue(sharedSecretsIdPatchResponse, "name"), 'name').toBe("updated-secret-name");
    expect(getValue(sharedSecretsIdPatchResponse, "expiresAt")).toMatch(/^\d{4}-\d{2}-\d{2}T/);
    expect(getValue(sharedSecretsIdPatchResponse, "createdAt")).toMatch(/^\d{4}-\d{2}-\d{2}T/);
    expect(getValue(sharedSecretsIdPatchResponse, "updatedAt")).toMatch(/^\d{4}-\d{2}-\d{2}T/);
    expect(getValue(sharedSecretsIdPatchResponse, "id")).not.toBeNull();
});
