// Generated by Skyramp v1.3.40 on 2026-08-26 19:25:48.032759548 +0000 UTC m=+747.829635662
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output ui_edit_shared_secret_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/.skyramp/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/edit_shared_secret_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(416000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', (error) => errors.push(error));

    await page.goto(`${baseUrl}/login`);
    // Wait for network activities to finish
    await page.waitForTimeout(9750);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Secret Sharing" }).click();
    const existingSecretRow = page.getByRole('row', { name: 'my-test-secret' });
    if (await existingSecretRow.isVisible().catch(() => false)) {
        // row already exists, skip creation
    } else {
        await page.getByRole("button", { name: "Share Secret" }).click();
        await page.getByRole("textbox", { name: "API Key" }).fill("my-test-secret");
        await page.getByRole("textbox", { name: "Enter sensitive data to share" }).fill("super-secret-value");
        await page.getByRole("button", { name: "Create Secret Link" }).click();
        // Wait for network activities to finish
        await page.waitForTimeout(3000);
        await page.getByRole("button", { name: "Close" }).click();
    }
    await expect(page.getByRole("cell", { name: "my-test-secret" })).toHaveText("my-test-secret");
    await page.getByRole("row", { name: /my-test-secret/ }).getByLabel("actions").click();
    await page.getByRole("menuitem", { name: "Edit" }).click();
    await page.getByRole("textbox", { name: "API Key for John" }).fill("my-updated-secret-name");
    await page.getByRole("combobox").nth(0).click();
    await page.getByRole("option", { name: "7 days" }).click();
    await page.getByRole("button", { name: "Save" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(14159);

    await expect(page.getByRole("cell", { name: "7:25 PM" })).toContainText("Sep 2, 2026");
    await expect(page.getByRole("cell", { name: "my-updated-secret-name" })).toHaveText("my-updated-secret-name");
    expect(errors).toHaveLength(0);
});
