// Generated by Skyramp v1.3.30 on 2026-07-06 17:53:54.734915023 +0000 UTC m=+1057.136195133
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output dotted_secret_reference_escape.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/dotted_secret_reference_escape_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('selecting a dotted secret key from the ${} autocomplete escapes the inserted reference', async ({ page }) => {
    test.setTimeout(1568000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.waitForTimeout(2000);

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    await page.getByRole("button", { name: "Add New Project" }).click();
    await page.getByRole("textbox", { name: "Type your project name" }).fill("Testbot Secret Refs");
    await page.getByRole("button", { name: "Create Project" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(11372);

    // Setup: create a secret whose key contains dots — this is the key that could
    // previously never be referenced, per issue #5962.
    await page.getByText("Add a New Secret").click();
    await page.getByRole("textbox", { name: "Type your secret name" }).fill("app.db.host");
    await page.getByRole("textbox", { name: "secret value" }).fill("prod-db.internal.example.com");
    await page.getByRole("button", { name: "Create Secret" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(20000);

    // Create a second secret and reference the dotted key via the ${...} autocomplete.
    await page.getByText("Add Secret").click();
    await page.getByRole("textbox", { name: "Type your secret name" }).fill("db-connection-string");
    await page.getByPlaceholder("Enter secret value...").fill("${dev.");
    await page.getByRole("button", { name: "suggestion-item" }).click();

    // The autocomplete should escape the dots in "app.db.host" so the reference
    // grammar treats the whole key as one token: ${dev.app\.db\.host}.
    // Bug: InfisicalSecretInput.tsx inserts the raw, unescaped key instead, which
    // the backend parser will mis-split into environment=dev, path=/app/db,
    // key=host — a path that does not exist — so the reference never resolves.
    await expect(page.getByPlaceholder("Enter secret value...")).toHaveValue("${dev.app\\.db\\.host}");

    await page.getByRole("button", { name: "Create Secret" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.getByRole("button", { name: "Reveal Values" }).click();

    // The persisted raw value should also reflect the escaped reference.
    await expect(page.getByRole("row", { name: "db-connection-string" })).toContainText("${dev.app\\.db\\.host}");

    expect(pageErrors).toHaveLength(0);
});
