// Generated by Skyramp v1.3.40 on 2026-08-26 19:39:41.434991378 +0000 UTC m=+915.123494275
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output edit_share_secret_modal_preserves_name.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/edit_share_secret_modal_preserves_name_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1303000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/login`);
    // Wait for network activities to finish
    await page.waitForTimeout(10500);

    await page.waitForTimeout(2000);

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;

    // Login redirects to the org Projects Overview page — navigate into Secret Sharing via the sidebar
    await page.getByRole("button", { name: "Secret Sharing" }).click();
    await page.waitForSelector("text=Share Secret");
    await page.getByRole("button", { name: "Share Secret" }).click();
    await page.getByRole("textbox", { name: "API Key" }).fill("Testbot Sample Secret");
    await page.getByRole("textbox", { name: "Enter sensitive data to share" }).fill("sample-secret-value-12345");
    await page.getByRole("button", { name: "Create Secret Link" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Close" }).click();
    // Scope every subsequent interaction to the row this test just created — the shared
    // test org can have other shared-secret rows present, so an unscoped "actions" locator
    // is ambiguous.
    const newSecretRow = page.getByRole("row", { name: "Testbot Sample Secret" }).first();
    await newSecretRow.getByRole("button", { name: "actions" }).click();
    await page.getByRole("menuitem", { name: "Edit" }).click();
    await page.getByRole("button", { name: "Cancel" }).click();
    await newSecretRow.getByRole("button", { name: "actions" }).click();
    await page.getByRole("menuitem", { name: "Edit" }).click();
    await page.getByRole("combobox").nth(0).click();
    await page.getByRole("option", { name: "1 day" }).click();
    await page.getByRole("button", { name: "Save" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(18331);

    // newSecretRow was located by its pre-edit name, which the bug below wipes out — re-locate
    // the same row post-save via its now-stable expiry cell instead.
    const editedSecretRow = page.getByRole("row").filter({ has: page.getByRole("cell", { name: "7:39 PM" }) }).first();
    await expect(editedSecretRow.getByRole("cell", { name: "7:39 PM" })).toContainText("Aug 27, 2026");
    // Bug-catching assertion: EditShareSecretModal always reset()s the form to blank
    // defaults and onSubmit always sends name: data.name, so saving after changing only
    // Expires In silently blanks the secret's name instead of preserving it.
    await expect(editedSecretRow.getByRole("cell").nth(1)).toHaveText("Testbot Sample Secret");
});
