// Generated by Skyramp v1.3.38 on 2026-08-19 04:18:37.570487846 +0000 UTC m=+1552.763941274
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_tag_form_attach.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_tag_form_attach_trace.zip

// Import of required libraries
import { test, expect, checkRequestPayload, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(120000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);

    const pageErrors: Error[] = [];
    page.on('pageerror', (error) => pageErrors.push(error));

    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    // Expected request payloads for network assertions
    const expectedPayload1 = {
        "environment": "dev",
        "secretPath": "/",
        "tagSlugs": ["urgent"]
    };

    await page.goto(`${baseUrl}/login`);
    // Wait for network activities to finish
    await page.waitForTimeout(7500);

    await page.waitForTimeout(2000);

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Add New Project" }).click();
    await page.getByRole("textbox", { name: "Type your project name" }).fill("Tag Editor Demo");
    await page.getByRole("button", { name: "Create Project" }).click();
    await page.getByText("Add a New Secret").click();
    await page.getByRole("textbox", { name: "Type your secret name" }).fill("DEMO_SECRET");
    await page.getByRole("textbox", { name: "secret value" }).fill("hello-world");
    await page.getByRole("button", { name: "Create Secret" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByRole("row", { name: "DEMO_SECRET" })).toBeVisible();
    await page.getByRole("row", { name: "DEMO_SECRET" }).hover();
    // Wait for the hover-revealed row actions to render
    await page.waitForTimeout(500);

    await page.evaluate(() => {
  const svg = document.querySelector('tbody tr svg.lucide-tags');
  (svg.closest('button') as HTMLButtonElement).click();
});

    await expect(page.getByRole("button", { name: "Save Tags" })).toBeVisible();

    const playwrightRequest1: Record<string, any> = {"slug": "urgent"};

    await page.locator("#react-select-3-input").fill(getValue(playwrightRequest1, "slug"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/v1/projects/**/tags**");
    await page.locator("#react-select-3-listbox").getByRole("option", { name: "Create \"urgent\"" }).click();
    const response1 = await responsePromise1;
    expect(response1.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(1500);

    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise2 = page.waitForResponse("**/api/v4/secrets/**/tags**");
    await page.getByRole("button", { name: "Save Tags" }).click();
    const response2 = await responsePromise2;
    // Validate request payload
    checkRequestPayload(response2.request().postDataJSON(), expectedPayload1);
    expect(response2.status()).toBe(200);
    const response2Body = await response2.json();
    expect(response2Body.tags).toHaveLength(1);
    expect(response2Body.tags[0].slug).toBe("urgent");

    await expect(page.getByText("Successfully updated tags")).toBeVisible();
    await expect(page.getByRole("button", { name: "Save Tags" })).not.toBeVisible();

    expect(pageErrors).toHaveLength(0);
});
