// Generated by Skyramp v1.3.40 on 2026-08-27 14:39:40.841396329 +0000 UTC m=+1404.510630690
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_sharing_access_history_drawer.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret-sharing-access-history_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test.use({
    viewport: { width: 1280, height: 900 },
});

async function openAccessHistoryDrawer(page, secretName) {
    const row = page.getByRole("row", { name: secretName });
    await row.hover();
    await row.getByRole("button", { name: "actions" }).click();
    await page.getByRole("menuitem", { name: "Access history" }).click();
}

test('testUi', async ({ page }) => {
    test.setTimeout(713000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    // Run-unique name so this test does not collide with rows left by prior runs
    const secretName = `Testbot Access History Secret ${Date.now()}`;
    const pageErrors: Error[] = [];
    page.on("pageerror", (err) => pageErrors.push(err));

    await page.goto(`${baseUrl}/login`);
    // Wait for network activities to finish
    await page.waitForTimeout(6750);

    await page.waitForTimeout(2000);

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status(), 'login response status').toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Secret Sharing" }).click();
    await page.getByRole("button", { name: "Share Secret" }).click();
    await page.getByRole("button", { name: "Advanced Settings" }).click();
    await page.getByRole("textbox", { name: "API Key" }).fill(secretName);
    await page.getByRole("textbox", { name: "Enter sensitive data to share" }).fill("sk-testbot-secret-value-123");
    await expect(page.locator("#notify-on-access"), 'notify-on-access before toggle').not.toBeChecked();
    await page.locator("#notify-on-access").click();
    await expect(page.locator("#notify-on-access"), 'notify-on-access after toggle').toBeChecked();
    await page.getByRole("button", { name: "Create Secret Link" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Close" }).click();
    await openAccessHistoryDrawer(page, secretName);
    await expect(page.getByRole("heading", { name: "Access History" }), 'access history heading').toBeVisible();
    await expect(page.getByText("Not opened yet"), 'empty state title').toBeVisible();
    await page.getByRole("button", { name: "Close" }).click();
    await openAccessHistoryDrawer(page, secretName);
    await expect(page.getByText("Every attempt to open this")).toContainText("0 total.");
    await page.getByRole("button", { name: "Close" }).click();

    expect(pageErrors, 'page errors').toHaveLength(0);
});
