// Generated by Skyramp v1.3.38 on 2026-08-19 04:23:37.444633909 +0000 UTC m=+1676.368236880
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_tag_form_attach_detach_diff.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_tag_form_attach_detach_diff_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(120000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (error) => pageErrors.push(error));

    await page.goto(`${baseUrl}/login`);
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.waitForTimeout(2000);

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status(), 'login response status').toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.getByRole("button", { name: "Add New Project" }).click();
    await page.getByRole("textbox", { name: "Type your project name" }).fill("skyramp-ui-tagtest");
    await page.getByRole("button", { name: "Create Project" }).click();
    await page.getByText("Add a New Secret").click();
    await page.getByRole("textbox", { name: "Type your secret name" }).fill("API_KEY");
    await page.getByRole("textbox", { name: "secret value" }).fill("sk-test-value-12345");
    await page.getByRole("button", { name: "Create Secret" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("row", { name: "API_KEY" }).hover();
    // Wait for network activities to finish
    await page.waitForTimeout(2000);

    await page.getByRole("row", { name: "API_KEY" }).locator('button:has(svg[class*="lucide-tags"])').first().click();

    const playwrightRequest1: Record<string, any> = {"slug": "env-prod"};

    await page.locator("#react-select-3-input").fill(getValue(playwrightRequest1, "slug"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/v1/projects/**/tags**");
    await page.locator("#react-select-3-listbox").getByRole("option", { name: "Create \"env-prod\"" }).click();
    const response1 = await responsePromise1;
    expect(response1.status(), 'create tag response status').toBe(200);
    expect((await response1.json()).tag.slug, 'created tag slug').toBe("env-prod");

    // Wait for network activities to finish
    await page.waitForTimeout(2000);

    const responsePromise2 = page.waitForResponse("**/api/v4/secrets/**/tags**");
    await page.getByRole("button", { name: "Save Tags" }).click();
    const response2 = await responsePromise2;
    expect(response2.status(), 'attach tags response status').toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(2000);

    // Reopen the tag editor to confirm the attach persisted, then detach it
    await page.getByRole("row", { name: "API_KEY" }).hover();
    await page.getByRole("row", { name: "API_KEY" }).locator('button:has(svg[class*="lucide-tags"])').first().click();
    await expect(page.getByRole("button", { name: "Remove env-prod" })).toBeVisible();
    await expect(page.getByText("env-prod", { exact: true })).toBeVisible();
    await page.getByRole("button", { name: "Remove env-prod" }).click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise3 = page.waitForResponse("**/api/v4/secrets/**/tags**");
    await page.getByRole("button", { name: "Save Tags" }).click();
    const response3 = await responsePromise3;
    expect(response3.status(), 'detach tags response status').toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(2000);

    // Reopen the tag editor once more to confirm the detach removed the tag
    await page.getByRole("row", { name: "API_KEY" }).hover();
    await page.getByRole("row", { name: "API_KEY" }).locator('button:has(svg[class*="lucide-tags"])').first().click();
    await expect(page.getByText("Select or create tags...")).toBeVisible();
    await page.getByRole("button", { name: "Close" }).click();

    expect(pageErrors, 'uncaught page errors').toHaveLength(0);
});
