// Generated by Skyramp v1.3.40 on 2026-08-27 15:04:47.429963815 +0000 UTC m=+1537.925445275
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output trash_secret_delete_does_not_archive.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/trash_secret_delete_restore_workflow_trace.zip

// Import of required libraries
import { test, expect, checkRequestPayload, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(2402000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // Expected request payloads for network assertions
    const expectedPayload1 = {
        "changes": {
            "secrets": {"delete": [{
                    "comment": "",
                    "resourceType": "secret",
                    "secretKey": "TESTBOT_TRASH_SECRET",
                    "secretValue": "<hidden-by-infisical>",
                    "type": "delete"
                }]},
            "folders": {"create": [], "update": [], "delete": []}
        },
        "environment": "dev",
        "message": "",
        "secretPath": "/"
    };

    await page.goto(`${baseUrl}/login`);
    await page.waitForLoadState('networkidle');
    // Wait for network activities to finish
    await page.waitForTimeout(15000);

    await page.waitForTimeout(2000);

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status(), 'login status code').toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Add New Project" }).click();
    await page.getByRole("textbox", { name: "Type your project name" }).fill("testbot-secrets-project");
    await page.getByRole("button", { name: "Create Project" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByText("Add a New Secret").click();
    await page.getByRole("textbox", { name: "Type your secret name" }).fill("TESTBOT_TRASH_SECRET");
    await page.getByRole("textbox", { name: "secret value" }).fill("super-secret-value-123");
    await page.getByRole("button", { name: "Create Secret" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(20000);

    // The "Add a New Secret" project overview page has no named delete action for a row.
    // The actual dashboard changed by this PR (ActionBar/SecretListView with the Trash button
    // and a "delete-value" row action) lives one level deeper, at .../secrets/<envSlug>.
    // Derive that URL from the current project overview URL instead of hardcoding the
    // project ID, since a new project is created on every run.
    const secretsExplorerUrl = page.url().replace(/\/overview$/, "/secrets/dev");
    await page.goto(secretsExplorerUrl);
    await page.waitForLoadState('networkidle');

    await page.getByRole("button", { name: "delete-value" }).waitFor({ state: "visible", timeout: 20000 });
    await expect(page.getByRole("button", { name: "delete-value" })).toHaveCount(1);

    await page.getByRole("button", { name: "delete-value" }).click();
    await page.getByRole("textbox", { name: "Type TESTBOT_TRASH_SECRET here" }).fill("TESTBOT_TRASH_SECRET");
    await page.getByRole("button", { name: "Delete Secret" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByText("1 pending change")).toBeVisible();

    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/v1/pit/batch/commit**");
    await page.getByRole("button", { name: "Save Changes" }).click();
    const response1 = await responsePromise1;
    expect(response1.status(), 'batch commit status code').toBe(200);
    // Validate request payload
    checkRequestPayload(response1.request().postDataJSON(), expectedPayload1);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    // The secret is gone from the main list (looks archived from the dashboard's point of view)
    await expect(page.getByRole("button", { name: "delete-value" })).toHaveCount(0);

    await page.getByRole("button", { name: "Trash" }).click();

    // Bug: the PR's stated behavior is that deleting a secret archives it and it can be
    // restored from the Trash. In practice, the default dashboard mode (isBatchMode) commits
    // deletes through POST /api/v1/pit/batch/commit -> secretV2BridgeService.deleteManySecret,
    // which permanently removes the row and never calls the new archiveSecrets() path. So the
    // secret we just deleted should appear here but the Trash is actually empty.
    await expect(page.getByText("TESTBOT_TRASH_SECRET")).toBeVisible();

    await page.getByRole("button", { name: "Close" }).click();

    expect(errors, 'uncaught page errors').toHaveLength(0);
});
