// Generated by Skyramp v1.3.38 on 2026-08-19 15:51:32.71879348 +0000 UTC m=+2018.239038984
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output ui_copy_secrets_overwrite_conflict_error.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/ui_copy_secrets_overwrite_conflict_error_trace.zip

// Import of required libraries
import { test, checkRequestPayload, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(239000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    // Expected request payloads for network assertions
    const expectedPayload1 = {
        "destinationEnvironment": "staging",
        "destinationSecretPath": "/",
        "sourceEnvironment": "dev",
        "sourceSecretPath": "/",
        "secretIds": null
    };

    const pageErrors: Error[] = [];
    page.on("pageerror", (err) => pageErrors.push(err));

    await page.goto(`${baseUrl}/login`);
    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto(`${baseUrl}/organizations/db7fbc02-8551-4633-af61-c6a80954379a/projects/secret-management/196b7b30-402b-49a1-8ad1-6c4296407302/secrets/staging`);
    await page.getByRole("button", { name: "Reveal" }).waitFor({ state: "visible", timeout: 20000 });
    await page.getByRole("button", { name: "Reveal" }).click();
    await expect(page.getByRole("textbox", { name: "secret value" })).toHaveValue("staging-original-value");
    await page.getByRole("button", { name: "Copy Secrets From An" }).click();
    await page.locator("#react-select-3-input").click();
    await page.getByRole("option", { name: "CONFLICT_KEY" }).click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/v4/secrets/copy**");
    await page.getByRole("button", { name: "Copy Secrets" }).click();
    const response1 = await responsePromise1;
    // Validate request payload
    checkRequestPayload(response1.request().postDataJSON(), expectedPayload1);

    // Wait for the post-copy query invalidation/refetch to settle before reading the DOM
    await page.waitForTimeout(3000);

    // The destination key CONFLICT_KEY already existed and shouldOverwrite was left off,
    // so the copy must be rejected and the original destination value must survive untouched.
    await expect(page.getByRole("textbox", { name: "secret value" })).toHaveValue("staging-original-value", { timeout: 10000 });
    expect(pageErrors).toHaveLength(0);
});
