// Generated by Skyramp v1.3.38 on 2026-08-19 16:50:19.421590252 +0000 UTC m=+1691.682923710
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output folder_rename_ui_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/folder_rename_ui_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1316000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/login`);
    // Wait for network activities to finish
    await page.waitForTimeout(8250);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "All Projects" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.waitForSelector("text=Add New Project");
    const existingProject = page.getByRole("link", { name: "skyramp-test-project Secrets Management" });
    if (await existingProject.isVisible().catch(() => false)) {
        await existingProject.click();
    } else {
        await page.getByRole("button", { name: "Add New Project" }).click();
        await page.getByRole("textbox", { name: "Type your project name" }).fill("skyramp-test-project");
        await page.getByRole("button", { name: "Create Project" }).click();
        // Wait for network activities to finish
        await page.waitForTimeout(20000);
    }

    await page.locator(".inline-flex.items-center.active\\\\:scale-\\\\[0\\\\.99\\\\].justify-center.border.cursor-pointer.whitespace-nowrap.rounded-md.text-sm.font-medium.transition-all.disabled\\\\:pointer-events-none.disabled\\\\:opacity-50.\\\\[\\\\&_svg\\\\]\\\\:pointer-events-none.shrink-0.\\\\[\\\\&\\\\>svg\\\\]\\\\:shrink-0.focus-visible\\\\:ring-ring.outline-0.focus-visible\\\\:ring-2.border-project\\\\/25").click();
    await page.getByRole("menuitem", { name: "Add Folder" }).click();
    await page.getByRole("textbox", { name: "Type your folder name" }).fill("test-folder");
    await page.getByRole("button", { name: "Add Folder" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);
    await expect(page.getByRole("row", { name: "test-folder" })).toHaveCount(1);
    await expect(page.getByRole("cell", { name: "test-folder" })).toHaveText("test-folder");

    await page.getByRole("row", { name: "test-folder" }).hover();
    // Wait for network activities to finish
    await page.waitForTimeout(120000);

    await page.mouse.move(760, 363);
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.locator("body").click({ position: {"x": 1158, "y": 363} });
    await expect(page.getByRole("textbox", { name: "Type your folder name" })).toHaveValue("test-folder");
    await page.getByRole("textbox", { name: "Type your folder name" }).fill("test-folder-renamed");
    await page.getByRole("button", { name: "Update Folder" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.waitForSelector("text=test-folder-renamed");
    await expect(page.getByRole("row", { name: "test-folder-renamed" })).toHaveCount(1);
    await expect(page.getByRole("cell", { name: "test-folder-renamed" })).toHaveText("test-folder-renamed");
    expect(pageErrors).toHaveLength(0);
});
