// Generated by Skyramp v1.3.38 on 2026-08-19 05:55:13.974789016 +0000 UTC m=+971.511771582
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output identity_access_tokens_revoke_ui.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/identity_access_tokens_revoke_ui_trace.zip

// Import of required libraries
import { test, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(651000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/login`);
    // Wait for network activities to finish
    await page.waitForTimeout(6000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Access Control" }).click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/v1/identities/search**");
    await page.getByRole("link", { name: "Machine Identities" }).click();
    const response1 = await responsePromise1;

    // Wait for network activities to finish
    await page.waitForTimeout(20000);

    await page.getByRole("row", { name: "Instance Admin Identity" }).click();
    await page.getByRole("button", { name: "Revoke" }).click();
    await page.getByRole("textbox", { name: "Type confirm here" }).fill("confirm");
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise2 = page.waitForResponse("**/api/v1/identities/**/access-tokens/**/revoke**");
    await page.getByRole("button", { name: "Revoke" }).click();
    const response2 = await responsePromise2;
});
