// Generated by Skyramp v1.3.40 on 2026-08-27 14:29:40.832049064 +0000 UTC m=+862.167217167
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output share_secret_access_history_ui.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/share_secret_access_history_ui_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(468000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', (e) => errors.push(e));

    await page.goto(`${baseUrl}/login`);
    // Wait for network activities to finish
    await page.waitForTimeout(9750);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Secret Sharing" }).click();
    const existingActions = page.getByRole("button", { name: "actions" }).first();
    if (!await existingActions.isVisible().catch(() => false)) {
        await page.getByRole("button", { name: "Share Secret" }).click();
        await page.getByRole("textbox", { name: "Enter sensitive data to share" }).fill("my-test-secret-value");
        await page.getByRole("button", { name: "Advanced Settings" }).click();
        await page.locator("#notify-on-access").click();
        await expect(page.locator("#notify-on-access")).toBeChecked();
        await page.getByRole("button", { name: "Create Secret Link" }).click();
        await page.waitForTimeout(3000);
        await page.getByRole("button", { name: "Close" }).click();
    }
    await expect(page.getByRole("button", { name: "actions" }).first()).toBeVisible();
    await page.getByRole("button", { name: "actions" }).first().click();
    await page.getByRole("menuitem", { name: "Access history" }).click();
    await expect(page.getByText("Every attempt to open this")).toContainText("0 total");
    expect(errors).toHaveLength(0);
});
