// Generated by Skyramp v1.3.40 on 2026-08-27 14:44:35.966371844 +0000 UTC m=+1235.258878863
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output secrets_move_shared_cross_env_integration.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/skyramp-tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/skyramp-tests/scenario_secrets-move-shared-cross-env.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue, uniqueSuffix } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const secrets = "MOVE_TEST_KEY";

    // Request Body
    const v2WorkspacePostRequestBody: string = `{
        "projectName": "skyramp-move-it",
        "type": "secret-manager"
    }`;

    // Execute Request
    const v2WorkspacePostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v2/workspace",
        method: "POST",
        body: v2WorkspacePostRequestBody,
        headers: headers,
        dataOverride: {"projectName": uniqueSuffix("skyramp-move-it")}
    });

    // Generated Assertions
    expect(v2WorkspacePostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(v2WorkspacePostResponse, "project.id")).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getResponseValue(v2WorkspacePostResponse, "project.type")).toBe("secret-manager");

    // Request Body
    const secretsPostRequestBody: string = `{
        "environment": "dev",
        "projectId": "11111111-1111-4111-8111-111111111111",
        "secretPath": "/",
        "secretValue": "move-me",
        "type": "shared"
    }`;

    // Execute Request
    const secretsPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets/{secrets}",
        method: "POST",
        body: secretsPostRequestBody,
        headers: headers,
        pathParams: {"secrets": secrets},
        dataOverride: {"projectId": getResponseValue(v2WorkspacePostResponse, "project.id")}
    });

    // Generated Assertions
    expect(secretsPostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(secretsPostResponse, "secret.id")).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getResponseValue(secretsPostResponse, "secret.secretKey")).toBe("MOVE_TEST_KEY");
    expect(getResponseValue(secretsPostResponse, "secret.environment")).toBe("dev");
    expect(getResponseValue(secretsPostResponse, "secret.secretValue")).toBe("move-me");
    expect(getResponseValue(secretsPostResponse, "secret.type")).toBe("shared");

    // Request Body — projectId and secretIds are chained inline (dataOverride does not
    // preserve JSON array types, so the moved secret id is interpolated into the array here)
    const movePostRequestBody: string = `{
        "destinationEnvironment": "prod",
        "destinationSecretPath": "/",
        "projectId": "${getResponseValue(v2WorkspacePostResponse, "project.id")}",
        "secretIds": [
            "${getResponseValue(secretsPostResponse, "secret.id")}"
        ],
        "shouldOverwrite": false,
        "sourceEnvironment": "dev",
        "sourceSecretPath": "/"
    }`;

    // Execute Request
    const movePostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets/move",
        method: "POST",
        body: movePostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(movePostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(movePostResponse, "isSourceUpdated")).toBe(true);
    expect(getResponseValue(movePostResponse, "isDestinationUpdated")).toBe(true);
    expect(getResponseValue(movePostResponse, "movedOverridesCount")).toBe(0);

    // Execute Request
    const secretsGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets/{secrets}",
        method: "GET",
        headers: headers,
        pathParams: {"secrets": getResponseValue(secretsPostResponse, "secret.secretKey")},
        queryParams: {
            "environment": ["prod"],
            "projectId": [getResponseValue(v2WorkspacePostResponse, "project.id")],
            "secretPath": ["/"]
        }
    });

    // Generated Assertions
    expect(secretsGetResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(secretsGetResponse, "secret.secretKey")).toBe(getResponseValue(secretsPostResponse, "secret.secretKey"));
    expect(getResponseValue(secretsGetResponse, "secret.environment")).toBe("prod");
    expect(getResponseValue(secretsGetResponse, "secret.secretValue")).toBe("move-me");

    // Execute Request
    const workspaceDeleteResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/workspace/{workspace}",
        method: "DELETE",
        headers: headers,
        pathParams: {"workspace": getResponseValue(v2WorkspacePostResponse, "project.id")}
    });

    // Generated Assertions
    expect(workspaceDeleteResponse.statusCode, 'status code').toBe(200);
});
