// Generated by Skyramp v1.3.40 on 2026-08-27 14:44:25.596726744 +0000 UTC m=+1224.889233749
// Command: skyramp generate contract rest http://localhost:8080/api/v4/secrets/move \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output secrets_move_nonexistent_project_contract.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/skyramp-tests \
// 		--overwrite \
// 		--provider \
// 		--request-data {"projectId":"00000000-0000-4000-8000-000000000000","sourceEnvironment":"dev","sourceSecretPath":"/","destinationEnvironment":"prod","destinationSecretPath":"/","secretIds":["00000000-0000-4000-8000-000000000001"],"shouldOverwrite":false} \
// 		--response-status-code 404 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

// contract test for /api/v4/secrets/move POST
test('testMovePost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const movePostRequestBody: string = `{
        "destinationEnvironment": "prod",
        "destinationSecretPath": "/",
        "projectId": "00000000-0000-4000-8000-000000000000",
        "secretIds": [
            "00000000-0000-4000-8000-000000000001"
        ],
        "shouldOverwrite": false,
        "sourceEnvironment": "dev",
        "sourceSecretPath": "/"
    }`;

    // Execute Request
    const movePostResponse = await client.sendRequest({
        url: URL,
        path: "/api/v4/secrets/move",
        method: "POST",
        body: movePostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(movePostResponse.statusCode, 'status code').toBe(404);
    expect(getValue(movePostResponse, "error")).toBe("NotFound");
    expect(getValue(movePostResponse, "statusCode")).toBe(404);
});
