// Generated by Skyramp v1.3.40 on 2026-08-27 14:29:44.203570854 +0000 UTC m=+663.028887399
// Command: skyramp generate contract rest http://localhost:8080/api/v1/pam/resources/ai-insights/models \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output contract_pam_ai_insights_models.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests \
// 		--overwrite \
// 		--provider \
// 		--provider-output contract_pam_ai_insights_models.spec.ts \
// 		--response-status-code 403 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

// contract test for /api/v1/pam/resources/ai-insights/models GET
test('testModelsGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const modelsGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/v1/pam/resources/ai-insights/models",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(modelsGetResponse.statusCode, 'status code').toBe(403);
    expect(getValue(modelsGetResponse, "statusCode"), 'body statusCode').toBe(403);
    expect(getValue(modelsGetResponse, "message"), 'message').toBe("You are not allowed to access this resource");
    expect(getValue(modelsGetResponse, "error"), 'error').toBe("Forbidden access to /api/v1/pam/resources/ai-insights/models");
    expect(getValue(modelsGetResponse, "reqId"), 'reqId').not.toBeNull();
    expect(getValue(modelsGetResponse, "models"), 'model catalogue is withheld from a rejected caller').toBeNull();
});
