// Generated by Skyramp v1.3.40 on 2026-08-27 15:21:06.750448157 +0000 UTC m=+865.134605643
// Command: skyramp generate contract rest http://localhost:8080/api/v4/secrets/id/{secretId} \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output contract_secrets_get_by_id.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests \
// 		--overwrite \
// 		--path-params secretId=b47e2c19-8f3d-4a56-91c0-6d2e83f4a7b5 \
// 		--provider \
// 		--provider-output contract_secrets_get_by_id.spec.ts \
// 		--response-status-code 404 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

// contract test for /api/v4/secrets/id/{secretId} GET
test('testIdSecretIdGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const secretId = "b47e2c19-8f3d-4a56-91c0-6d2e83f4a7b5";

    // Execute Request
    const idSecretIdGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/v4/secrets/id/{secretId}",
        method: "GET",
        headers: headers,
        pathParams: {"secretId": secretId}
    });

    // Generated Assertions
    expect(idSecretIdGetResponse.statusCode, 'status code').toBe(404);
    expect(getValue(idSecretIdGetResponse, "statusCode"), 'body statusCode').toBe(404);
    expect(getValue(idSecretIdGetResponse, "error"), 'error').toBe("GetSecretById");
    expect(getValue(idSecretIdGetResponse, "message"), 'message').toBe(`Secret with ID '${secretId}' not found`);
    expect(getValue(idSecretIdGetResponse, "secret"), 'no secret leaked on a 404').toBeUndefined();
});
