# Generated by Skyramp v1.3.38 on 2026-08-19 17:48:56.178189987 +0000 UTC m=+699.881117487
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--chaining-key id \
# 		--framework pytest \
# 		--language python \
# 		--output folder_rename_cascades_secret_references_integration_test.py \
# 		--output-dir /home/runner/work/infisical/infisical/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/infisical/infisical/tests/scenario_folder_rename_cascades_secret_references.json

# Import of required libraries
import skyramp
import os
import re
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    raw = "TARGET"
    raw_1 = "CONSUMER"

    # Request Body
    workspace_POST_request_body = r'''{
        "projectName": "skyramp-refs",
        "slug": "skyramp-refs"
    }'''

    # Execute Request
    workspace_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/workspace",
        method="POST",
        body=workspace_POST_request_body,
        headers=headers,
        data_override={
            "projectName": skyramp.unique_suffix("skyramp-refs"),
            "slug": skyramp.unique_suffix("skyramp-refs")
        }
    )

    # Generated Assertions
    assert workspace_POST_response.status_code == 200
    project_id = skyramp.get_response_value(workspace_POST_response, "project.id")
    assert re.match(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", project_id, re.I)
    assert skyramp.get_response_value(workspace_POST_response, "project.type") == "secret-manager"
    assert skyramp.get_response_value(workspace_POST_response, "project.environments.0.slug") == "dev"
    assert skyramp.get_response_value(workspace_POST_response, "project.environments.1.slug") == "staging"

    # Request Body
    folders_POST_request_body = r'''{
        "environment": "dev",
        "name": "refsrc",
        "path": "/",
        "projectId": "3f6c1d84-9a52-4e7b-8c11-2b7e5a904d31"
    }'''

    # Execute Request
    folders_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/folders",
        method="POST",
        body=folders_POST_request_body,
        headers=headers,
        data_override={"projectId": project_id}
    )

    # Generated Assertions
    assert folders_POST_response.status_code == 200
    folder_id = skyramp.get_response_value(folders_POST_response, "folder.id")
    assert re.match(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", folder_id, re.I)
    assert skyramp.get_response_value(folders_POST_response, "folder.name") == "refsrc"
    assert skyramp.get_response_value(folders_POST_response, "folder.path") == "/refsrc"
    assert skyramp.get_response_value(folders_POST_response, "folder.isReserved") is False
    assert skyramp.get_response_value(folders_POST_response, "folder.version") == 1

    # Request Body
    raw_POST_request_body = r'''{
        "environment": "dev",
        "secretPath": "/refsrc",
        "secretValue": "target-value",
        "workspaceId": "3f6c1d84-9a52-4e7b-8c11-2b7e5a904d31"
    }'''

    # Execute Request
    raw_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v3/secrets/raw/{raw}",
        method="POST",
        body=raw_POST_request_body,
        headers=headers,
        path_params={"raw": raw},
        data_override={"workspaceId": project_id}
    )

    # Generated Assertions
    assert raw_POST_response.status_code == 200
    assert skyramp.get_response_value(raw_POST_response, "secret.secretKey") == "TARGET"
    assert skyramp.get_response_value(raw_POST_response, "secret.secretValue") == "target-value"
    assert skyramp.get_response_value(raw_POST_response, "secret.version") == 1

    # Request Body
    raw_POST_1_request_body = r'''{
        "environment": "dev",
        "secretPath": "/",
        "secretValue": "pre-${dev.refsrc.TARGET}-post",
        "workspaceId": "3f6c1d84-9a52-4e7b-8c11-2b7e5a904d31"
    }'''

    # Execute Request
    raw_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/v3/secrets/raw/{raw}",
        method="POST",
        body=raw_POST_1_request_body,
        headers=headers,
        path_params={"raw": raw_1},
        data_override={"workspaceId": project_id}
    )

    # Generated Assertions
    assert raw_POST_1_response.status_code == 200
    assert skyramp.get_response_value(raw_POST_1_response, "secret.secretKey") == "CONSUMER"
    assert skyramp.get_response_value(raw_POST_1_response, "secret.secretValue") == "pre-${dev.refsrc.TARGET}-post"
    assert skyramp.get_response_value(raw_POST_1_response, "secret.version") == 1

    # Request Body
    folders_folders_PATCH_request_body = r'''{
        "environment": "dev",
        "name": "refdst",
        "path": "/",
        "projectId": "3f6c1d84-9a52-4e7b-8c11-2b7e5a904d31"
    }'''

    # Execute Request
    folders_folders_PATCH_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/folders/{folders}",
        method="PATCH",
        body=folders_folders_PATCH_request_body,
        headers=headers,
        path_params={"folders": folder_id},
        data_override={"projectId": project_id}
    )

    # Generated Assertions
    assert folders_folders_PATCH_response.status_code == 200
    assert skyramp.get_response_value(folders_folders_PATCH_response, "folder.id") == folder_id
    assert skyramp.get_response_value(folders_folders_PATCH_response, "folder.name") == "refdst"
    assert skyramp.get_response_value(folders_folders_PATCH_response, "folder.path") == "/refdst"
    assert skyramp.get_response_value(folders_folders_PATCH_response, "folder.version") == 2
    assert skyramp.get_response_value(folders_folders_PATCH_response, "folder.isReserved") is False
    # No secret import targets this folder, so the import counter must be 0.
    assert skyramp.get_response_value(folders_folders_PATCH_response, "updatedImportsCount") == 0
    # Exactly one secret (CONSUMER) references ${dev.refsrc.TARGET}, so the rename must rewrite it and count it.
    assert skyramp.get_response_value(folders_folders_PATCH_response, "updatedReferencesCount") == 1

    # Execute Request
    raw_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v3/secrets/raw/{raw}",
        method="GET",
        headers=headers,
        path_params={"raw": skyramp.get_response_value(raw_POST_1_response, "secret.secretKey")},
        query_params={
            "environment": ["dev"],
            "expandSecretReferences": ["false"],
            "secretPath": ["/"],
            "workspaceId": [project_id]
        }
    )

    # Generated Assertions
    assert raw_GET_response.status_code == 200
    assert skyramp.get_response_value(raw_GET_response, "secret.secretKey") == "CONSUMER"
    assert skyramp.get_response_value(raw_GET_response, "secret.environment") == "dev"
    assert skyramp.get_response_value(raw_GET_response, "secret.secretPath") == "/"
    # The reference must now point at the renamed folder, not the dangling old path.
    assert skyramp.get_response_value(raw_GET_response, "secret.secretValue") == "pre-${dev.refdst.TARGET}-post"


if __name__ == "__main__":
    test_integration()
