# Generated by Skyramp v1.3.38 on 2026-08-19 17:48:47.339930138 +0000 UTC m=+691.042857618
# Command: skyramp generate contract rest http://localhost:8080/api/v2/folders/{folderId} \
# 		--framework pytest \
# 		--language python \
# 		--method PATCH \
# 		--output folder_rename_requires_auth_contract_test.py \
# 		--output-dir /home/runner/work/infisical/infisical/tests \
# 		--overwrite \
# 		--path-params folderId=7d1e6b48-3c05-4a92-b6f7-25e4c8a09d16 \
# 		--provider \
# 		--provider-output folder_rename_requires_auth_contract_test.py \
# 		--request-data {"projectId":"9a4c2f61-7b83-4d50-8e29-14f6b0d7c3a5","environment":"dev","name":"renamed","path":"/"} \
# 		--response-status-code 401 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

# contract test for /api/v2/folders/{folderId} PATCH
def test_folders_folder_id_patch():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    folderId = "7d1e6b48-3c05-4a92-b6f7-25e4c8a09d16"

    # Request Body
    folders_folderId_PATCH_request_body = r'''{
        "environment": "dev",
        "name": "renamed",
        "path": "/",
        "projectId": "9a4c2f61-7b83-4d50-8e29-14f6b0d7c3a5"
    }'''

    # Execute Request
    folders_folderId_PATCH_response = client.send_request(
        url=URL,
        path="/api/v2/folders/{folderId}",
        method="PATCH",
        body=folders_folderId_PATCH_request_body,
        headers=headers,
        path_params={"folderId": folderId}
    )

    # Generated Assertions
    assert folders_folderId_PATCH_response.status_code == 401
    # The rename cascade rewrites secret_imports rows and re-encrypts secret values, so an
    # anonymous caller must be turned away at the auth gate with a body, not just a bare status.
    assert skyramp.get_response_value(folders_folderId_PATCH_response, "statusCode") == 401
    assert skyramp.get_response_value(folders_folderId_PATCH_response, "error") == "UnauthorizedError"
    assert skyramp.get_response_value(folders_folderId_PATCH_response, "message") == "Token missing"


if __name__ == "__main__":
    test_folders_folder_id_patch()
