# Generated by Skyramp v1.3.38 on 2026-08-19 15:36:57.710914703 +0000 UTC m=+519.333523553
# Command: skyramp generate contract rest http://localhost:8080/api/v4/secrets/expiring-soon \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output secret_expiring_soon_empty_contract_test.py \
# 		--output-dir /home/runner/work/infisical/infisical/tests \
# 		--overwrite \
# 		--provider \
# 		--query-params projectId=77fa7aed-9288-401e-a4c9-3a9430be62a4,environment=dev,secretPath=/,days=1 \
# 		--response-data {"secrets":[]} \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

# contract test for /api/v4/secrets/expiring-soon GET
def test_expiring_soon_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_expiring_soon_GET_response_body = r'''{
        "secrets": []
    }'''

    # Execute Request
    expiring_soon_GET_response = client.send_request(
        url=URL,
        path="/api/v4/secrets/expiring-soon",
        method="GET",
        headers=headers,
        query_params={
            "days": "1",
            "environment": "dev",
            "projectId": "77fa7aed-9288-401e-a4c9-3a9430be62a4",
            "secretPath": "/"
        }
    )

    # Generated Assertions
    assert expiring_soon_GET_response.status_code == 200
    assert skyramp.check_schema(expiring_soon_GET_response, expected_expiring_soon_GET_response_body)
    assert len(skyramp.get_response_value(expiring_soon_GET_response, "secrets")) == 0
    assert skyramp.get_response_value(expiring_soon_GET_response, "secrets.0") is None


if __name__ == "__main__":
    test_expiring_soon_get()
