// Generated by Skyramp v1.3.38 on 2026-08-19 15:40:59.698666475 +0000 UTC m=+761.321275325
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_item_expiry_badge_ui_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_item_expiry_badge_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(438000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/login`);
    // Wait for network activities to finish
    await page.waitForTimeout(9000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "All Projects" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(17672);

    const existingProject = page.getByRole("link", { name: "test-expiry-project Secrets Management" });
    if (await existingProject.isVisible().catch(() => false)) {
        await existingProject.click();
    } else {
        await page.getByRole("button", { name: "Add New Project" }).click();
        await page.getByRole("textbox", { name: "Type your project name" }).fill("test-expiry-project");
        await page.getByRole("button", { name: "Create Project" }).click();
        // Wait for network activities to finish
        await page.waitForTimeout(3000);
    }

    const existingSecret = page.getByRole("row", { name: "MY_EXPIRY_TEST_SECRET" });
    if (!(await existingSecret.isVisible().catch(() => false))) {
        await page.getByText("Add a New Secret").click();
        await page.getByRole("textbox", { name: "Type your secret name" }).fill("MY_EXPIRY_TEST_SECRET");
        await page.getByRole("textbox", { name: "secret value" }).fill("test-expiry-value");
        await page.getByRole("button", { name: "Create Secret" }).click();
        // Wait for network activities to finish
        await page.waitForTimeout(9147);
    }

    await expect(page.getByRole("textbox", { name: "Secret name" })).toHaveValue("MY_EXPIRY_TEST_SECRET");
    await expect(page.getByRole("button", { name: "Reveal Values" })).toBeVisible();
    await expect(errors).toHaveLength(0);
});
