// Generated by Skyramp v1.3.40 on 2026-08-27 15:21:14.045203359 +0000 UTC m=+872.429360866
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output secrets_multipath_precedence_merge_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/tests/scenario_secrets-multipath-precedence-merge.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue, uniqueSuffix } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const secrets = "SHARED_KEY";
    const secrets_1 = "ONLY_BASE";

    // Request Body
    const projectsPostRequestBody: string = `{
        "projectName": "mp-precedence",
        "slug": "mp-precedence-proj"
    }`;

    // Execute Request
    const projectsPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/projects",
        method: "POST",
        body: projectsPostRequestBody,
        headers: headers,
        dataOverride: {"slug": uniqueSuffix("mp-precedence-proj")}
    });

    // Generated Assertions
    expect(projectsPostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(projectsPostResponse, "project.id"), 'project.id').toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getResponseValue(projectsPostResponse, "project.name"), 'project.name').toBe("mp-precedence");
    expect(getResponseValue(projectsPostResponse, "project.slug"), 'project.slug').toMatch(/^mp-precedence-proj/);

    const projectId = getResponseValue(projectsPostResponse, "project.id");

    // Request Body
    const foldersPostRequestBody: string = `{
        "environment": "dev",
        "name": "base",
        "path": "/",
        "workspaceId": "${projectId}"
    }`;

    // Execute Request
    const foldersPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/folders",
        method: "POST",
        body: foldersPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(foldersPostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(foldersPostResponse, "folder.name"), 'folder.name').toBe("base");
    expect(getResponseValue(foldersPostResponse, "folder.version"), 'folder.version').toBe(1);

    // Request Body
    const foldersPost1RequestBody: string = `{
        "environment": "dev",
        "name": "app",
        "path": "/",
        "workspaceId": "${projectId}"
    }`;

    // Execute Request
    const foldersPost1Response = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/folders",
        method: "POST",
        body: foldersPost1RequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(foldersPost1Response.statusCode, 'status code').toBe(200);
    expect(getResponseValue(foldersPost1Response, "folder.name"), 'folder.name').toBe("app");
    expect(getResponseValue(foldersPost1Response, "folder.version"), 'folder.version').toBe(1);

    // Request Body
    const secretsSecretsPostRequestBody: string = `{
        "environment": "dev",
        "projectId": "${projectId}",
        "secretPath": "/base",
        "secretValue": "base-val"
    }`;

    // Execute Request
    const secretsSecretsPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets/{secrets}",
        method: "POST",
        body: secretsSecretsPostRequestBody,
        headers: headers,
        pathParams: {"secrets": secrets}
    });

    // Generated Assertions
    expect(secretsSecretsPostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(secretsSecretsPostResponse, "secret.secretKey"), 'secret.secretKey').toBe("SHARED_KEY");
    expect(getResponseValue(secretsSecretsPostResponse, "secret.secretValue"), 'secret.secretValue').toBe("base-val");
    expect(getResponseValue(secretsSecretsPostResponse, "secret.type"), 'secret.type').toBe("shared");
    expect(getResponseValue(secretsSecretsPostResponse, "secret.version"), 'secret.version').toBe(1);

    // Request Body
    const secretsSecretsPost1RequestBody: string = `{
        "environment": "dev",
        "projectId": "${projectId}",
        "secretPath": "/base",
        "secretValue": "only-base"
    }`;

    // Execute Request
    const secretsSecretsPost1Response = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets/{secrets}",
        method: "POST",
        body: secretsSecretsPost1RequestBody,
        headers: headers,
        pathParams: {"secrets": secrets_1}
    });

    // Generated Assertions
    expect(secretsSecretsPost1Response.statusCode, 'status code').toBe(200);
    expect(getResponseValue(secretsSecretsPost1Response, "secret.secretKey"), 'secret.secretKey').toBe("ONLY_BASE");
    expect(getResponseValue(secretsSecretsPost1Response, "secret.secretValue"), 'secret.secretValue').toBe("only-base");
    expect(getResponseValue(secretsSecretsPost1Response, "secret.type"), 'secret.type').toBe("shared");

    // Request Body
    const secretsSecretsPost2RequestBody: string = `{
        "environment": "dev",
        "projectId": "${projectId}",
        "secretPath": "/app",
        "secretValue": "app-val"
    }`;

    // Execute Request
    const secretsSecretsPost2Response = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets/{secrets}",
        method: "POST",
        body: secretsSecretsPost2RequestBody,
        headers: headers,
        pathParams: {"secrets": getResponseValue(secretsSecretsPostResponse, "secret.secretKey")}
    });

    // Generated Assertions
    expect(secretsSecretsPost2Response.statusCode, 'status code').toBe(200);
    expect(getResponseValue(secretsSecretsPost2Response, "secret.secretKey"), 'secret.secretKey').toBe("SHARED_KEY");
    expect(getResponseValue(secretsSecretsPost2Response, "secret.secretValue"), 'secret.secretValue').toBe("app-val");
    expect(getResponseValue(secretsSecretsPost2Response, "secret.type"), 'secret.type').toBe("shared");

    // Execute Request
    const secretsGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets",
        method: "GET",
        headers: headers,
        queryParams: {
            "environment": ["dev"],
            "projectId": [projectId],
            "secretPaths": ["/base,/app"],
            "viewSecretValue": ["true"]
        }
    });

    // Generated Assertions
    expect(secretsGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(secretsGetResponse, "secrets").length, 'merged secret count').toBe(2);
    expect(getValue(secretsGetResponse, "secrets.2"), 'no third merged secret').toBeUndefined();
    expect(getResponseValue(secretsGetResponse, "secrets.0.secretKey"), 'secrets.0.secretKey').toBe("SHARED_KEY");
    expect(getResponseValue(secretsGetResponse, "secrets.0.secretValue"), 'later path wins the key conflict').toBe("app-val");
    expect(getResponseValue(secretsGetResponse, "secrets.0.secretPath"), 'secrets.0.secretPath').toBe("/app");
    expect(getResponseValue(secretsGetResponse, "secrets.0.type"), 'secrets.0.type').toBe("shared");
    expect(getResponseValue(secretsGetResponse, "secrets.1.secretKey"), 'secrets.1.secretKey').toBe("ONLY_BASE");
    expect(getResponseValue(secretsGetResponse, "secrets.1.secretValue"), 'unique key survives the merge').toBe("only-base");
    expect(getResponseValue(secretsGetResponse, "secrets.1.secretPath"), 'secrets.1.secretPath').toBe("/base");
    expect(getValue(secretsGetResponse, "merge.paths").length, 'merge.paths length').toBe(2);
    expect(getResponseValue(secretsGetResponse, "merge.paths.0"), 'merge.paths.0').toBe("/base");
    expect(getResponseValue(secretsGetResponse, "merge.paths.1"), 'merge.paths.1').toBe("/app");
    expect(getValue(secretsGetResponse, "merge.overrides").length, 'merge.overrides length').toBe(1);
    expect(getValue(secretsGetResponse, "merge.overrides.1"), 'no second override').toBeUndefined();
    expect(getResponseValue(secretsGetResponse, "merge.overrides.0.secretKey"), 'overridden key').toBe("SHARED_KEY");
    expect(getResponseValue(secretsGetResponse, "merge.overrides.0.type"), 'overridden type').toBe("shared");
    expect(getResponseValue(secretsGetResponse, "merge.overrides.0.winningPath"), 'winning path').toBe("/app");
    expect(getValue(secretsGetResponse, "merge.overrides.0.overriddenPaths").length, 'overriddenPaths length').toBe(1);
    expect(getResponseValue(secretsGetResponse, "merge.overrides.0.overriddenPaths.0"), 'overridden path').toBe("/base");
});
