# Generated by Skyramp v1.3.38 on 2026-08-19 15:37:59.142499254 +0000 UTC m=+580.765108094
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output secret_expiry_window_bug_integration_test.py \
# 		--output-dir /home/runner/work/infisical/infisical/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/infisical/infisical/tests/scenario_secret-expiry-window-bug.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    secrets = "EXPIRY-WINDOW-BUG"

    # Request Body
    secrets_POST_request_body = r'''{
        "environment": "dev",
        "expiresAt": "2026-08-22T00:00:00.000Z",
        "projectId": "77fa7aed-9288-401e-a4c9-3a9430be62a4",
        "secretKey": "EXPIRY-WINDOW-BUG",
        "secretPath": "/",
        "secretValue": "test-value",
        "type": "shared"
    }'''

    # Execute Request
    secrets_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v4/secrets/{secrets}",
        method="POST",
        body=secrets_POST_request_body,
        headers=headers,
        path_params={"secrets": secrets},
        data_override={"secretKey": secrets}
    )

    # Generated Assertions
    assert secrets_POST_response.status_code == 200
    assert skyramp.get_response_value(secrets_POST_response, "secret.secretKey") == "EXPIRY-WINDOW-BUG"
    assert skyramp.get_response_value(secrets_POST_response, "secret.secretValue") == "test-value"
    assert skyramp.get_response_value(secrets_POST_response, "secret.expiresAt") is not None
    import re
    assert re.match(r'^\d{4}-\d{2}-\d{2}T', str(skyramp.get_response_value(secrets_POST_response, "secret.expiresAt")))
    assert re.match(r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', str(skyramp.get_response_value(secrets_POST_response, "secret.id")), re.IGNORECASE)

    # Execute Request
    expiring_soon_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v4/secrets/expiring-soon",
        method="GET",
        headers=headers,
        query_params={
            "days": ["7"],
            "environment": ["dev"],
            "projectId": ["77fa7aed-9288-401e-a4c9-3a9430be62a4"],
            "secretPath": ["/"]
        }
    )

    # Generated Assertions
    assert expiring_soon_GET_response.status_code == 200
    # Bug-catching assertion: secret with expiresAt 3 days from now must appear when days=7
    # This FAILS with current bug: SECONDS_PER_DAY (86400) used with Date.now() (ms) = 10 min window
    assert len(skyramp.get_response_value(expiring_soon_GET_response, "secrets")) >= 1
    assert skyramp.get_response_value(expiring_soon_GET_response, "secrets.0.secretKey") == skyramp.get_response_value(secrets_POST_response, "secret.secretKey")
    assert skyramp.get_response_value(expiring_soon_GET_response, "secrets.0.expiresAt") is not None
    assert skyramp.get_response_value(expiring_soon_GET_response, "secrets.0.version") >= 1
    assert skyramp.get_response_value(expiring_soon_GET_response, "secrets.0.id") == skyramp.get_response_value(secrets_POST_response, "secret.id")

    # Request Body
    secrets_DELETE_request_body = r'''{
        "environment": "dev",
        "projectId": "77fa7aed-9288-401e-a4c9-3a9430be62a4",
        "secretPath": "/"
    }'''

    # Execute Request
    secrets_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/v4/secrets/{secrets}",
        method="DELETE",
        body=secrets_DELETE_request_body,
        headers=headers,
        path_params={"secrets": skyramp.get_response_value(expiring_soon_GET_response, "secrets.0.secretKey")}
    )

    # Generated Assertions
    assert secrets_DELETE_response.status_code == 200


if __name__ == "__main__":
    test_integration()
