// Generated by Skyramp v1.3.40 on 2026-08-27 14:29:56.299486414 +0000 UTC m=+675.124802939
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output shared_secret_access_updates_last_viewed_at_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/tests/scenario_shared-secret-access-updates-last-viewed-at.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const sharedSecretsPostRequestBody: string = `{
        "accessType": "organization",
        "expiresIn": "1h",
        "name": "last-viewed-probe",
        "password": "CorrectHorse1!",
        "secretValue": "last-viewed-probe-value"
    }`;

    // Execute Request
    const sharedSecretsPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/shared-secrets",
        method: "POST",
        body: sharedSecretsPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(sharedSecretsPostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(sharedSecretsPostResponse, "name"), 'name').toBe("last-viewed-probe");
    expect(getResponseValue(sharedSecretsPostResponse, "accessType"), 'accessType').toBe("organization");
    expect(getResponseValue(sharedSecretsPostResponse, "type"), 'type').toBe("share");
    expect(getResponseValue(sharedSecretsPostResponse, "notifyOnAccess"), 'notifyOnAccess').toBe(false);
    expect(getResponseValue(sharedSecretsPostResponse, "id"), 'id').not.toBeNull();
    expect(getResponseValue(sharedSecretsPostResponse, "createdAt"), 'createdAt').toMatch(/^\d{4}-\d{2}-\d{2}T/);
    expect(getResponseValue(sharedSecretsPostResponse, "expiresAt"), 'expiresAt').toMatch(/^\d{4}-\d{2}-\d{2}T/);
    expect(getResponseValue(sharedSecretsPostResponse, "lastViewedAt"), 'lastViewedAt is unset before any access').toBeNull();

    // Request Body
    const accessPostRequestBody: string = `{
        "password": "CorrectHorse1!"
    }`;

    // Execute Request
    const accessPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/shared-secrets/{shared-secrets}/access",
        method: "POST",
        body: accessPostRequestBody,
        headers: headers,
        pathParams: {"shared-secrets": getResponseValue(sharedSecretsPostResponse, "id")}
    });

    // Generated Assertions
    expect(accessPostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(accessPostResponse, "secretValue"), 'secretValue').toBe("last-viewed-probe-value");
    expect(getResponseValue(accessPostResponse, "name"), 'name').toBe("last-viewed-probe");
    expect(getResponseValue(accessPostResponse, "id"), 'id').toBe(getResponseValue(sharedSecretsPostResponse, "id"));
    expect(getResponseValue(accessPostResponse, "accessType"), 'accessType').toBe("organization");

    // Execute Request
    const sharedSecretsGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/shared-secrets",
        method: "GET",
        headers: headers,
        queryParams: {
            "limit": ["25"],
            "offset": ["0"]
        }
    });

    // Generated Assertions
    expect(sharedSecretsGetResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(sharedSecretsGetResponse, "totalCount"), 'totalCount').toBeGreaterThanOrEqual(1);
    expect(getResponseValue(sharedSecretsGetResponse, "secrets.25"), 'page size honours limit=25').toBeNull();
    expect(getResponseValue(sharedSecretsGetResponse, "secrets.0.id"), 'newest share is the one just created').toBe(getResponseValue(sharedSecretsPostResponse, "id"));
    expect(getResponseValue(sharedSecretsGetResponse, "secrets.0.name"), 'name').toBe("last-viewed-probe");
    expect(getResponseValue(sharedSecretsGetResponse, "secrets.0.notifyOnAccess"), 'notifyOnAccess').toBe(false);
    expect(getResponseValue(sharedSecretsGetResponse, "secrets.0.lastViewedAt"), 'lastViewedAt is stamped after the share was opened').toMatch(/^\d{4}-\d{2}-\d{2}T/);
});
