// Generated by Skyramp v1.3.40 on 2026-08-27 14:24:39.896298165 +0000 UTC m=+775.743310393
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output shared_secret_password_rotation_not_persisted_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/tests/scenario_shared-secret-password-rotation-not-persisted.json

// Import of required libraries
import { test, expect, SkyrampClient, checkSchema, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const sharedSecretsPostRequestBody: string = `{
        "accessType": "organization",
        "expiresIn": "1h",
        "name": "rotation-probe",
        "password": "OldPassword123!",
        "secretValue": "ssh-key-abc123-contractor"
    }`;

    // Execute Request
    const sharedSecretsPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/shared-secrets",
        method: "POST",
        body: sharedSecretsPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(sharedSecretsPostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(sharedSecretsPostResponse, "name"), 'name').toBe("rotation-probe");
    expect(getResponseValue(sharedSecretsPostResponse, "accessType"), 'accessType').toBe("organization");
    expect(getResponseValue(sharedSecretsPostResponse, "type"), 'type').toBe("share");
    expect(getResponseValue(sharedSecretsPostResponse, "id"), 'id').not.toBeNull();
    expect(getResponseValue(sharedSecretsPostResponse, "expiresAt"), 'expiresAt').toMatch(/^\d{4}-\d{2}-\d{2}T/);
    expect(getResponseValue(sharedSecretsPostResponse, "sharedSecretLink"), 'sharedSecretLink').toBe(`http://localhost:8080/shared/secret/${getResponseValue(sharedSecretsPostResponse, "id")}`);
    expect(checkSchema(sharedSecretsPostResponse, `{"authorizedEmails": null, "expiresAfterViews": null, "lastViewedAt": null}`), 'nullable fields present').toBeTruthy();

    // Request Body
    const sharedSecretsSharedSecretsPatchRequestBody: string = `{
        "name": "rotation-probe-rotated",
        "password": "NewPassword456!"
    }`;

    // Execute Request
    const sharedSecretsSharedSecretsPatchResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/shared-secrets/{shared-secrets}",
        method: "PATCH",
        body: sharedSecretsSharedSecretsPatchRequestBody,
        headers: headers,
        pathParams: {"shared-secrets": getResponseValue(sharedSecretsPostResponse, "id")}
    });

    // Generated Assertions
    expect(sharedSecretsSharedSecretsPatchResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(sharedSecretsSharedSecretsPatchResponse, "name"), 'name').toBe("rotation-probe-rotated");
    expect(getResponseValue(sharedSecretsSharedSecretsPatchResponse, "id"), 'id').toBe(getResponseValue(sharedSecretsPostResponse, "id"));
    expect(getResponseValue(sharedSecretsSharedSecretsPatchResponse, "accessType"), 'accessType').toBe("organization");
    expect(getResponseValue(sharedSecretsSharedSecretsPatchResponse, "type"), 'type').toBe("share");
    expect(getResponseValue(sharedSecretsSharedSecretsPatchResponse, "expiresAt"), 'expiresAt').toMatch(/^\d{4}-\d{2}-\d{2}T/);

    // Request Body
    const accessPostRequestBody: string = `{
        "password": "NewPassword456!"
    }`;

    // Execute Request
    const accessPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/shared-secrets/{shared-secrets}/access",
        method: "POST",
        body: accessPostRequestBody,
        headers: headers,
        pathParams: {"shared-secrets": getResponseValue(sharedSecretsPostResponse, "id")}
    });

    // Generated Assertions
    expect(accessPostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(accessPostResponse, "secretValue"), 'secretValue').toBe("ssh-key-abc123-contractor");
    expect(getResponseValue(accessPostResponse, "id"), 'id').toBe(getResponseValue(sharedSecretsPostResponse, "id"));
    expect(getResponseValue(accessPostResponse, "accessType"), 'accessType').toBe("organization");
    expect(getResponseValue(accessPostResponse, "type"), 'type').toBe("share");

    // Request Body
    const accessPost1RequestBody: string = `{
        "password": "OldPassword123!"
    }`;

    // Execute Request
    const accessPost1Response = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/shared-secrets/{shared-secrets}/access",
        method: "POST",
        body: accessPost1RequestBody,
        headers: headers,
        pathParams: {"shared-secrets": getResponseValue(sharedSecretsPostResponse, "id")}
    });

    // Generated Assertions
    expect(accessPost1Response.statusCode, 'status code').toBe(401);
    expect(getResponseValue(accessPost1Response, "statusCode"), 'body statusCode').toBe(401);
    expect(getResponseValue(accessPost1Response, "message"), 'message').toBe("Invalid credentials");
    expect(getResponseValue(accessPost1Response, "error"), 'error').toBe("UnauthorizedError");
    expect(getResponseValue(accessPost1Response, "secretValue"), 'secretValue').toBeUndefined();

    // Execute Request
    const sharedSecretsSharedSecretsDeleteResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/shared-secrets/{shared-secrets}",
        method: "DELETE",
        headers: headers,
        pathParams: {"shared-secrets": getResponseValue(sharedSecretsPostResponse, "id")}
    });

    // Generated Assertions
    expect(sharedSecretsSharedSecretsDeleteResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(sharedSecretsSharedSecretsDeleteResponse, "id"), 'id').toBe(getResponseValue(sharedSecretsPostResponse, "id"));
    expect(getResponseValue(sharedSecretsSharedSecretsDeleteResponse, "type"), 'type').toBe("share");
});
