// Generated by Skyramp v1.3.40 on 2026-08-26 19:19:12.745606341 +0000 UTC m=+675.521223850
// Command: skyramp generate contract rest http://localhost:8080/api/v1/webhooks/{webhookId}/deliveries \
// 		--api-schema /tmp/skyramp-openapi.json \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output-dir /home/runner/work/infisical/infisical/tests \
// 		--overwrite \
// 		--path-params webhookId=7c3e1a45-9b62-4d08-8f51-2a6c94e7db30 \
// 		--provider \
// 		--provider-output webhook_deliveries_list_contract.spec.ts \
// 		--response-status-code 200 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect, SkyrampClient, checkSchema, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

// contract test for /api/v1/webhooks/{webhookId}/deliveries GET
test('testDeliveriesGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const webhookId = "7c3e1a45-9b62-4d08-8f51-2a6c94e7db30";

    // Expected Response Body
    const expectedDeliveriesGetResponseBody: string = `{
        "deliveries": "array",
        "message": "string",
        "totalCount": "number"
    }`;

    // Execute Request
    const deliveriesGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/v1/webhooks/{webhookId}/deliveries",
        method: "GET",
        headers: headers,
        pathParams: {"webhookId": webhookId},
        queryParams: {
            "limit": 20,
            "offset": 0
        }
    });

    // Generated Assertions
    expect(deliveriesGetResponse.statusCode, 'status code').toBe(200);
    expect(checkSchema(deliveriesGetResponse, expectedDeliveriesGetResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(deliveriesGetResponse, "message"), 'message').toBe("Successfully fetched webhook deliveries");
    expect(getResponseValue(deliveriesGetResponse, "totalCount"), 'totalCount').toBeGreaterThanOrEqual(0);
    const deliveries = getResponseValue(deliveriesGetResponse, "deliveries");
    expect(deliveries.length, 'page size honours the limit query param').toBeLessThanOrEqual(20);
    expect(deliveries.length, 'offset=0 page returns every row when totalCount fits in one page')
        .toBe(Math.min(getResponseValue(deliveriesGetResponse, "totalCount"), 20));
    for (let i = 0; i < deliveries.length; i += 1) {
        expect(getResponseValue(deliveriesGetResponse, `deliveries.${i}.id`), 'delivery id').toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
        expect(getResponseValue(deliveriesGetResponse, `deliveries.${i}.webhookId`), 'delivery webhookId').toBe(webhookId);
        expect(["success", "failed"], 'delivery status').toContain(getResponseValue(deliveriesGetResponse, `deliveries.${i}.status`));
        expect(getResponseValue(deliveriesGetResponse, `deliveries.${i}.createdAt`), 'delivery createdAt').toMatch(/^\d{4}-\d{2}-\d{2}T/);
    }
    // the route orders by createdAt desc, so the newest delivery is first
    if (deliveries.length > 1) {
        expect(new Date(getResponseValue(deliveriesGetResponse, "deliveries.0.createdAt")).getTime(), 'newest first ordering')
            .toBeGreaterThanOrEqual(new Date(getResponseValue(deliveriesGetResponse, "deliveries.1.createdAt")).getTime());
    }
});
