// Generated by Skyramp v1.3.40 on 2026-08-26 19:19:57.393427089 +0000 UTC m=+720.169044608
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--chaining-key id \
// 		--framework playwright \
// 		--language typescript \
// 		--output webhook_list_environment_filter_isolation_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/tests/scenario_webhook-list-environment-filter-isolation.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, uniqueSuffix } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const projectsPostRequestBody: string = `{
        "projectName": "webhook-env-filter-qa",
        "shouldCreateDefaultEnvs": true,
        "type": "secret-manager"
    }`;

    // Execute Request
    const projectsPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/projects",
        method: "POST",
        body: projectsPostRequestBody,
        headers: headers,
        dataOverride: {"projectName": uniqueSuffix("webhook-env-filter-qa")}
    });

    // Generated Assertions
    expect(projectsPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(projectsPostResponse, "project.id"), 'project id').toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getValue(projectsPostResponse, "project.type"), 'project type').toBe("secret-manager");
    expect(getValue(projectsPostResponse, "project.name"), 'project name').toContain("webhook-env-filter-qa");

    const projectId = getValue(projectsPostResponse, "project.id");

    // Request Body
    const webhooksPostRequestBody: string = `{
        "environment": "dev",
        "projectId": "${projectId}",
        "secretPath": "/",
        "type": "general",
        "webhookUrl": "https://example.com/dev-hook"
    }`;

    // Execute Request
    const webhooksPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/webhooks",
        method: "POST",
        body: webhooksPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(webhooksPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(webhooksPostResponse, "message"), 'message').toBe("Successfully created webhook");
    expect(getValue(webhooksPostResponse, "webhook.id"), 'webhook id').toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getValue(webhooksPostResponse, "webhook.projectId"), 'webhook projectId').toBe(projectId);
    expect(getValue(webhooksPostResponse, "webhook.environment.slug"), 'webhook environment').toBe("dev");
    expect(getValue(webhooksPostResponse, "webhook.secretPath"), 'webhook secretPath').toBe("/");
    expect(getValue(webhooksPostResponse, "webhook.isDisabled"), 'webhook isDisabled').toBe(false);
    expect(getValue(webhooksPostResponse, "webhook.createdAt"), 'webhook createdAt').toMatch(/^\d{4}-\d{2}-\d{2}T/);

    const devWebhookId = getValue(webhooksPostResponse, "webhook.id");

    // Request Body
    const webhooksPost1RequestBody: string = `{
        "environment": "prod",
        "projectId": "${projectId}",
        "secretPath": "/",
        "type": "general",
        "webhookUrl": "https://example.com/prod-hook"
    }`;

    // Execute Request
    const webhooksPost1Response = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/webhooks",
        method: "POST",
        body: webhooksPost1RequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(webhooksPost1Response.statusCode, 'status code').toBe(200);
    expect(getValue(webhooksPost1Response, "message"), 'message').toBe("Successfully created webhook");
    expect(getValue(webhooksPost1Response, "webhook.projectId"), 'webhook projectId').toBe(projectId);
    expect(getValue(webhooksPost1Response, "webhook.environment.slug"), 'webhook environment').toBe("prod");
    expect(getValue(webhooksPost1Response, "webhook.secretPath"), 'webhook secretPath').toBe("/");

    // Execute Request
    const webhooksGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/webhooks",
        method: "GET",
        headers: headers,
        queryParams: {
            "environment": ["dev"],
            "projectId": [projectId]
        }
    });

    // Generated Assertions
    expect(webhooksGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(webhooksGetResponse, "message"), 'message').toBe("Successfully fetched webhook");
    // environment=dev was sent as a filter, so the prod webhook created above must NOT come back
    expect(getValue(webhooksGetResponse, "webhooks").length, 'webhook count for environment=dev').toBe(1);
    expect(getValue(webhooksGetResponse, "webhooks.0.id"), 'listed webhook id').toBe(devWebhookId);
    expect(getValue(webhooksGetResponse, "webhooks.0.environment.slug"), 'listed webhook environment').toBe("dev");
    expect(getValue(webhooksGetResponse, "webhooks.0.url"), 'listed webhook url').toBe("https://example.com/dev-hook");
    expect(getValue(webhooksGetResponse, "webhooks.0.secretPath"), 'listed webhook secretPath').toBe("/");
    expect(getValue(webhooksGetResponse, "webhooks.0.isDisabled"), 'listed webhook isDisabled').toBe(false);
    expect(getValue(webhooksGetResponse, "webhooks.1"), 'no second webhook').toBeUndefined();
});
