# Generated by Skyramp v1.3.40 on 2026-08-27 14:58:30.296725358 +0000 UTC m=+858.680715043
# Command: skyramp generate contract rest http://localhost:8080/api/v3/secrets/raw/MALFORMED_REF_KEY \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output cross_project_reference_malformed_syntax_left_literal_contract_test.py \
# 		--output-dir /home/runner/work/infisical/infisical/backend/e2e-test/routes \
# 		--overwrite \
# 		--provider \
# 		--request-data {"workspaceId":"SKYRAMP_SEED_PROJECT_ID","environment":"dev","secretPath":"/","secretValue":"${::dev.SOME_KEY}"} \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

# contract test for /api/v3/secrets/raw/MALFORMED_REF_KEY POST
def test_malformed_ref_key_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Setup: provision a project for this contract test to run against, since the
    # secret-creation endpoint under test has no path-nested parent to auto-provision.
    setup_project_request_body = r'''{
        "projectName": "Malformed Ref Contract Test Project",
        "slug": "cpref-malformed-syntax-test"
    }'''
    setup_project_response = client.send_request(
        url=URL,
        path="/api/v1/projects",
        method="POST",
        body=setup_project_request_body,
        headers=headers
    )
    assert setup_project_response.status_code == 200
    workspace_id = skyramp.get_response_value(setup_project_response, "project.id")

    # Request Body
    MALFORMED_REF_KEY_POST_request_body = r'''{
        "environment": "dev",
        "secretPath": "/",
        "secretValue": "${::dev.SOME_KEY}"
    }'''

    # Execute Request
    MALFORMED_REF_KEY_POST_response = client.send_request(
        url=URL,
        path="/api/v3/secrets/raw/MALFORMED_REF_KEY",
        method="POST",
        body=MALFORMED_REF_KEY_POST_request_body,
        headers=headers,
        data_override={
            "workspaceId": workspace_id
        }
    )

    # Generated Assertions
    assert MALFORMED_REF_KEY_POST_response.status_code == 200
    assert skyramp.get_response_value(MALFORMED_REF_KEY_POST_response, "secret.secretKey") == "MALFORMED_REF_KEY"
    assert skyramp.get_response_value(MALFORMED_REF_KEY_POST_response, "secret.secretValue") == "${::dev.SOME_KEY}"
    assert skyramp.get_response_value(MALFORMED_REF_KEY_POST_response, "secret.environment") == "dev"
    assert skyramp.get_response_value(MALFORMED_REF_KEY_POST_response, "secret.workspace") == workspace_id
    assert skyramp.get_response_value(MALFORMED_REF_KEY_POST_response, "secret.version") == 1
    import re
    assert re.match(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", skyramp.get_response_value(MALFORMED_REF_KEY_POST_response, "secret.id"), re.IGNORECASE)

    # Teardown
    teardown_response = client.send_request(
        url=URL,
        path="/api/v1/projects/{projectId}",
        method="DELETE",
        headers=headers,
        path_params={"projectId": workspace_id}
    )
    assert teardown_response.status_code == 200


if __name__ == "__main__":
    test_malformed_ref_key_post()
