# Generated by Skyramp v1.3.40 on 2026-08-27 14:58:05.202479546 +0000 UTC m=+833.586469221
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output cross_project_consumer_invalidation_not_wired_integration_test.py \
# 		--output-dir /home/runner/work/infisical/infisical/backend/e2e-test/routes \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/infisical/infisical/backend/e2e-test/routes/scenario_cross-project-consumer-invalidation-not-wired.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    environment = "dev"
    expandSecretReferences = "true"
    raw = "ROTATE_KEY"
    raw_1 = "CONSUMER_REF"
    secretPath = "/"

    # Request Body
    projects_POST_request_body = r'''{
        "projectName": "CrossRef Rotation Shared",
        "slug": "cpref-rotate-src"
    }'''

    # Execute Request
    projects_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects",
        method="POST",
        body=projects_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert projects_POST_response.status_code == 200
    shared_project_id = skyramp.get_response_value(projects_POST_response, "project.id")

    # Request Body
    raw_raw_POST_request_body = r'''{
        "environment": "dev",
        "secretPath": "/",
        "secretValue": "original-value-v1"
    }'''

    # Execute Request
    raw_raw_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v3/secrets/raw/{raw}",
        method="POST",
        body=raw_raw_POST_request_body,
        headers=headers,
        path_params={"raw": raw},
        data_override={
            "environment": environment,
            "secretPath": secretPath,
            "workspaceId": shared_project_id
        }
    )

    # Generated Assertions
    assert raw_raw_POST_response.status_code == 200
    assert skyramp.get_response_value(raw_raw_POST_response, "secret.secretValue") == "original-value-v1"

    # Request Body
    projects_POST_1_request_body = r'''{
        "projectName": "CrossRef Rotation Consumer",
        "slug": "cpref-rotate-dst"
    }'''

    # Execute Request
    projects_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects",
        method="POST",
        body=projects_POST_1_request_body,
        headers=headers
    )

    # Generated Assertions
    assert projects_POST_1_response.status_code == 200
    consumer_project_id = skyramp.get_response_value(projects_POST_1_response, "project.id")

    # Request Body
    raw_raw_POST_1_request_body = r'''{
        "environment": "dev",
        "secretPath": "/",
        "secretValue": "${cpref-rotate-src::dev.ROTATE_KEY}"
    }'''

    # Execute Request
    raw_raw_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/v3/secrets/raw/{raw}",
        method="POST",
        body=raw_raw_POST_1_request_body,
        headers=headers,
        path_params={"raw": raw_1},
        data_override={
            "environment": environment,
            "secretPath": secretPath,
            "workspaceId": consumer_project_id
        }
    )

    # Generated Assertions
    assert raw_raw_POST_1_response.status_code == 200
    assert skyramp.get_response_value(raw_raw_POST_1_response, "secret.secretValue") == "${cpref-rotate-src::dev.ROTATE_KEY}"

    # Execute Request
    raw_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v3/secrets/raw",
        method="GET",
        headers=headers,
        query_params={
            "environment": [environment],
            "expandSecretReferences": [expandSecretReferences],
            "secretPath": [secretPath],
            "workspaceId": [consumer_project_id]
        }
    )

    # Generated Assertions
    assert raw_GET_response.status_code == 200
    assert skyramp.get_response_value(raw_GET_response, "secrets.0.secretKey") == "CONSUMER_REF"
    assert skyramp.get_response_value(raw_GET_response, "secrets.0.secretValue") == "original-value-v1"

    # Request Body
    raw_raw_PATCH_request_body = r'''{
        "environment": "dev",
        "secretPath": "/",
        "secretValue": "rotated-value-v2"
    }'''

    # Execute Request
    raw_raw_PATCH_response = client.send_request(
        url=URL_localhost,
        path="/api/v3/secrets/raw/{raw}",
        method="PATCH",
        body=raw_raw_PATCH_request_body,
        headers=headers,
        path_params={"raw": skyramp.get_response_value(raw_raw_POST_response, "secret.secretKey")},
        data_override={
            "environment": environment,
            "secretPath": secretPath,
            "workspaceId": shared_project_id
        }
    )

    # Generated Assertions
    assert raw_raw_PATCH_response.status_code == 200
    assert skyramp.get_response_value(raw_raw_PATCH_response, "secret.secretValue") == "rotated-value-v2"

    # Execute Request
    raw_GET_1_response = client.send_request(
        url=URL_localhost,
        path="/api/v3/secrets/raw",
        method="GET",
        headers=headers,
        query_params={
            "environment": [environment],
            "expandSecretReferences": [expandSecretReferences],
            "secretPath": [secretPath],
            "workspaceId": [consumer_project_id]
        }
    )

    # Generated Assertions
    # This is the crux of the bug: invalidateSecretCacheByProjectId only bumps the
    # ROTATED (shared) project's own dal-version cache key. It never reads back
    # keyStore.hashGetAll(SecretServiceCacheKeys.getCrossProjectConsumers(sharedProjectId))
    # to also bump the CONSUMER project's dal-version, so the consumer project's
    # getSecretsOfServiceLayer cache entry (keyed by its own, unchanged, dal version)
    # is still a hit and returns the pre-rotation expanded value below.
    assert raw_GET_1_response.status_code == 200
    assert skyramp.get_response_value(raw_GET_1_response, "secrets.0.secretKey") == "CONSUMER_REF"
    assert skyramp.get_response_value(raw_GET_1_response, "secrets.0.secretValue") == "rotated-value-v2"

    # Execute Request
    projectId_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects/{projectId}",
        method="DELETE",
        headers=headers,
        path_params={"projectId": consumer_project_id}
    )

    # Generated Assertions
    assert projectId_DELETE_response.status_code == 200

    # Execute Request
    projectId_DELETE_1_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects/{projectId}",
        method="DELETE",
        headers=headers,
        path_params={"projectId": shared_project_id}
    )

    # Generated Assertions
    assert projectId_DELETE_1_response.status_code == 200


if __name__ == "__main__":
    test_integration()
