// Generated by Skyramp v1.3.38 on 2026-08-13 17:58:21.250491387 +0000 UTC m=+695.284665615
// Command: skyramp generate contract rest http://localhost:8080/api/v1/projects/{projectId}/activity-summary \
// 		--api-schema http://localhost:8080/api/docs/json \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output activity_summary_get_new_endpoint_contract.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/backend \
// 		--overwrite \
// 		--parent-request-data projectId={"projectName": "activity-summary-contract-test"} \
// 		--parent-status-code projectId=200 \
// 		--provider \
// 		--provider-output activity_summary_get_new_endpoint_contract_provider.spec.ts \
// 		--response-data {"secretsCreated":0,"secretsUpdated":0,"secretsDeleted":0} \
// 		--response-status-code 200 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, checkSchema, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");
let projectId = "projectId";

function getHeader() {
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }
    return headers;
}

test.beforeAll(async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers = getHeader();

    // Request Body
    const projectsPostRequestBody: string = `{
        "projectName": "activity-summary-contract-test"
    }`;

    // Execute Request
    const projectsPostResponse = await client.sendRequest({
        url: URL,
        path: "/api/v1/projects",
        method: "POST",
        body: projectsPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(projectsPostResponse.statusCode, 'status code').toBe(200);

    // Update global path param values
    projectId = getResponseValue(projectsPostResponse, "project.id");
});

test.afterAll(async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers = getHeader();

    // Execute Request
    const projectsProjectIdDeleteResponse = await client.sendRequest({
        url: URL,
        path: "/api/v1/projects/{projectId}",
        method: "DELETE",
        headers: headers,
        pathParams: {"projectId": projectId}
    });

    // Generated Assertions
    expect(projectsProjectIdDeleteResponse.statusCode, 'status code').toBe(200);
});

// contract test for /api/v1/projects/{projectId}/activity-summary GET
test('testActivitySummaryGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers = getHeader();

    // Expected Response Body
    const expectedActivitySummaryGetResponseBody: string = `{
        "secretsCreated": 0,
        "secretsDeleted": 0,
        "secretsUpdated": 0
    }`;

    // Execute Request
    const activitySummaryGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/v1/projects/{projectId}/activity-summary",
        method: "GET",
        headers: headers,
        pathParams: {"projectId": projectId}
    });

    // Generated Assertions
    expect(activitySummaryGetResponse.statusCode, 'status code').toBe(200);
    expect(checkSchema(activitySummaryGetResponse, expectedActivitySummaryGetResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(activitySummaryGetResponse, "secretsCreated"), 'secretsCreated').toBe(0);
    expect(getResponseValue(activitySummaryGetResponse, "secretsDeleted"), 'secretsDeleted').toBe(0);
    expect(getResponseValue(activitySummaryGetResponse, "secretsUpdated"), 'secretsUpdated').toBe(0);
});
