// Generated by Skyramp v1.3.40 on 2026-08-26 19:37:21.601789742 +0000 UTC m=+775.290292629
// Command: skyramp generate contract rest http://localhost:8080/api/v1/secrets \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output audit_log_type_response_shape_update_shared_secret_secrets_contract_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/backend \
// 		--overwrite \
// 		--provider \
// 		--query-params workspaceId=00000000-0000-4000-8000-000000000000,environment=prod \
// 		--response-status-code 404 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

// contract test for /api/v1/secrets GET
test('testSecretsGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const secretsGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/v1/secret-imports/secrets",
        method: "GET",
        headers: headers,
        queryParams: {
            "environment": "prod",
            "workspaceId": "00000000-0000-4000-8000-000000000000"
        }
    });

    // Generated Assertions
    expect(secretsGetResponse.statusCode, 'status code').toBe(404);
    expect(getValue(secretsGetResponse, "error"), 'error').toBe("NotFound");
    expect(getValue(secretsGetResponse, "message"), 'message').toBe("Project with 00000000-0000-4000-8000-000000000000 not found");
});
