// Generated by Skyramp v1.3.30 on 2026-07-06 17:57:30.452547706 +0000 UTC m=+1272.853827816
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output dotted_key_secret_reference_resolution_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/backend \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/tests/skyramp/backend/scenario_dotted_key_secret_reference_resolution.json

// Import of required libraries
import { test, expect } from '@skyramp/skyramp';

// URL for test requests
const BASE_URL = process.env.SKYRAMP_TEST_BASE_URL || "http://localhost:4000";

// NOTE: this test uses native fetch() instead of SkyrampClient.sendRequest() for
// the HTTP calls. SkyrampClient's request body is forwarded verbatim to Skyramp's
// own Go-based test runtime, which scans string values for a "${identifier.field}"
// override/chaining syntax of its own. Since this test's actual application data
// legitimately contains a literal "${dev.app\.db\.host}" secret-reference string
// (the exact feature under test), that collides with Skyramp's own template
// syntax and the runtime throws "invalid override statement: unknown field name
// app" before the request is ever sent. There is no escape hatch for this in the
// current @skyramp/skyramp client (body/path/query params all pass through the
// same parser) — using fetch() directly for these specific calls avoids it.
async function sendJson(method: string, path: string, headers: Record<string, string>, body?: unknown) {
    const res = await fetch(`${BASE_URL}${path}`, {
        method,
        headers: { "Content-Type": "application/json", ...headers },
        body: body !== undefined ? JSON.stringify(body) : undefined
    });
    const json = await res.json().catch(() => undefined);
    return { status: res.status, json };
}

test('dotted secret key reference resolves via escaped ${} syntax', async () => {
    test.setTimeout(60000);

    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Step 1: create a fresh project so this test owns all its own resources.
    const projectRes = await sendJson("POST", "/api/v1/projects", headers, {
        projectName: "testbot-dotted-ref-e7f3a1"
    });
    expect(projectRes.status, 'status code').toBe(200);
    expect(projectRes.json.project.name, 'project.name').toBe("testbot-dotted-ref-e7f3a1");
    expect(projectRes.json.project.id, 'project.id').toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    const projectId: string = projectRes.json.project.id;

    // Step 2: create a secret whose key contains a dot — this is the key that
    // previously could never be referenced (issue #5962).
    const hostSecretRes = await sendJson("POST", "/api/v3/secrets/raw/app.db.host", headers, {
        workspaceId: projectId,
        environment: "dev",
        secretPath: "/",
        secretValue: "prod-db.internal.example.com"
    });
    expect(hostSecretRes.status, 'status code').toBe(200);
    expect(hostSecretRes.json.secret.secretKey, 'secret.secretKey').toBe("app.db.host");
    expect(hostSecretRes.json.secret.secretValue, 'secret.secretValue').toBe("prod-db.internal.example.com");
    expect(hostSecretRes.json.secret.workspace, 'secret.workspace').toBe(projectId);
    expect(hostSecretRes.json.secret.environment, 'secret.environment').toBe("dev");

    // Step 3: create a second secret whose value references the dotted key,
    // escaped as app\.db\.host so the reference grammar treats it as one token.
    // This is a plain (non-template-literal) JS string, so it is exactly the
    // literal runtime value "${dev.app\.db\.host}" — one backslash per dot.
    const refValue = "${dev.app\\.db\\.host}";
    const refSecretRes = await sendJson("POST", "/api/v3/secrets/raw/db-connection-string", headers, {
        workspaceId: projectId,
        environment: "dev",
        secretPath: "/",
        secretValue: refValue
    });
    expect(refSecretRes.status, 'status code').toBe(200);
    expect(refSecretRes.json.secret.secretKey, 'secret.secretKey').toBe("db-connection-string");
    expect(refSecretRes.json.secret.secretValue, 'secret.secretValue').toBe(refValue);
    expect(refSecretRes.json.secret.workspace, 'secret.workspace').toBe(projectId);

    // Step 4: fetch the referencing secret with expandSecretReferences=true.
    const params = new URLSearchParams({
        workspaceId: projectId,
        environment: "dev",
        secretPath: "/",
        expandSecretReferences: "true"
    });
    const getRes = await sendJson("GET", `/api/v3/secrets/raw/db-connection-string?${params.toString()}`, headers);
    expect(getRes.status, 'status code').toBe(200);
    expect(getRes.json.secret.secretKey, 'secret.secretKey').toBe(refSecretRes.json.secret.secretKey);
    // Core regression assertion (issue #5962): the escaped reference to the dotted
    // key "app.db.host" must resolve to that secret's value, not the raw
    // unexpanded "${dev.app\.db\.host}" string and not an empty/undefined value.
    expect(getRes.json.secret.secretValue, 'secret.secretValue').toBe(hostSecretRes.json.secret.secretValue);
    expect(getRes.json.secret.secretValue, 'secret.secretValue').toBe("prod-db.internal.example.com");
});
