// Generated by Skyramp v1.3.40 on 2026-08-27 14:33:38.068713528 +0000 UTC m=+1041.737947878
// Command: skyramp generate contract rest http://localhost:8080/api/v1/pam/resources/ai-insights/models \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output pam_resource_ai_insights_models_contract_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/backend \
// 		--overwrite \
// 		--provider \
// 		--response-data {"models":[{"connectionApp":"string","id":"string","label":"string"}]} \
// 		--response-status-code 200 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, checkSchema, getBaseUrl, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

// contract test for /api/v1/pam/resources/ai-insights/models GET
test('testModelsGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Expected Response Body
    const expectedModelsGetResponseBody: string = `{
        "models": [
            {
                "connectionApp": "anthropic",
                "id": "claude-opus-4-6",
                "label": "Claude Opus 4.6"
            },
            {
                "connectionApp": "anthropic",
                "id": "claude-sonnet-4-6",
                "label": "Claude Sonnet 4.6"
            },
            {
                "connectionApp": "anthropic",
                "id": "claude-haiku-4-5",
                "label": "Claude Haiku 4.5"
            }
        ]
    }`;

    // Execute Request
    const modelsGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/v1/pam/resources/ai-insights/models",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(modelsGetResponse.statusCode, 'status code').toBe(200);
    expect(checkSchema(modelsGetResponse, expectedModelsGetResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(modelsGetResponse, "models").length, 'models.length').toBe(3);
    expect(getResponseValue(modelsGetResponse, "models.0.connectionApp"), 'models.0.connectionApp').toBe("anthropic");
    expect(getResponseValue(modelsGetResponse, "models.0.id"), 'models.0.id').toBe("claude-opus-4-6");
    expect(getResponseValue(modelsGetResponse, "models.0.label"), 'models.0.label').toBe("Claude Opus 4.6");
    expect(getResponseValue(modelsGetResponse, "models.1.connectionApp"), 'models.1.connectionApp').toBe("anthropic");
    expect(getResponseValue(modelsGetResponse, "models.1.id"), 'models.1.id').toBe("claude-sonnet-4-6");
    expect(getResponseValue(modelsGetResponse, "models.1.label"), 'models.1.label').toBe("Claude Sonnet 4.6");
    expect(getResponseValue(modelsGetResponse, "models.2.connectionApp"), 'models.2.connectionApp').toBe("anthropic");
    expect(getResponseValue(modelsGetResponse, "models.2.id"), 'models.2.id').toBe("claude-haiku-4-5");
    expect(getResponseValue(modelsGetResponse, "models.2.label"), 'models.2.label').toBe("Claude Haiku 4.5");
    expect(getResponseValue(modelsGetResponse, "models.3"), 'models.3').toBeUndefined();
});
