// Generated by Skyramp v1.3.40 on 2026-08-26 19:46:45.052751483 +0000 UTC m=+1338.741254360
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output public_shared_secret_ownership_bypass_patch_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/backend \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/tests/skyramp/backend/scenario_public_shared_secret_ownership_bypass_patch.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const publicPostRequestBody: string = `{
        "expiresIn": "1h",
        "secretValue": "anon-secret-value-001"
    }`;

    // Execute Request
    const publicPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/shared-secrets/public",
        method: "POST",
        body: publicPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(publicPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(publicPostResponse, "id"), 'id').not.toBeNull();

    // Declaration of variables — chained from the create response, never hardcoded
    const id = getValue(publicPostResponse, "id");

    // Request Body
    const idPatchRequestBody: string = `{
        "name": "hijacked-name"
    }`;

    // Execute Request
    const idPatchResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/shared-secrets/{id}",
        method: "PATCH",
        body: idPatchRequestBody,
        headers: headers,
        pathParams: {"id": id}
    });

    // Generated Assertions
    expect(idPatchResponse.statusCode, 'status code').toBe(403);
    // Bug-catching assertion: $validateSharedSecretOwnership only denies when a
    // sharedSecret.userId/identityId/orgId field is truthy AND mismatched, so a secret with
    // none of those set (an anonymous public share) skips every check and this PATCH is
    // silently allowed instead of forbidden.
    expect(getValue(idPatchResponse, "error"), 'error').toBe("ForbiddenError");
    expect(getValue(idPatchResponse, "message"), 'message').toBe("User does not have permission to update shared secret");
});
