// Generated by Skyramp v1.3.38 on 2026-08-19 04:12:55.635127582 +0000 UTC m=+1034.558730547
// Command: skyramp generate contract rest http://localhost:4000/api/v4/secrets/{secretName}/tags \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output secret_tag_attach_unauthenticated_401.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/backend \
// 		--overwrite \
// 		--path-params secretName=skyramp-unauth-probe \
// 		--provider \
// 		--request-data {"projectId":"00000000-0000-0000-0000-000000000000","environment":"dev","secretPath":"/","tagSlugs":["some-tag"]} \
// 		--response-status-code 401 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4000");

// contract test for /api/v4/secrets/{secretName}/tags POST
test('testTagsPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const secretName = "skyramp-unauth-probe";

    // Request Body
    const tagsPostRequestBody: string = `{
        "environment": "dev",
        "projectId": "00000000-0000-0000-0000-000000000000",
        "secretPath": "/",
        "tagSlugs": [
            "some-tag"
        ]
    }`;

    // Execute Request
    const tagsPostResponse = await client.sendRequest({
        url: URL,
        path: "/api/v4/secrets/{secretName}/tags",
        method: "POST",
        body: tagsPostRequestBody,
        headers: headers,
        pathParams: {"secretName": secretName}
    });

    // Generated Assertions
    expect(tagsPostResponse.statusCode, 'status code').toBe(401);
    expect(getValue(tagsPostResponse, "message"), 'message').toBe("Token missing");
    expect(getValue(tagsPostResponse, "error"), 'error').toBe("UnauthorizedError");
});
