// Generated by Skyramp v1.3.38 on 2026-08-19 15:34:51.798915967 +0000 UTC m=+1017.319161451
// Command: skyramp generate contract rest http://localhost:8080/api/v4/secrets/copy \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output secrets_copy_destination_folder_not_found.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/backend \
// 		--overwrite \
// 		--provider \
// 		--request-data {"projectId":"196b7b30-402b-49a1-8ad1-6c4296407302","sourceEnvironment":"dev","sourceSecretPath":"/","destinationEnvironment":"staging","destinationSecretPath":"/nonexistent-folder-xyz","secretIds":["b4e2f9d1-7a3c-4e5f-9b2d-1f6a8c3e7d92"],"shouldOverwrite":false} \
// 		--response-status-code 404 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

// contract test for /api/v4/secrets/copy POST
test('testCopyPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const copyPostRequestBody: string = `{
        "destinationEnvironment": "staging",
        "destinationSecretPath": "/nonexistent-folder-xyz",
        "projectId": "196b7b30-402b-49a1-8ad1-6c4296407302",
        "secretIds": [
            "b4e2f9d1-7a3c-4e5f-9b2d-1f6a8c3e7d92"
        ],
        "shouldOverwrite": false,
        "sourceEnvironment": "dev",
        "sourceSecretPath": "/"
    }`;

    // Execute Request
    const copyPostResponse = await client.sendRequest({
        url: URL,
        path: "/api/v4/secrets/copy",
        method: "POST",
        body: copyPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(copyPostResponse.statusCode, 'status code').toBe(404);
    expect(getValue(copyPostResponse, "message"), 'message').toBe("Destination folder with path '/nonexistent-folder-xyz' in environment with slug 'staging' not found");
    expect(getValue(copyPostResponse, "error"), 'error').toBe("NotFound");
});
