// Generated by Skyramp v1.3.38 on 2026-08-19 04:29:31.79660426 +0000 UTC m=+2030.720207220
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_list_tag_filter_any_match_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/backend \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/tests/skyramp/backend/scenario_secret_list_tag_filter_any_match.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue, uniqueSuffix } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4000");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }
    // Declaration of variables
    const api = "v2";
    const api_1 = "v1";
    const api_2 = "v1";
    const secrets = "sec1";
    const secrets_1 = "sec2";
    const secrets_2 = "sec3";
    const secrets_3 = "sec2";
    const secrets_4 = "sec3";

    // Request Body
    const workspacePostRequestBody: string = `{
        "projectName": "skyramp-tagfilter-proj"
    }`;

    // Execute Request
    const workspacePostResponse = await client.sendRequest({
        url: URL_localhost,
            headers: headers,
        path: "/api/{api}/workspace",
        method: "POST",
        body: workspacePostRequestBody,
        pathParams: {"api": api},
        dataOverride: {"projectName": uniqueSuffix("skyramp-tagfilter-proj")}
    });

    // Generated Assertions
    expect(workspacePostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(workspacePostResponse, "project.id"), 'project.id').toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getResponseValue(workspacePostResponse, "project.slug"), 'project.slug').toMatch(/^skyramp-tagfilter-proj/);
    expect(getResponseValue(workspacePostResponse, "project.environments.0.slug"), 'project.environments.0.slug').toBe("dev");
    const projectId = getResponseValue(workspacePostResponse, "project.id");

    // Request Body
    const workspaceTagsPostRequestBody: string = `{
        "color": "#ff0000",
        "slug": "tag-a"
    }`;

    // Execute Request
    const workspaceTagsPostResponse = await client.sendRequest({
        url: URL_localhost,
            headers: headers,
        path: "/api/{api}/workspace/{workspace}/tags",
        method: "POST",
        body: workspaceTagsPostRequestBody,
        pathParams: {
            "api": api_1,
            "workspace": getResponseValue(workspacePostResponse, "project.id")
        },
        dataOverride: {"slug": uniqueSuffix("tag-a")}
    });

    // Generated Assertions
    expect(workspaceTagsPostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(workspaceTagsPostResponse, "workspaceTag.slug"), 'workspaceTag.slug').toMatch(/^tag-a/);
    expect(getResponseValue(workspaceTagsPostResponse, "workspaceTag.color"), 'workspaceTag.color').toBe("#ff0000");
    expect(getResponseValue(workspaceTagsPostResponse, "workspaceTag.projectId"), 'workspaceTag.projectId').toBe(getResponseValue(workspacePostResponse, "project.id"));

    // Request Body
    const workspaceTagsPost1RequestBody: string = `{
        "color": "#00ff00",
        "slug": "tag-b"
    }`;

    // Execute Request
    const workspaceTagsPost1Response = await client.sendRequest({
        url: URL_localhost,
            headers: headers,
        path: "/api/{api}/workspace/{workspace}/tags",
        method: "POST",
        body: workspaceTagsPost1RequestBody,
        pathParams: {
            "api": api_2,
            "workspace": getResponseValue(workspacePostResponse, "project.id")
        },
        dataOverride: {"slug": uniqueSuffix("tag-b")}
    });

    // Generated Assertions
    expect(workspaceTagsPost1Response.statusCode, 'status code').toBe(200);
    expect(getResponseValue(workspaceTagsPost1Response, "workspaceTag.slug"), 'workspaceTag.slug').toMatch(/^tag-b/);
    expect(getResponseValue(workspaceTagsPost1Response, "workspaceTag.color"), 'workspaceTag.color').toBe("#00ff00");

    // Request Body
    const secretsPostRequestBody: string = `{
        "environment": "dev",
        "projectId": "chained-project-id",
        "secretKey": "sec1",
        "secretPath": "/",
        "secretValue": "v1"
    }`;

    // Request Body
    const secretsPost1RequestBody: string = `{
        "environment": "dev",
        "projectId": "chained-project-id",
        "secretKey": "sec2",
        "secretPath": "/",
        "secretValue": "v2"
    }`;

    // Request Body
    const secretsPost2RequestBody: string = `{
        "environment": "dev",
        "projectId": "chained-project-id",
        "secretKey": "sec3",
        "secretPath": "/",
        "secretValue": "v3"
    }`;

    const [secretsPostResponse, secretsPost1Response, secretsPost2Response] = await Promise.all([
        client.sendRequest({
            url: URL_localhost,
            headers: headers,
            path: "/api/v4/secrets/{secrets}",
            method: "POST",
            body: secretsPostRequestBody,
            pathParams: {"secrets": secrets},
            dataOverride: {
                "projectId": projectId,
                "secretKey": secrets
            }
        }),
        client.sendRequest({
            url: URL_localhost,
            headers: headers,
            path: "/api/v4/secrets/{secrets}",
            method: "POST",
            body: secretsPost1RequestBody,
            pathParams: {"secrets": secrets_1},
            dataOverride: {
                "projectId": projectId,
                "secretKey": secrets_1
            }
        }),
        client.sendRequest({
            url: URL_localhost,
            headers: headers,
            path: "/api/v4/secrets/{secrets}",
            method: "POST",
            body: secretsPost2RequestBody,
            pathParams: {"secrets": secrets_2},
            dataOverride: {
                "projectId": projectId,
                "secretKey": secrets_2
            }
        }),
    ]);;

    // Generated Assertions
    expect(secretsPostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(secretsPostResponse, "secret.secretKey"), 'secret.secretKey').toBe("sec1");
    expect(getResponseValue(secretsPostResponse, "secret.workspace"), 'secret.workspace').toBe(getResponseValue(workspacePostResponse, "project.id"));
    // Generated Assertions
    expect(secretsPost1Response.statusCode, 'status code').toBe(200);
    expect(getResponseValue(secretsPost1Response, "secret.secretKey"), 'secret.secretKey').toBe("sec2");
    // Generated Assertions
    expect(secretsPost2Response.statusCode, 'status code').toBe(200);
    expect(getResponseValue(secretsPost2Response, "secret.secretKey"), 'secret.secretKey').toBe("sec3");

    // Request Body
    const tagsPostRequestBody: string = `{
        "environment": "dev",
        "projectId": "chained-project-id",
        "secretPath": "/",
        "tagSlugs": [
            "tag-a"
        ]
    }`;

    // Execute Request
    const tagsPostResponse = await client.sendRequest({
        url: URL_localhost,
            headers: headers,
        path: "/api/v4/secrets/{secrets}/tags",
        method: "POST",
        body: tagsPostRequestBody,
        pathParams: {"secrets": secrets},
        dataOverride: {"projectId": projectId, "tagSlugs": [getResponseValue(workspaceTagsPostResponse, "workspaceTag.slug")]}
    });

    // Generated Assertions
    expect(tagsPostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(tagsPostResponse, "secretName"), 'secretName').toBe("sec1");
    expect(getResponseValue(tagsPostResponse, "tags.0.id"), 'tags.0.id').toBe(getResponseValue(workspaceTagsPostResponse, "workspaceTag.id"));
    expect(getResponseValue(tagsPostResponse, "tags.1"), 'tags.1').toBeNull();

    // Request Body
    const tagsPost1RequestBody: string = `{
        "environment": "dev",
        "projectId": "chained-project-id",
        "secretPath": "/",
        "tagSlugs": [
            "tag-b"
        ]
    }`;

    // Execute Request
    const tagsPost1Response = await client.sendRequest({
        url: URL_localhost,
            headers: headers,
        path: "/api/v4/secrets/{secrets}/tags",
        method: "POST",
        body: tagsPost1RequestBody,
        pathParams: {"secrets": secrets_3},
        dataOverride: {"projectId": projectId, "tagSlugs": [getResponseValue(workspaceTagsPost1Response, "workspaceTag.slug")]}
    });

    // Generated Assertions
    expect(tagsPost1Response.statusCode, 'status code').toBe(200);
    expect(getResponseValue(tagsPost1Response, "secretName"), 'secretName').toBe("sec2");
    expect(getResponseValue(tagsPost1Response, "tags.0.id"), 'tags.0.id').toBe(getResponseValue(workspaceTagsPost1Response, "workspaceTag.id"));

    // Execute Request
    const endpoint1GetResponse = await client.sendRequest({
        url: URL_localhost,
            headers: headers,
        path: "/api/v4/secrets/",
        method: "GET",
        queryParams: {
            "environment": ["dev"],
            "projectId": [projectId],
            "secretPath": ["/"],
            "tagSlugs": [`${getResponseValue(workspaceTagsPostResponse, "workspaceTag.slug")},${getResponseValue(workspaceTagsPost1Response, "workspaceTag.slug")}`]
        }
    });

    // Generated Assertions
    expect(endpoint1GetResponse.statusCode, 'status code').toBe(200);
    // Business rule under test: a secret matches when it carries ANY of the requested tagSlugs
    // (tag-a OR tag-b) — sec1 (tag-a only) and sec2 (tag-b only) must both be returned, sec3 (untagged) must not.
    // getResponseValue only resolves scalar leaves (arrays/objects return null), so the array is
    // read directly off the raw response body instead.
    const endpoint1GetBody = JSON.parse(endpoint1GetResponse.responseBody);
    const anyMatchSecretKeys = (endpoint1GetBody.secrets ?? [])
        .map((s: { secretKey: string }) => s.secretKey)
        .sort();
    expect(anyMatchSecretKeys, 'secrets matched by tagSlugs=tag-a,tag-b (any-of semantics)').toEqual(["sec1", "sec2"]);

    // Request Body
    const secretsDeleteRequestBody: string = `{
        "environment": "dev",
        "projectId": "chained-project-id",
        "secretPath": "/"
    }`;

    // Request Body
    const secretsDelete1RequestBody: string = `{
        "environment": "dev",
        "projectId": "chained-project-id",
        "secretPath": "/"
    }`;

    // Request Body
    const secretsDelete2RequestBody: string = `{
        "environment": "dev",
        "projectId": "chained-project-id",
        "secretPath": "/"
    }`;

    const [secretsDeleteResponse, secretsDelete1Response, secretsDelete2Response] = await Promise.all([
        client.sendRequest({
            url: URL_localhost,
            headers: headers,
            path: "/api/v4/secrets/{secrets}",
            method: "DELETE",
            body: secretsDeleteRequestBody,
            pathParams: {"secrets": secrets},
            dataOverride: {"projectId": projectId}
        }),
        client.sendRequest({
            url: URL_localhost,
            headers: headers,
            path: "/api/v4/secrets/{secrets}",
            method: "DELETE",
            body: secretsDelete1RequestBody,
            pathParams: {"secrets": secrets_1},
            dataOverride: {"projectId": projectId}
        }),
        client.sendRequest({
            url: URL_localhost,
            headers: headers,
            path: "/api/v4/secrets/{secrets}",
            method: "DELETE",
            body: secretsDelete2RequestBody,
            pathParams: {"secrets": secrets_4},
            dataOverride: {"projectId": projectId}
        }),
    ]);;

    // Generated Assertions
    expect(secretsDeleteResponse.statusCode, 'status code').toBe(200);
    // Generated Assertions
    expect(secretsDelete1Response.statusCode, 'status code').toBe(200);
    // Generated Assertions
    expect(secretsDelete2Response.statusCode, 'status code').toBe(200);

    // Execute Request
    const workspaceWorkspaceDeleteResponse = await client.sendRequest({
        url: URL_localhost,
            headers: headers,
        path: "/api/{api}/workspace/{workspace}",
        method: "DELETE",
        pathParams: {
            "api": api,
            "workspace": getResponseValue(workspacePostResponse, "project.slug")
        }
    });

    // Generated Assertions
    expect(workspaceWorkspaceDeleteResponse.statusCode, 'status code').toBe(200);
});
