// Generated by Skyramp v1.3.40 on 2026-08-27 14:33:23.406292911 +0000 UTC m=+1027.075527251
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_share_view_limit_exhaustion_access_log_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/backend \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/tests/skyramp/backend/scenario_secret_share_view_limit_exhaustion_access_log.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, uniqueSuffix } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const sharedSecretName = uniqueSuffix("view-limit-secret");
    const sharedSecretsPostRequestBody: string = `{
        "accessType": "organization",
        "expiresIn": "1h",
        "maxViews": 1,
        "name": "view-limit-secret",
        "secretValue": "sk-view-limit-test-value"
    }`;

    // Execute Request
    const sharedSecretsPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/shared-secrets",
        method: "POST",
        body: sharedSecretsPostRequestBody,
        headers: headers,
        dataOverride: {"name": sharedSecretName}
    });

    // Generated Assertions
    expect(sharedSecretsPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(sharedSecretsPostResponse, "name"), 'name').toBe(sharedSecretName);
    expect(getValue(sharedSecretsPostResponse, "accessType"), 'accessType').toBe("organization");
    expect(getValue(sharedSecretsPostResponse, "expiresAfterViews"), 'expiresAfterViews').toBe(1);
    expect(getValue(sharedSecretsPostResponse, "notifyOnAccess"), 'notifyOnAccess').toBe(false);
    expect(getValue(sharedSecretsPostResponse, "expiresAt"), 'expiresAt').toMatch(/^\d{4}-\d{2}-\d{2}T/);
    expect(getValue(sharedSecretsPostResponse, "sharedSecretLink"), 'sharedSecretLink').toContain(getValue(sharedSecretsPostResponse, "id"));

    // Chained value: the shared secret's public identifier, used by every subsequent step
    const id = getValue(sharedSecretsPostResponse, "id");

    // Request Body
    const accessPostRequestBody: string = `{}`;

    // Execute Request
    const accessPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/shared-secrets/{id}/access",
        method: "POST",
        body: accessPostRequestBody,
        headers: headers,
        pathParams: {"id": id}
    });

    // Generated Assertions
    expect(accessPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(accessPostResponse, "id"), 'id').toBe(id);
    expect(getValue(accessPostResponse, "secretValue"), 'secretValue').toBe("sk-view-limit-test-value");
    expect(getValue(accessPostResponse, "accessType"), 'accessType').toBe("organization");

    // Request Body
    const accessPost1RequestBody: string = `{}`;

    // Execute Request
    const accessPost1Response = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/shared-secrets/{id}/access",
        method: "POST",
        body: accessPost1RequestBody,
        headers: headers,
        pathParams: {"id": id}
    });

    // Generated Assertions
    expect(accessPost1Response.statusCode, 'status code').toBe(404);
    expect(getValue(accessPost1Response, "message"), 'message').toBe("The shared secret has reached its view limit");
    expect(getValue(accessPost1Response, "error"), 'error').toBe("NotFound");

    // Execute Request
    const accessLogsGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/shared-secrets/{id}/access-logs",
        method: "GET",
        headers: headers,
        pathParams: {"id": id}
    });

    // Generated Assertions
    expect(accessLogsGetResponse.statusCode, 'status code').toBe(200);
    // Both the successful first access and the view-limit-exceeded second access must be recorded
    expect(getValue(accessLogsGetResponse, "totalCount"), 'totalCount').toBe(2);
    expect(getValue(accessLogsGetResponse, "accessLogs.2"), 'accessLogs.2').toBeNull();
    // Ordered newest-first: the failed second attempt appears before the successful first attempt
    expect(getValue(accessLogsGetResponse, "accessLogs.0.success"), 'accessLogs.0.success').toBe(false);
    expect(getValue(accessLogsGetResponse, "accessLogs.0.failureReason"), 'accessLogs.0.failureReason').toBe("The shared secret has reached its view limit");
    expect(getValue(accessLogsGetResponse, "accessLogs.1.success"), 'accessLogs.1.success').toBe(true);
    expect(getValue(accessLogsGetResponse, "accessLogs.1.failureReason"), 'accessLogs.1.failureReason').toBeNull();
});
