// Generated by Skyramp v1.3.40 on 2026-08-26 19:37:14.479047877 +0000 UTC m=+768.167550754
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output shared_secret_patch_password_rotation_not_persisted_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/backend \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/tests/skyramp/backend/scenario_shared_secret_patch_password_rotation_not_persisted.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const sharedSecretsPostRequestBody: string = `{
        "expiresIn": "1h",
        "secretValue": "rotation-test-value-001"
    }`;

    // Execute Request
    const sharedSecretsPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/shared-secrets",
        method: "POST",
        body: sharedSecretsPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(sharedSecretsPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(sharedSecretsPostResponse, "id"), 'id').not.toBeNull();
    expect(getValue(sharedSecretsPostResponse, "expiresAt"), 'expiresAt').toMatch(/^\d{4}-\d{2}-\d{2}T/);
    expect(getValue(sharedSecretsPostResponse, "accessType"), 'accessType').toBe("organization");

    // Declaration of variables — chained from the create response, never hardcoded
    const id = getValue(sharedSecretsPostResponse, "id");

    // Request Body
    const idPatchRequestBody: string = `{
        "password": "NewPassw0rd!23"
    }`;

    // Execute Request
    const idPatchResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/shared-secrets/{id}",
        method: "PATCH",
        body: idPatchRequestBody,
        headers: headers,
        pathParams: {"id": id}
    });

    // Generated Assertions
    expect(idPatchResponse.statusCode, 'status code').toBe(200);
    expect(getValue(idPatchResponse, "id"), 'id').toBe(id);

    // Execute Request
    const idGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/shared-secrets/{id}",
        method: "GET",
        headers: headers,
        pathParams: {"id": id}
    });

    // Generated Assertions
    expect(idGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(idGetResponse, "id"), 'id').toBe(id);
    // Bug-catching assertion: updateSharedSecretById computes hashedPassword but never
    // assigns it to updatePayload.password, so the PATCH above should have rotated the
    // secret into a password-protected state but silently did not.
    expect(getValue(idGetResponse, "isPasswordProtected"), 'isPasswordProtected').toBe(true);

    // Execute Request
    const idDeleteResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/shared-secrets/{id}",
        method: "DELETE",
        headers: headers,
        pathParams: {"id": id}
    });

    // Generated Assertions
    expect(idDeleteResponse.statusCode, 'status code').toBe(204);
});
