// Generated by Skyramp v1.3.30 on 2026-07-06 18:04:05.504611862 +0000 UTC m=+1667.905891973
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output unescaped_dotted_reference_stays_unresolved_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/backend \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/tests/skyramp/backend/scenario_unescaped_dotted_reference_stays_unresolved.json

// Import of required libraries
import { test, expect } from '@skyramp/skyramp';

// URL for test requests
const BASE_URL = process.env.SKYRAMP_TEST_BASE_URL || "http://localhost:4000";

// NOTE: uses native fetch() instead of SkyrampClient.sendRequest() — see the
// sibling test dotted_key_secret_reference_resolution_integration_test.spec.ts
// for why (SkyrampClient's Go runtime misparses a literal "${...}" reference
// string in the request body as its own step-chaining override syntax).
async function sendJson(method: string, path: string, headers: Record<string, string>, body?: unknown) {
    const res = await fetch(`${BASE_URL}${path}`, {
        method,
        headers: { "Content-Type": "application/json", ...headers },
        body: body !== undefined ? JSON.stringify(body) : undefined
    });
    const json = await res.json().catch(() => undefined);
    return { status: res.status, json };
}

test('an unescaped dotted-key reference does not resolve (backward-compat guard)', async () => {
    test.setTimeout(60000);

    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Step 1: create a fresh project so this test owns all its own resources.
    const projectRes = await sendJson("POST", "/api/v1/projects", headers, {
        projectName: "testbot-unescaped-ref-b2c9"
    });
    expect(projectRes.status, 'status code').toBe(200);
    expect(projectRes.json.project.name, 'project.name').toBe("testbot-unescaped-ref-b2c9");
    expect(projectRes.json.project.id, 'project.id').toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    const projectId: string = projectRes.json.project.id;

    // Step 2: create a secret whose key contains a dot.
    const hostSecretRes = await sendJson("POST", "/api/v3/secrets/raw/app.db.host", headers, {
        workspaceId: projectId,
        environment: "dev",
        secretPath: "/",
        secretValue: "prod-db.internal.example.com"
    });
    expect(hostSecretRes.status, 'status code').toBe(200);
    expect(hostSecretRes.json.secret.secretKey, 'secret.secretKey').toBe("app.db.host");
    expect(hostSecretRes.json.secret.secretValue, 'secret.secretValue').toBe("prod-db.internal.example.com");
    expect(hostSecretRes.json.secret.workspace, 'secret.workspace').toBe(projectId);

    // Step 3: create a second secret whose value references the dotted key
    // WITHOUT escaping the dots — "${dev.app.db.host}" — exactly the pattern
    // that historically failed (issue #5962). This is a plain JS string, so
    // its runtime value is the literal, unescaped reference text.
    const unescapedRefValue = "${dev.app.db.host}";
    const refSecretRes = await sendJson("POST", "/api/v3/secrets/raw/db-connection-string-unescaped", headers, {
        workspaceId: projectId,
        environment: "dev",
        secretPath: "/",
        secretValue: unescapedRefValue
    });
    expect(refSecretRes.status, 'status code').toBe(200);
    expect(refSecretRes.json.secret.secretKey, 'secret.secretKey').toBe("db-connection-string-unescaped");
    expect(refSecretRes.json.secret.secretValue, 'secret.secretValue').toBe(unescapedRefValue);
    expect(refSecretRes.json.secret.workspace, 'secret.workspace').toBe(projectId);

    // Step 4: fetch the referencing secret with expandSecretReferences=true.
    const params = new URLSearchParams({
        workspaceId: projectId,
        environment: "dev",
        secretPath: "/",
        expandSecretReferences: "true"
    });
    const getRes = await sendJson("GET", `/api/v3/secrets/raw/db-connection-string-unescaped?${params.toString()}`, headers);
    expect(getRes.status, 'status code').toBe(200);
    expect(getRes.json.secret.secretKey, 'secret.secretKey').toBe(refSecretRes.json.secret.secretKey);
    // Backward-compat guard: an unescaped "${dev.app.db.host}" is still parsed
    // as environment=dev, path=/app/db, key=host — a path that does not exist —
    // so expansion silently no-ops and the API returns the literal, unexpanded
    // reference text, NOT the app.db.host secret's value. This proves the fix
    // is additive (escaping is required to opt in) rather than accidentally
    // resolving every dotted-key reference regardless of escaping.
    expect(getRes.json.secret.secretValue, 'secret.secretValue').toBe(unescapedRefValue);
    expect(getRes.json.secret.secretValue, 'secret.secretValue').not.toBe(hostSecretRes.json.secret.secretValue);
});
