// Generated by Skyramp v1.3.40 on 2026-08-27 15:23:58.312637547 +0000 UTC m=+573.181656517
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output activity_summary_create_then_update_counts_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/backend/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/backend/tests/scenario_activity_summary_create_then_update_counts.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const raw = "ACTIVITY_PROBE";
    const workspace = "3f8e1c2a-9b47-4d16-8a5e-71c0d94b6f32";

    // Request Body
    const projectsPostRequestBody: string = `{
        "projectName": "skyramp-activity-summary",
        "type": "secret-manager"
    }`;

    // Execute Request
    const projectsPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/projects",
        method: "POST",
        body: projectsPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(projectsPostResponse.statusCode, 'status code').toBe(200);

    // Request Body
    const rawPostRequestBody: string = `{
        "environment": "dev",
        "secretPath": "/",
        "secretValue": "initial",
        "type": "shared",
        "workspaceId": "3f8e1c2a-9b47-4d16-8a5e-71c0d94b6f32"
    }`;

    // Execute Request
    const rawPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v3/secrets/raw/{raw}",
        method: "POST",
        body: rawPostRequestBody,
        headers: headers,
        pathParams: {"raw": raw},
        dataOverride: {"workspaceId": workspace}
    });

    // Generated Assertions
    expect(rawPostResponse.statusCode, 'status code').toBe(200);

    // Request Body
    const rawPatchRequestBody: string = `{
        "environment": "dev",
        "secretPath": "/",
        "secretValue": "rotated",
        "type": "shared",
        "workspaceId": "3f8e1c2a-9b47-4d16-8a5e-71c0d94b6f32"
    }`;

    // Execute Request
    const rawPatchResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v3/secrets/raw/{raw}",
        method: "PATCH",
        body: rawPatchRequestBody,
        headers: headers,
        pathParams: {"raw": getResponseValue(rawPostResponse, "secret.secretKey")},
        dataOverride: {"workspaceId": workspace}
    });

    // Generated Assertions
    expect(rawPatchResponse.statusCode, 'status code').toBe(200);

    // Execute Request
    const activitySummaryGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/projects/{projects}/activity-summary",
        method: "GET",
        headers: headers,
        pathParams: {"projects": getResponseValue(projectsPostResponse, "project.id")}
    });

    // Generated Assertions
    expect(activitySummaryGetResponse.statusCode, 'status code').toBe(200);

    // Execute Request
    const workspaceDeleteResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/workspace/{workspace}",
        method: "DELETE",
        headers: headers,
        pathParams: {"workspace": getResponseValue(projectsPostResponse, "project.id")}
    });

    // Generated Assertions
    expect(workspaceDeleteResponse.statusCode, 'status code').toBe(200);
});
