// Generated by Skyramp v1.3.40 on 2026-08-27 14:46:14.398483733 +0000 UTC m=+1138.861873161
// Command: skyramp generate contract rest http://localhost:8080/api/v3/secrets/move \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output-dir /home/runner/work/infisical/infisical/backend/tests \
// 		--overwrite \
// 		--provider \
// 		--provider-output contract_secrets_move_v3_provider.spec.ts \
// 		--request-data {"projectSlug":"skyramp-nonexistent-project","sourceEnvironment":"dev","sourceSecretPath":"/","destinationEnvironment":"staging","destinationSecretPath":"/","secretIds":["00000000-0000-4000-8000-000000000000"],"shouldOverwrite":false} \
// 		--response-data {"statusCode":404,"message":"Project with slug 'skyramp-nonexistent-project' not found","error":"NotFound"} \
// 		--response-status-code 404 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect, SkyrampClient, checkSchema, getBaseUrl, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

// contract test for /api/v3/secrets/move POST
test('testMovePost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const movePostRequestBody: string = `{
        "destinationEnvironment": "staging",
        "destinationSecretPath": "/",
        "projectSlug": "skyramp-nonexistent-project",
        "secretIds": [
            "00000000-0000-4000-8000-000000000000"
        ],
        "shouldOverwrite": false,
        "sourceEnvironment": "dev",
        "sourceSecretPath": "/"
    }`;

    // Expected Response Body
    const expectedMovePostResponseBody: string = `{
        "error": "NotFound",
        "message": "Project with slug 'skyramp-nonexistent-project' not found",
        "statusCode": 404
    }`;

    // Execute Request
    const movePostResponse = await client.sendRequest({
        url: URL,
        path: "/api/v3/secrets/move",
        method: "POST",
        body: movePostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(movePostResponse.statusCode, 'status code').toBe(404);
    expect(checkSchema(movePostResponse, expectedMovePostResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(movePostResponse, "error"), 'error').toBe("NotFound");
    expect(getResponseValue(movePostResponse, "message"), 'message').toBe("Project with slug 'skyramp-nonexistent-project' not found");
    expect(getResponseValue(movePostResponse, "statusCode"), 'statusCode').toBe(404);
    expect(getResponseValue(movePostResponse, "isSourceUpdated"), 'isSourceUpdated').toBeNull();
    expect(getResponseValue(movePostResponse, "isDestinationUpdated"), 'isDestinationUpdated').toBeNull();
    expect(getResponseValue(movePostResponse, "movedOverridesCount"), 'movedOverridesCount').toBeNull();
});
