// Generated by Skyramp v1.3.40 on 2026-08-27 15:02:32.118216587 +0000 UTC m=+973.431129464
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output cross_project_reference_nested_expansion_same_coordinates_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/backend/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/backend/tests/scenario_cross_project_reference_nested_expansion_same_coordinates.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const secrets = "LEAF";
    const secrets_1 = "API_KEY";
    const viewSecretValue = "true";

    // Request Body
    const projectsPostRequestBody: string = `{
        "projectName": "skyramp-nest-src",
        "slug": "skyramp-nest-src",
        "type": "secret-manager"
    }`;

    // Execute Request
    const projectsPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/projects",
        method: "POST",
        body: projectsPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(projectsPostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(projectsPostResponse, "project.id"), 'source project id').toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getResponseValue(projectsPostResponse, "project.slug"), 'source project slug').toBe("skyramp-nest-src");
    expect(getResponseValue(projectsPostResponse, "project.type"), 'source project type').toBe("secret-manager");

    // Request Body
    const projectsPost1RequestBody: string = `{
        "projectName": "skyramp-nest-consumer",
        "slug": "skyramp-nest-consumer",
        "type": "secret-manager"
    }`;

    // Execute Request
    const projectsPost1Response = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/projects",
        method: "POST",
        body: projectsPost1RequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(projectsPost1Response.statusCode, 'status code').toBe(200);
    expect(getResponseValue(projectsPost1Response, "project.id"), 'consumer project id').toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getResponseValue(projectsPost1Response, "project.slug"), 'consumer project slug').toBe("skyramp-nest-consumer");
    expect(getResponseValue(projectsPost1Response, "project.type"), 'consumer project type').toBe("secret-manager");

    // Request Body
    const secretsSecretsPostRequestBody: string = `{
        "environment": "dev",
        "projectId": "3c9f2a81-4d6b-4e57-9a03-15e8bc27f4a6",
        "secretPath": "/",
        "secretValue": "leaf-value"
    }`;

    // Execute Request
    const secretsSecretsPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets/{secrets}",
        method: "POST",
        body: secretsSecretsPostRequestBody,
        headers: headers,
        pathParams: {"secrets": secrets},
        dataOverride: {"projectId": getResponseValue(projectsPostResponse, "project.id")}
    });

    // Generated Assertions
    expect(secretsSecretsPostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(secretsSecretsPostResponse, "secret.secretKey"), 'leaf key').toBe("LEAF");
    expect(getResponseValue(secretsSecretsPostResponse, "secret.secretValue"), 'leaf value').toBe("leaf-value");

    // Request Body
    const secretsSecretsPost1RequestBody: string = `{
        "environment": "dev",
        "projectId": "3c9f2a81-4d6b-4e57-9a03-15e8bc27f4a6",
        "secretPath": "/",
        "secretValue": "\${LEAF}"
    }`;

    // Execute Request
    const secretsSecretsPost1Response = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets/{secrets}",
        method: "POST",
        body: secretsSecretsPost1RequestBody,
        headers: headers,
        pathParams: {"secrets": secrets_1},
        dataOverride: {"projectId": getResponseValue(projectsPostResponse, "project.id")}
    });

    // Generated Assertions
    expect(secretsSecretsPost1Response.statusCode, 'status code').toBe(200);
    expect(getResponseValue(secretsSecretsPost1Response, "secret.secretKey"), 'source API_KEY key').toBe("API_KEY");
    expect(getResponseValue(secretsSecretsPost1Response, "secret.secretValue"), 'source API_KEY holds a nested reference').toBe("\${LEAF}");

    // Request Body
    const secretsSecretsPost2RequestBody: string = `{
        "environment": "dev",
        "projectId": "6e1b48d3-9f27-4c85-b0d4-38a5c7e29b17",
        "secretPath": "/",
        "secretValue": "\${skyramp-nest-src::dev.API_KEY}"
    }`;

    // Execute Request
    const secretsSecretsPost2Response = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets/{secrets}",
        method: "POST",
        body: secretsSecretsPost2RequestBody,
        headers: headers,
        pathParams: {"secrets": getResponseValue(secretsSecretsPost1Response, "secret.secretKey")},
        dataOverride: {"projectId": getResponseValue(projectsPost1Response, "project.id")}
    });

    // Generated Assertions
    expect(secretsSecretsPost2Response.statusCode, 'status code').toBe(200);
    expect(getResponseValue(secretsSecretsPost2Response, "secret.secretKey"), 'consumer API_KEY key').toBe("API_KEY");
    expect(getResponseValue(secretsSecretsPost2Response, "secret.secretValue"), 'consumer API_KEY stored unexpanded').toBe("\${skyramp-nest-src::dev.API_KEY}");

    // Execute Request
    const secretsGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets",
        method: "GET",
        headers: headers,
        queryParams: {
            "environment": ["dev"],
            "expandSecretReferences": [viewSecretValue],
            "includeImports": ["false"],
            "projectId": [getResponseValue(projectsPost1Response, "project.id")],
            "secretPath": ["/"],
            "viewSecretValue": [viewSecretValue]
        }
    });

    // Generated Assertions
    expect(secretsGetResponse.statusCode, 'status code').toBe(200);
    // Read the returned pairs by index so the assertions do not depend on list ordering.
    const expandedSecrets: Record<string, string> = {};
    for (let i = 0; i < 3; i += 1) {
        const secretKey = getResponseValue(secretsGetResponse, `secrets.${i}.secretKey`) as string | null;
        if (!secretKey) break;
        expandedSecrets[secretKey] = getResponseValue(secretsGetResponse, `secrets.${i}.secretValue`) as string;
    }
    expect(Object.keys(expandedSecrets), 'consumer dev:/ secret keys').toEqual(["API_KEY"]);
    expect(expandedSecrets.API_KEY, 'nested cross-project reference must fully expand to the leaf value').toBe("leaf-value");

    // Execute Request
    const projectsProjectsDeleteResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/projects/{projects}",
        method: "DELETE",
        headers: headers,
        pathParams: {"projects": getResponseValue(projectsPostResponse, "project.id")}
    });

    // Generated Assertions
    expect(projectsProjectsDeleteResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(projectsProjectsDeleteResponse, "project.slug"), 'deleted source project').toBe("skyramp-nest-src");

    // Execute Request
    const projectsProjectsDelete1Response = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/projects/{projects}",
        method: "DELETE",
        headers: headers,
        pathParams: {"projects": getResponseValue(projectsPost1Response, "project.id")}
    });

    // Generated Assertions
    expect(projectsProjectsDelete1Response.statusCode, 'status code').toBe(200);
    expect(getResponseValue(projectsProjectsDelete1Response, "project.slug"), 'deleted consumer project').toBe("skyramp-nest-consumer");
});
