// Generated by Skyramp v1.3.40 on 2026-08-27 15:13:10.621689021 +0000 UTC m=+1611.934601898
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output cross_project_reference_resolves_source_project_value_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/backend/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/backend/tests/scenario_cross_project_reference_resolves_source_project_value.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const expandSecretReferences = "true";
    const secrets = "SHARED_KEY";
    const secrets_1 = "LOCAL_REF";
    const secrets_2 = "CROSS_REF";

    // Request Body
    const projectsPostRequestBody: string = `{
        "projectName": "skyramp-xproj-src",
        "slug": "skyramp-xproj-src",
        "type": "secret-manager"
    }`;

    // Execute Request
    const projectsPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/projects",
        method: "POST",
        body: projectsPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(projectsPostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(projectsPostResponse, "project.id"), 'source project id').toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getResponseValue(projectsPostResponse, "project.name"), 'source project name').toBe("skyramp-xproj-src");
    expect(getResponseValue(projectsPostResponse, "project.slug"), 'source project slug').toBe("skyramp-xproj-src");
    expect(getResponseValue(projectsPostResponse, "project.type"), 'source project type').toBe("secret-manager");

    // Request Body
    const projectsPost1RequestBody: string = `{
        "projectName": "skyramp-xproj-consumer",
        "slug": "skyramp-xproj-consumer",
        "type": "secret-manager"
    }`;

    // Execute Request
    const projectsPost1Response = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/projects",
        method: "POST",
        body: projectsPost1RequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(projectsPost1Response.statusCode, 'status code').toBe(200);
    expect(getResponseValue(projectsPost1Response, "project.id"), 'consumer project id').toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getResponseValue(projectsPost1Response, "project.name"), 'consumer project name').toBe("skyramp-xproj-consumer");
    expect(getResponseValue(projectsPost1Response, "project.slug"), 'consumer project slug').toBe("skyramp-xproj-consumer");
    expect(getResponseValue(projectsPost1Response, "project.type"), 'consumer project type').toBe("secret-manager");

    // Request Body
    const secretsSecretsPostRequestBody: string = `{
        "environment": "dev",
        "projectId": "8f3a1c72-5b4e-4d9a-9c21-0e7b64a1d3f5",
        "secretPath": "/",
        "secretValue": "value-from-source-project"
    }`;

    // Execute Request
    const secretsSecretsPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets/{secrets}",
        method: "POST",
        body: secretsSecretsPostRequestBody,
        headers: headers,
        pathParams: {"secrets": secrets},
        dataOverride: {"projectId": getResponseValue(projectsPostResponse, "project.id")}
    });

    // Generated Assertions
    expect(secretsSecretsPostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(secretsSecretsPostResponse, "secret.secretKey"), 'source secret key').toBe("SHARED_KEY");
    expect(getResponseValue(secretsSecretsPostResponse, "secret.secretValue"), 'source secret value').toBe("value-from-source-project");

    // Request Body
    const secretsSecretsPost1RequestBody: string = `{
        "environment": "dev",
        "projectId": "b2d7e419-6a8c-4f30-8d15-72c9ab04e6d8",
        "secretPath": "/",
        "secretValue": "value-from-consumer-project"
    }`;

    // Execute Request
    const secretsSecretsPost1Response = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets/{secrets}",
        method: "POST",
        body: secretsSecretsPost1RequestBody,
        headers: headers,
        pathParams: {"secrets": getResponseValue(secretsSecretsPostResponse, "secret.secretKey")},
        dataOverride: {"projectId": getResponseValue(projectsPost1Response, "project.id")}
    });

    // Generated Assertions
    expect(secretsSecretsPost1Response.statusCode, 'status code').toBe(200);
    expect(getResponseValue(secretsSecretsPost1Response, "secret.secretKey"), 'consumer secret key').toBe("SHARED_KEY");
    expect(getResponseValue(secretsSecretsPost1Response, "secret.secretValue"), 'consumer secret value').toBe("value-from-consumer-project");

    // Request Body
    const secretsSecretsPost2RequestBody: string = `{
        "environment": "dev",
        "projectId": "b2d7e419-6a8c-4f30-8d15-72c9ab04e6d8",
        "secretPath": "/",
        "secretValue": "\${SHARED_KEY}"
    }`;

    // Execute Request
    const secretsSecretsPost2Response = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets/{secrets}",
        method: "POST",
        body: secretsSecretsPost2RequestBody,
        headers: headers,
        pathParams: {"secrets": secrets_1},
        dataOverride: {"projectId": getResponseValue(projectsPost1Response, "project.id")}
    });

    // Generated Assertions
    expect(secretsSecretsPost2Response.statusCode, 'status code').toBe(200);
    expect(getResponseValue(secretsSecretsPost2Response, "secret.secretKey"), 'local reference key').toBe("LOCAL_REF");
    expect(getResponseValue(secretsSecretsPost2Response, "secret.secretValue"), 'local reference stored unexpanded').toBe("\${SHARED_KEY}");

    // Request Body
    const secretsSecretsPost3RequestBody: string = `{
        "environment": "dev",
        "projectId": "b2d7e419-6a8c-4f30-8d15-72c9ab04e6d8",
        "secretPath": "/",
        "secretValue": "\${skyramp-xproj-src::dev.SHARED_KEY}"
    }`;

    // Execute Request
    const secretsSecretsPost3Response = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets/{secrets}",
        method: "POST",
        body: secretsSecretsPost3RequestBody,
        headers: headers,
        pathParams: {"secrets": secrets_2},
        dataOverride: {"projectId": getResponseValue(projectsPost1Response, "project.id")}
    });

    // Generated Assertions
    expect(secretsSecretsPost3Response.statusCode, 'status code').toBe(200);
    expect(getResponseValue(secretsSecretsPost3Response, "secret.secretKey"), 'cross-project reference key').toBe("CROSS_REF");
    expect(getResponseValue(secretsSecretsPost3Response, "secret.secretValue"), 'cross-project reference stored unexpanded').toBe("\${skyramp-xproj-src::dev.SHARED_KEY}");

    // Execute Request
    const secretsGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets",
        method: "GET",
        headers: headers,
        queryParams: {
            "environment": ["dev"],
            "expandSecretReferences": [expandSecretReferences],
            "includeImports": ["false"],
            "projectId": [getResponseValue(projectsPost1Response, "project.id")],
            "secretPath": ["/"],
            "viewSecretValue": [expandSecretReferences]
        }
    });

    // Generated Assertions
    expect(secretsGetResponse.statusCode, 'status code').toBe(200);
    // One request resolves BOTH references at dev:/ — the cross-project one and the local one.
    // Read the returned pairs by index so the assertions do not depend on list ordering.
    const expandedSecrets: Record<string, string> = {};
    for (let i = 0; i < 3; i += 1) {
        const secretKey = getResponseValue(secretsGetResponse, `secrets.${i}.secretKey`) as string | null;
        if (!secretKey) break;
        expandedSecrets[secretKey] = getResponseValue(secretsGetResponse, `secrets.${i}.secretValue`) as string;
    }
    expect(Object.keys(expandedSecrets).sort(), 'consumer dev:/ secret keys').toEqual(["CROSS_REF", "LOCAL_REF", "SHARED_KEY"]);
    expect(expandedSecrets.CROSS_REF, 'CROSS_REF must expand to the SOURCE project value').toBe("value-from-source-project");
    expect(expandedSecrets.LOCAL_REF, 'LOCAL_REF must expand to the CONSUMER own value').toBe("value-from-consumer-project");
    expect(expandedSecrets.SHARED_KEY, 'consumer own SHARED_KEY must be untouched').toBe("value-from-consumer-project");

    // Execute Request
    const projectsProjectsDeleteResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/projects/{projects}",
        method: "DELETE",
        headers: headers,
        pathParams: {"projects": getResponseValue(projectsPostResponse, "project.id")}
    });

    // Generated Assertions
    expect(projectsProjectsDeleteResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(projectsProjectsDeleteResponse, "project.slug"), 'deleted source project').toBe("skyramp-xproj-src");

    // Execute Request
    const projectsProjectsDelete1Response = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/projects/{projects}",
        method: "DELETE",
        headers: headers,
        pathParams: {"projects": getResponseValue(projectsPost1Response, "project.id")}
    });

    // Generated Assertions
    expect(projectsProjectsDelete1Response.statusCode, 'status code').toBe(200);
    expect(getResponseValue(projectsProjectsDelete1Response, "project.slug"), 'deleted consumer project').toBe("skyramp-xproj-consumer");
});
