// Generated by Skyramp v1.3.40 on 2026-08-27 14:46:04.325296516 +0000 UTC m=+1128.788685963
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output secrets_move_cross_user_override_orphan_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/backend/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/backend/tests/scenario_secrets_move_cross_user_override_orphan.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue, uniqueSuffix } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const environment = "prod";
    let projectId = "11111111-1111-4111-8111-111111111111";
    const secretPath = "/";
    const secrets = "ORPHAN_KEY";
    const type = "shared";

    // Request Body
    const workspacePostRequestBody: string = `{
        "projectName": "skyramp-override-orphan"
    }`;

    // Execute Request
    const workspacePostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v2/workspace",
        method: "POST",
        body: workspacePostRequestBody,
        headers: headers,
        dataOverride: {"projectName": uniqueSuffix("skyramp-override-orphan")}
    });

    // Generated Assertions
    expect(workspacePostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(workspacePostResponse, "project.id"), 'project.id').toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getResponseValue(workspacePostResponse, "project.type"), 'project.type').toBe("secret-manager");
    expect(getResponseValue(workspacePostResponse, "project.version"), 'project.version').toBe(3);
    projectId = getResponseValue(workspacePostResponse, "project.id");

    // Request Body
    const secretsPostRequestBody: string = `{
        "environment": "dev",
        "projectId": "11111111-1111-4111-8111-111111111111",
        "secretPath": "/",
        "secretValue": "shared-value",
        "type": "shared"
    }`;

    // Execute Request
    const secretsPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets/{secrets}",
        method: "POST",
        body: secretsPostRequestBody,
        headers: headers,
        pathParams: {"secrets": secrets},
        dataOverride: {
            "projectId": projectId,
            "secretPath": secretPath
        }
    });

    // Generated Assertions
    expect(secretsPostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(secretsPostResponse, "secret.secretKey"), 'secret.secretKey').toBe("ORPHAN_KEY");
    expect(getResponseValue(secretsPostResponse, "secret.secretValue"), 'secret.secretValue').toBe("shared-value");
    expect(getResponseValue(secretsPostResponse, "secret.type"), 'secret.type').toBe("shared");
    expect(getResponseValue(secretsPostResponse, "secret.environment"), 'secret.environment').toBe("dev");
    expect(getResponseValue(secretsPostResponse, "secret.version"), 'secret.version').toBe(1);
    expect(getResponseValue(secretsPostResponse, "secret.id"), 'secret.id').toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);

    // Request Body
    const secretsPost1RequestBody: string = `{
        "environment": "dev",
        "projectId": "11111111-1111-4111-8111-111111111111",
        "secretPath": "/",
        "secretValue": "personal-override-value",
        "type": "personal"
    }`;

    // Execute Request
    const secretsPost1Response = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets/{secrets}",
        method: "POST",
        body: secretsPost1RequestBody,
        headers: headers,
        pathParams: {"secrets": getResponseValue(secretsPostResponse, "secret.secretKey")},
        dataOverride: {
            "projectId": projectId,
            "secretPath": secretPath
        }
    });

    // Generated Assertions
    expect(secretsPost1Response.statusCode, 'status code').toBe(200);
    expect(getResponseValue(secretsPost1Response, "secret.secretKey"), 'secret.secretKey').toBe("ORPHAN_KEY");
    expect(getResponseValue(secretsPost1Response, "secret.secretValue"), 'secret.secretValue').toBe("personal-override-value");
    expect(getResponseValue(secretsPost1Response, "secret.type"), 'secret.type').toBe("personal");
    expect(getResponseValue(secretsPost1Response, "secret.environment"), 'secret.environment').toBe("dev");

    // Request Body
    const movePostRequestBody: string = `{
        "destinationEnvironment": "prod",
        "destinationSecretPath": "/",
        "projectId": "11111111-1111-4111-8111-111111111111",
        "secretIds": [
            "22222222-2222-4222-8222-222222222222"
        ],
        "shouldOverwrite": false,
        "sourceEnvironment": "dev",
        "sourceSecretPath": "/"
    }`;

    // Execute Request
    const movePostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets/move",
        method: "POST",
        body: movePostRequestBody,
        headers: headers,
        dataOverride: {
            "projectId": projectId,
            "sourceSecretPath": secretPath,
            "secretIds": [getResponseValue(secretsPostResponse, "secret.id")]
        }
    });

    // Generated Assertions
    expect(movePostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(movePostResponse, "isSourceUpdated"), 'isSourceUpdated').toBe(true);
    expect(getResponseValue(movePostResponse, "isDestinationUpdated"), 'isDestinationUpdated').toBe(true);
    expect(getResponseValue(movePostResponse, "movedOverridesCount"), 'movedOverridesCount').toBe(1);

    // Execute Request
    const secretsGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets/{secrets}",
        method: "GET",
        headers: headers,
        pathParams: {"secrets": getResponseValue(secretsPostResponse, "secret.secretKey")},
        queryParams: {
            "environment": ["dev"],
            "projectId": [projectId],
            "secretPath": [secretPath],
            "type": ["personal"]
        }
    });

    // Generated Assertions
    expect(secretsGetResponse.statusCode, 'status code').toBe(404);
    expect(getResponseValue(secretsGetResponse, "statusCode"), 'statusCode').toBe(404);
    expect(getResponseValue(secretsGetResponse, "error"), 'error').toBe("NotFound");
    expect(getResponseValue(secretsGetResponse, "message"), 'message').toBe("Secret with name 'ORPHAN_KEY' not found");
    expect(getResponseValue(secretsGetResponse, "secret"), 'secret').toBeNull();

    // Execute Request
    const secretsGet1Response = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets/{secrets}",
        method: "GET",
        headers: headers,
        pathParams: {"secrets": getResponseValue(secretsPostResponse, "secret.secretKey")},
        queryParams: {
            "environment": ["prod"],
            "projectId": [projectId],
            "secretPath": [secretPath],
            "type": ["shared"]
        }
    });

    // Generated Assertions
    expect(secretsGet1Response.statusCode, 'status code').toBe(200);
    expect(getResponseValue(secretsGet1Response, "secret.secretKey"), 'secret.secretKey').toBe("ORPHAN_KEY");
    expect(getResponseValue(secretsGet1Response, "secret.secretValue"), 'secret.secretValue').toBe("shared-value");
    expect(getResponseValue(secretsGet1Response, "secret.type"), 'secret.type').toBe("shared");
    expect(getResponseValue(secretsGet1Response, "secret.environment"), 'secret.environment').toBe("prod");
    expect(getResponseValue(secretsGet1Response, "secret.secretPath"), 'secret.secretPath').toBe("/");
});
