// Generated by Skyramp v1.3.30 on 2026-07-06 17:08:30.705959852 +0000 UTC m=+1863.384084716
// Command: skyramp generate contract rest http://localhost:8080/api/v4/secrets \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output secrets_multi_path_cap_contract_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/backend/tests \
// 		--overwrite \
// 		--provider \
// 		--query-params projectId=00000000-0000-0000-0000-000000000000,environment=dev,secretPaths=/p0%2C/p1%2C/p2%2C/p3%2C/p4%2C/p5%2C/p6%2C/p7%2C/p8%2C/p9%2C/p10 \
// 		--response-data {"statusCode":400,"message":"A maximum of 10 secret paths can be fetched per request, received 11","error":"BadRequest"} \
// 		--response-status-code 400 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect, SkyrampClient, checkSchema, getBaseUrl, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

// contract test for /api/v4/secrets GET
test('testSecretsGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Expected Response Body
    const expectedSecretsGetResponseBody: string = `{
        "error": "BadRequest",
        "message": "A maximum of 10 secret paths can be fetched per request, received 11",
        "statusCode": 400
    }`;

    // Execute Request
    const secretsGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/v4/secrets",
        method: "GET",
        headers: headers,
        queryParams: {
            "environment": "dev",
            "projectId": "00000000-0000-0000-0000-000000000000",
            "secretPaths": "/p0,/p1,/p2,/p3,/p4,/p5,/p6,/p7,/p8,/p9,/p10"
        }
    });

    // Generated Assertions
    expect(secretsGetResponse.statusCode, 'status code').toBe(400);
    expect(checkSchema(secretsGetResponse, expectedSecretsGetResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(secretsGetResponse, "error"), 'error').toBe("BadRequest");
    expect(getResponseValue(secretsGetResponse, "message"), 'message').toBe("A maximum of 10 secret paths can be fetched per request, received 11");
    expect(getResponseValue(secretsGetResponse, "statusCode"), 'statusCode').toBe(400);
});
