// Generated by Skyramp v1.3.30 on 2026-07-06 17:08:15.316166385 +0000 UTC m=+1847.994291249
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output secrets_multi_path_merge_precedence_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/backend/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/backend/tests/scenario_secrets_multi_path_merge_precedence.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const secrets = "LOG_LEVEL";

    // Request Body
    const projectsPostRequestBody: string = `{
        "projectName": "multipath-merge-test"
    }`;

    // Execute Request
    const projectsPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/projects",
        method: "POST",
        body: projectsPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(projectsPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(projectsPostResponse, "project.name"), 'name').toBe("multipath-merge-test");
    expect(getValue(projectsPostResponse, "project.id"), 'id').toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getValue(projectsPostResponse, "project.environments.0.slug"), 'environments.0.slug').toBe("dev");

    // Request Body
    const foldersPostRequestBody: string = `{
        "environment": "dev",
        "name": "svc",
        "path": "/",
        "workspaceId": "${getValue(projectsPostResponse, "project.id")}"
    }`;

    // Execute Request
    const foldersPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/folders",
        method: "POST",
        body: foldersPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(foldersPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(foldersPostResponse, "folder.name"), 'name').toBe("svc");
    expect(getValue(foldersPostResponse, "folder.path"), 'path').toBe("/svc");

    // Request Body
    const secretsSecretsPostRequestBody: string = `{
        "environment": "dev",
        "projectId": "${getValue(projectsPostResponse, "project.id")}",
        "secretPath": "/",
        "secretValue": "info"
    }`;

    // Execute Request
    const secretsSecretsPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets/{secrets}",
        method: "POST",
        body: secretsSecretsPostRequestBody,
        headers: headers,
        pathParams: {"secrets": secrets}
    });

    // Generated Assertions
    expect(secretsSecretsPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(secretsSecretsPostResponse, "secret.secretKey"), 'secretKey').toBe("LOG_LEVEL");
    expect(getValue(secretsSecretsPostResponse, "secret.secretValue"), 'secretValue').toBe("info");
    expect(getValue(secretsSecretsPostResponse, "secret.type"), 'type').toBe("shared");

    // Request Body
    const secretsSecretsPost1RequestBody: string = `{
        "environment": "dev",
        "projectId": "${getValue(projectsPostResponse, "project.id")}",
        "secretPath": "/svc",
        "secretValue": "debug"
    }`;

    // Execute Request
    const secretsSecretsPost1Response = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets/{secrets}",
        method: "POST",
        body: secretsSecretsPost1RequestBody,
        headers: headers,
        pathParams: {"secrets": secrets}
    });

    // Generated Assertions
    expect(secretsSecretsPost1Response.statusCode, 'status code').toBe(200);
    expect(getValue(secretsSecretsPost1Response, "secret.secretKey"), 'secretKey').toBe("LOG_LEVEL");
    expect(getValue(secretsSecretsPost1Response, "secret.secretValue"), 'secretValue').toBe("debug");
    expect(getValue(secretsSecretsPost1Response, "secret.type"), 'type').toBe("shared");

    // Execute Request
    const secretsGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets",
        method: "GET",
        headers: headers,
        queryParams: {
            "environment": ["dev"],
            "projectId": [getValue(projectsPostResponse, "project.id")],
            "secretPaths": ["/,/svc"]
        }
    });

    // Generated Assertions
    expect(secretsGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(secretsGetResponse, "merge.paths"), 'merge.paths').toEqual(["/", "/svc"]);
    expect(getValue(secretsGetResponse, "merge.overrides").length, 'overrides length').toBe(1);
    expect(getValue(secretsGetResponse, "merge.overrides.0.secretKey"), 'overrides.0.secretKey').toBe("LOG_LEVEL");
    expect(getValue(secretsGetResponse, "merge.overrides.0.type"), 'overrides.0.type').toBe("shared");
    expect(getValue(secretsGetResponse, "merge.overrides.0.winningPath"), 'overrides.0.winningPath').toBe("/svc");
    expect(getValue(secretsGetResponse, "merge.overrides.0.overriddenPaths"), 'overrides.0.overriddenPaths').toEqual(["/"]);
    expect(getValue(secretsGetResponse, "merge.overrides.1"), 'overrides.1').toBeUndefined();
    expect(getValue(secretsGetResponse, "secrets.0.secretKey"), 'secrets.0.secretKey').toBe("LOG_LEVEL");
    expect(getValue(secretsGetResponse, "secrets.0.secretValue"), 'secrets.0.secretValue').toBe(getValue(secretsSecretsPost1Response, "secret.secretValue"));
    expect(getValue(secretsGetResponse, "secrets.0.secretPath"), 'secrets.0.secretPath').toBe("/svc");
    expect(getValue(secretsGetResponse, "secrets.1"), 'secrets.1').toBeUndefined();
});
