// Generated by Skyramp v1.3.40 on 2026-08-26 19:22:44.36159088 +0000 UTC m=+1023.726119873
// Command: skyramp generate contract rest http://localhost:8080/api/v1/webhooks/{webhookId}/deliveries \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output webhook_deliveries_not_found_contract.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/backend/tests \
// 		--overwrite \
// 		--path-params webhookId=3f9a1c72-8b4e-4d21-9a6f-2e7c5d081b34 \
// 		--provider \
// 		--response-status-code 404 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

// contract test for /api/v1/webhooks/{webhookId}/deliveries GET
test('testDeliveriesGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const webhookId = "3f9a1c72-8b4e-4d21-9a6f-2e7c5d081b34";

    // Execute Request
    const deliveriesGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/v1/webhooks/{webhookId}/deliveries",
        method: "GET",
        headers: headers,
        pathParams: {"webhookId": webhookId}
    });

    // Generated Assertions
    expect(deliveriesGetResponse.statusCode, 'status code').toBe(404);
    expect(getValue(deliveriesGetResponse, "message"), 'error message').toBe("Webhook with ID '3f9a1c72-8b4e-4d21-9a6f-2e7c5d081b34' not found");
});
