// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const SecretShareAccessLogsSchema = z.object({
  id: z.string().uuid(),
  sharedSecretId: z.string().uuid(),
  actorEmail: z.string().nullable().optional(),
  ipAddress: z.string().nullable().optional(),
  userAgent: z.string().nullable().optional(),
  success: z.boolean(),
  failureReason: z.string().nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TSecretShareAccessLogs = z.infer<typeof SecretShareAccessLogsSchema>;
export type TSecretShareAccessLogsInsert = Omit<z.input<typeof SecretShareAccessLogsSchema>, TImmutableDBKeys>;
export type TSecretShareAccessLogsUpdate = Partial<Omit<z.input<typeof SecretShareAccessLogsSchema>, TImmutableDBKeys>>;
