// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const WebhookDeliveryLogsSchema = z.object({
  id: z.string().uuid(),
  webhookId: z.string().uuid(),
  status: z.string(),
  statusCode: z.number().nullable().optional(),
  eventType: z.string(),
  errorMessage: z.string().nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TWebhookDeliveryLogs = z.infer<typeof WebhookDeliveryLogsSchema>;
export type TWebhookDeliveryLogsInsert = Omit<z.input<typeof WebhookDeliveryLogsSchema>, TImmutableDBKeys>;
export type TWebhookDeliveryLogsUpdate = Partial<Omit<z.input<typeof WebhookDeliveryLogsSchema>, TImmutableDBKeys>>;
