// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const WebhookAttemptsSchema = z.object({
  id: z.string().uuid(),
  webhookId: z.string().uuid(),
  status: z.string().default("pending"),
  attemptNumber: z.number().default(1),
  statusCode: z.number().nullable().optional(),
  errorMessage: z.string().nullable().optional(),
  payload: z.unknown().nullable().optional(),
  nextRetryAt: z.date().nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TWebhookAttempts = z.infer<typeof WebhookAttemptsSchema>;
export type TWebhookAttemptsInsert = Omit<z.input<typeof WebhookAttemptsSchema>, TImmutableDBKeys>;
export type TWebhookAttemptsUpdate = Partial<Omit<z.input<typeof WebhookAttemptsSchema>, TImmutableDBKeys>>;
