// Generated by Skyramp v1.3.40 on 2026-08-27 14:18:19.715928001 +0000 UTC m=+620.775062177
// Command: skyramp generate contract rest http://localhost:8080/api/v2/secret-imports/secrets \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output audit_log_type_response_shape_update_shared_secret_secrets_contract_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/backend/skyramp-tests \
// 		--overwrite \
// 		--provider \
// 		--query-params projectId=00000000-0000-4000-8000-000000000001,environment=dev \
// 		--response-status-code 200 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

// contract test for /api/v2/secret-imports/secrets GET
test('testSecretsGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const secretsGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/v2/secret-imports/secrets",
        method: "GET",
        headers: headers,
        queryParams: {
            "environment": "dev",
            "projectId": "00000000-0000-4000-8000-000000000001"
        }
    });

    // Generated Assertions
    expect(secretsGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(secretsGetResponse, "secrets.environment"), 'environment').toBe("dev");
});
