// Generated by Skyramp v1.3.40 on 2026-08-27 14:59:50.38025083 +0000 UTC m=+973.472547549
// Command: skyramp generate contract rest http://localhost:8080/api/v4/secrets/archive \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output-dir /home/runner/work/infisical/infisical/backend/skyramp-tests \
// 		--overwrite \
// 		--provider \
// 		--provider-output contract_secrets_archive_auth_boundary.spec.ts \
// 		--request-data {"projectId":"9c4e1d70-8b32-4a6f-b5d1-27e0af63c948","environment":"dev","secretPath":"/","secretNames":["ANY_SECRET"]} \
// 		--response-data {"statusCode":401,"message":"Token missing","error":"UnauthorizedError"} \
// 		--response-status-code 401 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect, SkyrampClient, checkSchema, getBaseUrl, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

// contract test for /api/v4/secrets/archive POST
test('testArchivePost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const archivePostRequestBody: string = `{
        "environment": "dev",
        "projectId": "9c4e1d70-8b32-4a6f-b5d1-27e0af63c948",
        "secretNames": [
            "ANY_SECRET"
        ],
        "secretPath": "/"
    }`;

    // Expected Response Body
    const expectedArchivePostResponseBody: string = `{
        "error": "UnauthorizedError",
        "message": "Token missing",
        "statusCode": 401
    }`;

    // Execute Request
    const archivePostResponse = await client.sendRequest({
        url: URL,
        path: "/api/v4/secrets/archive",
        method: "POST",
        body: archivePostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(archivePostResponse.statusCode, 'status code').toBe(401);
    expect(checkSchema(archivePostResponse, expectedArchivePostResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(archivePostResponse, "error"), 'error').toBe("UnauthorizedError");
    expect(getResponseValue(archivePostResponse, "message"), 'message').toBe("Token missing");
    expect(getResponseValue(archivePostResponse, "statusCode"), 'statusCode').toBe(401);
});
