// Generated by Skyramp v1.3.40 on 2026-08-27 14:59:40.194293745 +0000 UTC m=+963.286590466
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output secrets_archive_lifecycle_archive_then_list_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/backend/skyramp-tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/backend/skyramp-tests/scenario_secrets_archive_lifecycle_archive_then_list.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getResponseValue, uniqueSuffix } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const secrets = "ARCHIVE_ME";

    // Request Body
    const v2WorkspacePostRequestBody: string = `{
        "projectName": "skyramp-archive-lifecycle",
        "slug": "skyramp-archive-lifecycle",
        "type": "secret-manager"
    }`;

    // Execute Request
    const v2WorkspacePostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v2/workspace",
        method: "POST",
        body: v2WorkspacePostRequestBody,
        headers: headers,
        dataOverride: {
            "projectName": uniqueSuffix("skyramp-archive"),
            "slug": uniqueSuffix("skyramp-archive")
        }
    });

    // Generated Assertions
    expect(v2WorkspacePostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(v2WorkspacePostResponse, "project.id"), 'project id').toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getResponseValue(v2WorkspacePostResponse, "project.type"), 'project type').toBe("secret-manager");
    expect(getResponseValue(v2WorkspacePostResponse, "project.environments.0.slug"), 'first environment slug').toBe("dev");
    expect(getResponseValue(v2WorkspacePostResponse, "project.environments.1.slug"), 'second environment slug').toBe("staging");
    expect(getResponseValue(v2WorkspacePostResponse, "project.environments.2.slug"), 'third environment slug').toBe("prod");
    expect(getResponseValue(v2WorkspacePostResponse, "project.environments.3"), 'no fourth environment').toBeFalsy();

    const projectId = getResponseValue(v2WorkspacePostResponse, "project.id");

    // Request Body
    const secretsPostRequestBody: string = `{
        "environment": "dev",
        "projectId": "d24b1f8e-3a5c-4e17-9f62-8c0b7a4d5e91",
        "secretPath": "/",
        "secretValue": "archive-me-value"
    }`;

    // Execute Request
    const secretsPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets/{secrets}",
        method: "POST",
        body: secretsPostRequestBody,
        headers: headers,
        pathParams: {"secrets": secrets},
        dataOverride: {"projectId": projectId}
    });

    // Generated Assertions
    expect(secretsPostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(secretsPostResponse, "secret.secretKey"), 'secret key').toBe("ARCHIVE_ME");
    expect(getResponseValue(secretsPostResponse, "secret.secretValue"), 'secret value').toBe("archive-me-value");
    expect(getResponseValue(secretsPostResponse, "secret.environment"), 'environment').toBe("dev");
    expect(getResponseValue(secretsPostResponse, "secret.type"), 'secret type').toBe("shared");
    expect(getResponseValue(secretsPostResponse, "secret.version"), 'version').toBe(1);
    expect(getResponseValue(secretsPostResponse, "secret.workspace"), 'workspace').toBe(projectId);
    expect(getResponseValue(secretsPostResponse, "secret.id"), 'secret id').toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);

    // Request Body
    const archivePostRequestBody: string = `{
        "environment": "dev",
        "projectId": "d24b1f8e-3a5c-4e17-9f62-8c0b7a4d5e91",
        "secretNames": [
            "ARCHIVE_ME"
        ],
        "secretPath": "/"
    }`;

    // Execute Request
    const archivePostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets/archive",
        method: "POST",
        body: archivePostRequestBody,
        headers: headers,
        dataOverride: {"projectId": projectId}
    });

    // Generated Assertions
    expect(archivePostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(archivePostResponse, "archivedCount"), 'archived count').toBe(1);
    expect(getResponseValue(archivePostResponse, "secretNames.0"), 'archived name').toBe("ARCHIVE_ME");
    expect(getResponseValue(archivePostResponse, "secretNames.1"), 'no extra archived names').toBeFalsy();

    // Execute Request
    const archivedGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets/archived",
        method: "GET",
        headers: headers,
        queryParams: {
            "environment": ["dev"],
            "projectId": [projectId],
            "secretPath": ["/"]
        }
    });

    // Generated Assertions
    expect(archivedGetResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(archivedGetResponse, "secrets.0.secretKey"), 'archived secret key').toBe("ARCHIVE_ME");
    expect(getResponseValue(archivedGetResponse, "secrets.0.id"), 'archived secret id').toBe(getResponseValue(secretsPostResponse, "secret.id"));
    expect(getResponseValue(archivedGetResponse, "secrets.0.version"), 'archived version').toBe(1);
    expect(getResponseValue(archivedGetResponse, "secrets.0.archivedAt"), 'archivedAt timestamp').toMatch(/^\d{4}-\d{2}-\d{2}T/);
    expect(getResponseValue(archivedGetResponse, "secrets.0.createdAt"), 'createdAt timestamp').toMatch(/^\d{4}-\d{2}-\d{2}T/);
    expect(getResponseValue(archivedGetResponse, "secrets.1"), 'no extra archived rows').toBeFalsy();

    // Execute Request
    const workspaceDeleteResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/workspace/{workspace}",
        method: "DELETE",
        headers: headers,
        pathParams: {"workspace": projectId}
    });

    // Generated Assertions
    expect(workspaceDeleteResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(workspaceDeleteResponse, "project.id"), 'deleted project id').toBe(projectId);
});
