// Generated by Skyramp v1.3.40 on 2026-08-27 14:18:09.154884605 +0000 UTC m=+610.214018791
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output shared_secret_patch_password_rotation_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/backend/skyramp-tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/backend/skyramp-tests/scenario_shared-secret-patch-password-rotation.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const sharedSecretsPostRequestBody: string = `{
        "accessType": "organization",
        "expiresIn": "30d",
        "secretValue": "my-super-secret-value"
    }`;

    // Execute Request
    const sharedSecretsPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/shared-secrets",
        method: "POST",
        body: sharedSecretsPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(sharedSecretsPostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(sharedSecretsPostResponse, "accessType"), 'accessType').toBe("organization");
    expect(getResponseValue(sharedSecretsPostResponse, "id"), 'id').not.toBeNull();
    expect(getResponseValue(sharedSecretsPostResponse, "expiresAt"), 'expiresAt').toMatch(/^\d{4}-\d{2}-\d{2}T/);

    // Request Body
    const sharedSecretsSharedSecretsPatchRequestBody: string = `{
        "name": "Renamed Share",
        "password": "RotatedPass123!"
    }`;

    // Execute Request
    const sharedSecretsSharedSecretsPatchResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/shared-secrets/{shared-secrets}",
        method: "PATCH",
        body: sharedSecretsSharedSecretsPatchRequestBody,
        headers: headers,
        pathParams: {"shared-secrets": getResponseValue(sharedSecretsPostResponse, "id")}
    });

    // Generated Assertions
    expect(sharedSecretsSharedSecretsPatchResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(sharedSecretsSharedSecretsPatchResponse, "name"), 'name').toBe("Renamed Share");
    expect(getResponseValue(sharedSecretsSharedSecretsPatchResponse, "id"), 'id').toBe(getResponseValue(sharedSecretsPostResponse, "id"));

    // Execute Request
    const sharedSecretsSharedSecretsGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/shared-secrets/{shared-secrets}",
        method: "GET",
        headers: headers,
        pathParams: {"shared-secrets": getResponseValue(sharedSecretsPostResponse, "id")}
    });

    // Generated Assertions
    expect(sharedSecretsSharedSecretsGetResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(sharedSecretsSharedSecretsGetResponse, "isPasswordProtected"), 'isPasswordProtected').toBe(true);
    expect(getResponseValue(sharedSecretsSharedSecretsGetResponse, "name"), 'name').toBe("Renamed Share");
    expect(getResponseValue(sharedSecretsSharedSecretsGetResponse, "id"), 'id').toBe(getResponseValue(sharedSecretsPostResponse, "id"));

    // Execute Request
    const sharedSecretsSharedSecretsDeleteResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/shared-secrets/{shared-secrets}",
        method: "DELETE",
        headers: headers,
        pathParams: {"shared-secrets": getResponseValue(sharedSecretsPostResponse, "id")}
    });

    // Generated Assertions
    expect(sharedSecretsSharedSecretsDeleteResponse.statusCode, 'status code').toBe(200);
});
