// Generated by Skyramp v1.3.40 on 2026-08-27 15:17:43.359026134 +0000 UTC m=+692.292659759
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output activity_summary_bulk_secret_creation_counted_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/backend/e2e-test \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/backend/e2e-test/scenario_activity-summary-bulk-secret-creation-counted.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue, uniqueSuffix } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const api = "v1";
    const api_1 = "v3";

    // Request Body
    const projectsPostRequestBody: string = `{
        "projectName": "activity-summary-bulk-secret-creation-counted",
        "shouldCreateDefaultEnvs": true
    }`;

    // Execute Request
    const projectsPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/{api}/projects",
        method: "POST",
        body: projectsPostRequestBody,
        headers: headers,
        pathParams: {"api": api},
        dataOverride: {"projectName": uniqueSuffix("activity-summary-bulk-secret-creation-counted")}
    });

    // Generated Assertions
    expect(projectsPostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(projectsPostResponse, "project.id"), 'project.id').toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getResponseValue(projectsPostResponse, "project.environments").length, 'environments length').toBe(3);
    expect(getResponseValue(projectsPostResponse, "project.environments.0.slug"), 'environments.0.slug').toBe("dev");
    expect(getResponseValue(projectsPostResponse, "project.environments.1.slug"), 'environments.1.slug').toBe("staging");
    expect(getResponseValue(projectsPostResponse, "project.environments.2.slug"), 'environments.2.slug').toBe("prod");
    expect(getResponseValue(projectsPostResponse, "project.environments.3"), 'environments.3').toBeUndefined();

    // Request Body
    const rawPostRequestBody: string = `{
        "environment": "dev",
        "secretPath": "/",
        "secrets": [
            {
                "secretKey": "BULK_A",
                "secretValue": "v1"
            },
            {
                "secretKey": "BULK_B",
                "secretValue": "v2"
            },
            {
                "secretKey": "BULK_C",
                "secretValue": "v3"
            }
        ],
        "workspaceId": "8a1c3ee4-6b2a-4c3d-9f1e-2d7b4a6c9e01"
    }`;

    // Execute Request
    const rawPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/{api}/secrets/batch/raw",
        method: "POST",
        body: rawPostRequestBody,
        headers: headers,
        pathParams: {"api": api_1},
        dataOverride: {"secrets.2.secretValue": api_1, "workspaceId": getResponseValue(projectsPostResponse, "project.id")}
    });

    // Generated Assertions
    expect(rawPostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(rawPostResponse, "secrets").length, 'secrets length').toBe(3);
    expect(getResponseValue(rawPostResponse, "secrets.0.secretKey"), 'secrets.0.secretKey').toBe("BULK_A");
    expect(getResponseValue(rawPostResponse, "secrets.0.workspace"), 'secrets.0.workspace').toBe(getResponseValue(projectsPostResponse, "project.id"));
    expect(getResponseValue(rawPostResponse, "secrets.0.environment"), 'secrets.0.environment').toBe("dev");
    expect(getResponseValue(rawPostResponse, "secrets.1.secretKey"), 'secrets.1.secretKey').toBe("BULK_B");
    expect(getResponseValue(rawPostResponse, "secrets.2.secretKey"), 'secrets.2.secretKey').toBe("BULK_C");
    expect(getResponseValue(rawPostResponse, "secrets.3"), 'secrets.3').toBeUndefined();

    // Execute Request
    const activitySummaryGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/{api}/projects/{projects}/activity-summary",
        method: "GET",
        headers: headers,
        pathParams: {
            "api": api,
            "projects": getResponseValue(projectsPostResponse, "project.id")
        }
    });

    // Generated Assertions
    expect(activitySummaryGetResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(activitySummaryGetResponse, "secretsCreated"), 'secretsCreated').toBe(3);
    expect(getResponseValue(activitySummaryGetResponse, "secretsUpdated"), 'secretsUpdated').toBe(0);
    expect(getResponseValue(activitySummaryGetResponse, "secretsDeleted"), 'secretsDeleted').toBe(0);
});
