// Generated by Skyramp v1.3.40 on 2026-08-27 14:53:48.194020861 +0000 UTC m=+878.689502331
// Command: skyramp generate contract rest http://localhost:8080/api/v4/secrets/archive \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output archive_secrets_requires_auth.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/backend/e2e-test \
// 		--overwrite \
// 		--provider \
// 		--request-data {"projectId":"5a174d43-62ef-487e-a513-dafd606225e9","environment":"dev","secretPath":"/","secretNames":["ANY_SECRET"]} \
// 		--response-status-code 401 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

// contract test for /api/v4/secrets/archive POST
test('testArchivePost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Intentionally no Authorization header — this test asserts the endpoint rejects unauthenticated requests
    const headers: Record<string, string> = {};

    // Request Body
    const archivePostRequestBody: string = `{
        "environment": "dev",
        "projectId": "5a174d43-62ef-487e-a513-dafd606225e9",
        "secretNames": [
            "DB_PASSWORD"
        ],
        "secretPath": "/"
    }`;

    // Execute Request
    const archivePostResponse = await client.sendRequest({
        url: URL,
        path: "/api/v4/secrets/archive",
        method: "POST",
        body: archivePostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(archivePostResponse.statusCode, 'status code').toBe(401);
    expect(getValue(archivePostResponse, "error"), 'error').toBe("UnauthorizedError");
    expect(getValue(archivePostResponse, "message"), 'message').toBe("Token missing");
});
