# Generated by Skyramp v1.3.40 on 2026-08-27 14:48:15.794058174 +0000 UTC m=+953.899739431
# Command: skyramp generate contract rest http://localhost:8080/api/v4/secrets/archive \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output contract_archive_auth_boundary_test.py \
# 		--output-dir /home/runner/work/infisical/infisical/backend/e2e-test/ \
# 		--overwrite \
# 		--provider \
# 		--request-data {"projectId":"77fa7aed-9288-401e-a4c9-3a9430be62a4","environment":"dev","secretPath":"/","secretNames":["any-secret"]} \
# 		--response-status-code 401 \
# 		--runtime local

# Import of required libraries
import skyramp
import os


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

# contract test for /api/v4/secrets/archive POST
def test_archive_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}

    # Request Body
    archive_POST_request_body = r'''{
        "environment": "dev",
        "projectId": "77fa7aed-9288-401e-a4c9-3a9430be62a4",
        "secretNames": [
            "any-secret"
        ],
        "secretPath": "/"
    }'''

    # Execute Request
    archive_POST_response = client.send_request(
        url=URL,
        path="/api/v4/secrets/archive",
        method="POST",
        body=archive_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert archive_POST_response.status_code == 401
    assert skyramp.get_response_value(archive_POST_response, "statusCode") == 401
    assert skyramp.get_response_value(archive_POST_response, "error") == "UnauthorizedError"
    assert skyramp.get_response_value(archive_POST_response, "message") == "Token missing"


if __name__ == "__main__":
    test_archive_post()
