# Generated by Skyramp v1.3.40 on 2026-08-26 19:11:24.306458777 +0000 UTC m=+506.350809911
# Command: skyramp generate contract rest http://localhost:8080/api/v1/webhooks/{webhookId}/deliveries \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/infisical/infisical/backend/e2e-test/ \
# 		--overwrite \
# 		--path-params webhookId=a1b2c3d4-e5f6-7890-abcd-ef1234567890 \
# 		--provider \
# 		--query-params limit=20,offset=0 \
# 		--runtime local

# Import of required libraries
import skyramp
import os


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

# contract test for /api/v1/webhooks/{webhookId}/deliveries GET
def test_deliveries_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    webhookId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"

    # Execute Request
    deliveries_GET_response = client.send_request(
        url=URL,
        path="/api/v1/webhooks/{webhookId}/deliveries",
        method="GET",
        headers=headers,
        path_params={"webhookId": webhookId},
        query_params={
            "limit": "20",
            "offset": "0"
        }
    )

    # Generated Assertions
    assert skyramp.check_status_code(deliveries_GET_response, "20x")
    # Array / Items validation: deliveries is an empty array for a non-existent webhookId
    # but endpoint should return 200 with deliveries and totalCount
    assert skyramp.check_schema(deliveries_GET_response, '{"message": "Successfully fetched webhook deliveries", "totalCount": 0, "deliveries": []}')
    # Chained values from inline request data: verify totalCount is a non-negative integer
    total_count = skyramp.get_response_value(deliveries_GET_response, "totalCount")
    assert total_count >= 0
    # Verify deliveries field is present as an array
    deliveries = skyramp.get_response_value(deliveries_GET_response, "deliveries")
    assert isinstance(deliveries, list)


if __name__ == "__main__":
    test_deliveries_get()
