// Generated by Skyramp v1.3.38 on 2026-08-19 16:33:02.211043673 +0000 UTC m=+654.472377121
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output folder_rename_cascade_descendant_paths_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/backend/e2e-test \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/backend/e2e-test/scenario_folder-rename-cascade-descendant-paths.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue, uniqueSuffix } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const foldersPostRequestBody: string = `{
        "environment": "dev",
        "name": "parent-folder",
        "path": "/",
        "projectId": "ad9afa30-2eff-4797-ab48-0dc69a6cea11"
    }`;

    // Execute Request
    const foldersPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v2/folders",
        method: "POST",
        body: foldersPostRequestBody,
        headers: headers,
        dataOverride: {"name": uniqueSuffix("parent-folder")}
    });

    // Generated Assertions
    expect(foldersPostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(foldersPostResponse, "folder.id")).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getResponseValue(foldersPostResponse, "folder.name")).not.toBeNull();

    // Request Body
    const foldersFoldersPatchRequestBody: string = `{
        "environment": "dev",
        "name": "parent-folder-renamed",
        "path": "/",
        "projectId": "ad9afa30-2eff-4797-ab48-0dc69a6cea11"
    }`;

    // Execute Request
    const foldersFoldersPatchResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v2/folders/{folders}",
        method: "PATCH",
        body: foldersFoldersPatchRequestBody,
        headers: headers,
        pathParams: {"folders": getResponseValue(foldersPostResponse, "folder.id")},
        dataOverride: {"name": uniqueSuffix("parent-folder-renamed")}
    });

    // Generated Assertions
    expect(foldersFoldersPatchResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(foldersFoldersPatchResponse, "folder.id")).toBe(getResponseValue(foldersPostResponse, "folder.id"));
    expect(getResponseValue(foldersFoldersPatchResponse, "updatedImportsCount")).toBe(0);
    expect(getResponseValue(foldersFoldersPatchResponse, "updatedReferencesCount")).toBe(0);
    expect(getResponseValue(foldersFoldersPatchResponse, "updatedImportsCount")).toBeGreaterThanOrEqual(0);
    expect(getResponseValue(foldersFoldersPatchResponse, "updatedReferencesCount")).toBeGreaterThanOrEqual(0);

    // Request Body
    const foldersFoldersDeleteRequestBody: string = `{
        "environment": "dev",
        "path": "/",
        "projectId": "ad9afa30-2eff-4797-ab48-0dc69a6cea11"
    }`;

    // Execute Request
    const foldersFoldersDeleteResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v2/folders/{folders}",
        method: "DELETE",
        body: foldersFoldersDeleteRequestBody,
        headers: headers,
        pathParams: {"folders": getResponseValue(foldersPostResponse, "folder.id")}
    });

    // Generated Assertions
    expect(foldersFoldersDeleteResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(foldersFoldersDeleteResponse, "folder.id")).toBe(getResponseValue(foldersPostResponse, "folder.id"));
});
