// Generated by Skyramp v1.3.38 on 2026-08-19 16:32:49.331706573 +0000 UTC m=+641.593040021
// Command: skyramp generate contract rest http://localhost:8080/api/v2/folders/{folderId} \
// 		--framework playwright \
// 		--language typescript \
// 		--method PATCH \
// 		--output folder_rename_permission_check.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/backend/e2e-test \
// 		--overwrite \
// 		--path-params folderId=a1b2c3d4-e5f6-7890-abcd-ef1234567890 \
// 		--provider \
// 		--request-data {"projectId":"77fa7aed-9288-401e-a4c9-3a9430be62a0","environment":"dev","name":"renamed-folder","path":"/"} \
// 		--response-status-code 401 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

// contract test for /api/v2/folders/{folderId} PATCH
test('testFoldersFolderIdPatch', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // No authentication header — this test verifies unauthenticated access returns 401
    const headers: Record<string, string> = {};

    // Declaration of variables
    const folderId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890";

    // Request Body
    const foldersFolderIdPatchRequestBody: string = `{
        "environment": "dev",
        "name": "renamed-folder",
        "path": "/",
        "projectId": "77fa7aed-9288-401e-a4c9-3a9430be62a0"
    }`;

    // Execute Request
    const foldersFolderIdPatchResponse = await client.sendRequest({
        url: URL,
        path: "/api/v2/folders/{folderId}",
        method: "PATCH",
        body: foldersFolderIdPatchRequestBody,
        headers: headers,
        pathParams: {"folderId": folderId}
    });

    // Generated Assertions
    expect(foldersFolderIdPatchResponse.statusCode, 'status code').toBe(401);
    expect(getValue(foldersFolderIdPatchResponse, "statusCode")).toBe(401);
    expect(getValue(foldersFolderIdPatchResponse, "error")).not.toBeNull();
    expect(getValue(foldersFolderIdPatchResponse, "message")).not.toBeNull();
});
