# Generated by Skyramp v1.3.40 on 2026-08-27 14:48:29.19787146 +0000 UTC m=+967.303552737
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output secret_archive_delete_permanently_integration_test.py \
# 		--output-dir /home/runner/work/infisical/infisical/backend/e2e-test/ \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/infisical/infisical/backend/e2e-test/scenario_secret-archive-delete-permanently.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    batch_POST_request_body = r'''{
        "environment": "dev",
        "projectId": "f99b678a-253e-4182-9de3-e147bb0f6287",
        "secretPath": "/",
        "secrets": [
            {
                "secretKey": "TEST-PERM-DELETE-SEC",
                "secretValue": "my-test-value"
            }
        ]
    }'''

    # Execute Request
    batch_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v4/secrets/batch",
        method="POST",
        body=batch_POST_request_body,
        headers=headers,
        data_override={"secrets.0.secretKey": skyramp.unique_suffix("TEST-PERM-DELETE-SEC")}
    )

    # Generated Assertions
    assert batch_POST_response.status_code == 200
    assert skyramp.get_response_value(batch_POST_response, "secrets.0.secretKey") is not None
    assert skyramp.get_response_value(batch_POST_response, "secrets.0.secretValue") == "my-test-value"
    assert skyramp.get_response_value(batch_POST_response, "secrets.1.secretKey") is None

    # Request Body
    archive_POST_request_body = r'''{
        "environment": "dev",
        "projectId": "f99b678a-253e-4182-9de3-e147bb0f6287",
        "secretNames": [
            "TEST-PERM-DELETE-SEC"
        ],
        "secretPath": "/"
    }'''

    # Execute Request
    archive_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v4/secrets/archive",
        method="POST",
        body=archive_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert archive_POST_response.status_code == 200
    assert skyramp.get_response_value(archive_POST_response, "archivedCount") == 1
    assert skyramp.get_response_value(archive_POST_response, "secretNames.0") == skyramp.get_response_value(batch_POST_response, "secrets.0.secretKey")
    assert skyramp.get_response_value(archive_POST_response, "secretNames.1") is None

    # Request Body
    archived_DELETE_request_body = r'''{
        "environment": "dev",
        "projectId": "f99b678a-253e-4182-9de3-e147bb0f6287",
        "secretNames": [
            "TEST-PERM-DELETE-SEC"
        ],
        "secretPath": "/"
    }'''

    # Execute Request
    archived_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/v4/secrets/archived",
        method="DELETE",
        body=archived_DELETE_request_body,
        headers=headers
    )

    # Generated Assertions
    assert archived_DELETE_response.status_code == 200
    assert skyramp.get_response_value(archived_DELETE_response, "deletedCount") == 1
    assert skyramp.get_response_value(archived_DELETE_response, "secretNames.0") == skyramp.get_response_value(batch_POST_response, "secrets.0.secretKey")
    assert skyramp.get_response_value(archived_DELETE_response, "secretNames.1") is None


if __name__ == "__main__":
    test_integration()
