// Generated by Skyramp v1.3.40 on 2026-08-27 14:52:46.741095235 +0000 UTC m=+817.236576705
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_archive_hides_from_get_by_id.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/backend/e2e-test \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/backend/e2e-test/scenario_secret_archive_hides_from_get_by_id.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const secrets = "TESTBOT_ARCHIVE_BUG_TEST";

    // Request Body
    const secretsPostRequestBody: string = `{
        "environment": "dev",
        "projectId": "5a174d43-62ef-487e-a513-dafd606225e9",
        "secretPath": "/",
        "secretValue": "super-secret-value-123"
    }`;

    // Execute Request
    const secretsPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets/{secrets}",
        method: "POST",
        body: secretsPostRequestBody,
        headers: headers,
        pathParams: {"secrets": secrets}
    });

    // Generated Assertions
    expect(secretsPostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(secretsPostResponse, "secret.secretKey"), 'secret.secretKey').toBe(secrets);
    expect(getResponseValue(secretsPostResponse, "secret.secretValue"), 'secret.secretValue').toBe("super-secret-value-123");
    expect(getResponseValue(secretsPostResponse, "secret.environment"), 'secret.environment').toBe("dev");
    expect(getResponseValue(secretsPostResponse, "secret.version"), 'secret.version').toBe(1);
    expect(getResponseValue(secretsPostResponse, "secret.id"), 'secret.id').toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getResponseValue(secretsPostResponse, "secret.createdAt"), 'secret.createdAt').toMatch(/^\d{4}-\d{2}-\d{2}T/);
    expect(getResponseValue(secretsPostResponse, "secret.updatedAt"), 'secret.updatedAt').toMatch(/^\d{4}-\d{2}-\d{2}T/);

    // Request Body
    const archivePostRequestBody: string = `{
        "environment": "dev",
        "projectId": "5a174d43-62ef-487e-a513-dafd606225e9",
        "secretNames": [
            "TESTBOT_ARCHIVE_BUG_TEST"
        ],
        "secretPath": "/"
    }`;

    // Execute Request
    const archivePostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets/archive",
        method: "POST",
        body: archivePostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(archivePostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(archivePostResponse, "archivedCount"), 'archivedCount').toBe(1);
    expect(getResponseValue(archivePostResponse, "secretNames.0"), 'secretNames.0').toBe(secrets);
    expect(getResponseValue(archivePostResponse, "secretNames.1"), 'secretNames.1').toBeUndefined();

    // Execute Request
    const idGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets/id/{id}",
        method: "GET",
        headers: headers,
        pathParams: {"id": getResponseValue(secretsPostResponse, "secret.id")}
    });

    // Generated Assertions
    expect(idGetResponse.statusCode, 'status code').toBe(404);

    // Request Body
    const archivedDeleteRequestBody: string = `{
        "environment": "dev",
        "projectId": "5a174d43-62ef-487e-a513-dafd606225e9",
        "secretNames": [
            "TESTBOT_ARCHIVE_BUG_TEST"
        ],
        "secretPath": "/"
    }`;

    // Execute Request
    const archivedDeleteResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets/archived",
        method: "DELETE",
        body: archivedDeleteRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(archivedDeleteResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(archivedDeleteResponse, "deletedCount"), 'deletedCount').toBe(1);
    expect(getResponseValue(archivedDeleteResponse, "secretNames.0"), 'secretNames.0').toBe(secrets);
    expect(getResponseValue(archivedDeleteResponse, "secretNames.1"), 'secretNames.1').toBeUndefined();
});
