// Generated by Skyramp v1.3.38 on 2026-08-19 14:07:29.88972459 +0000 UTC m=+519.809576781
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output v4_secret_tag_filter_any_semantics_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/backend/e2e-test \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/backend/e2e-test/scenario_v4-secret-tag-filter-any-semantics.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const secretsGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets",
        method: "GET",
        headers: headers,
        queryParams: {
            "environment": ["dev"],
            "projectId": ["a8746afa-d91b-4f04-8373-bda1dd9e3f6d"],
            "secretPath": ["/"]
        }
    });

    // Generated Assertions
    expect(secretsGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(secretsGetResponse, "secrets")).not.toBeNull();
    expect(getValue(secretsGetResponse, "imports")).not.toBeNull();
});
