# Generated by Skyramp v1.3.40 on 2026-08-26 19:12:41.157647834 +0000 UTC m=+583.201998947
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output webhook_auto_disable_delivery_tracking_integration_test.py \
# 		--output-dir /home/runner/work/infisical/infisical/backend/e2e-test/ \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/infisical/infisical/backend/e2e-test/scenario_webhook-auto-disable-delivery-tracking.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Declaration of variables
    webhooks = "c0d1e2f3-a4b5-6789-cdef-012345678901"

    # Execute Request
    deliveries_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/webhooks/a0b1c2d3-e4f5-6789-abcd-ef0123456789/deliveries",
        method="GET",
        query_params={
            "limit": ["20"],
            "offset": ["0"]
        }
    )

    # Generated Assertions
    assert deliveries_GET_response.status_code == 200
    assert skyramp.get_response_value(deliveries_GET_response, "message") == "Successfully fetched webhook deliveries"
    assert skyramp.get_response_value(deliveries_GET_response, "totalCount") == 0
    deliveries = skyramp.get_response_value(deliveries_GET_response, "deliveries")
    assert len(deliveries) == 0
    assert skyramp.get_response_value(deliveries_GET_response, "deliveries.0") is None

    # Request Body
    reactivate_POST_request_body = r'''{}'''

    # Execute Request
    reactivate_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/webhooks/{webhooks}/reactivate",
        method="POST",
        body=reactivate_POST_request_body,
        path_params={"webhooks": webhooks}
    )

    # Generated Assertions
    assert reactivate_POST_response.status_code == 200
    assert skyramp.get_response_value(reactivate_POST_response, "message") == "Successfully reactivated webhook"
    assert skyramp.get_response_value(reactivate_POST_response, "webhook.id") == webhooks
    assert skyramp.get_response_value(reactivate_POST_response, "webhook.isDisabled") == False
    assert skyramp.get_response_value(reactivate_POST_response, "webhook.consecutiveFailures") == 0
    assert skyramp.check_schema(reactivate_POST_response, '{"webhook": {"autoDisabledAt": null}}')


if __name__ == "__main__":
    test_integration()
