// Generated by Skyramp v1.3.40 on 2026-08-27 14:27:31.520929334 +0000 UTC m=+607.233203782
// Command: skyramp generate contract rest http://localhost:8080/api/v1/shared-secrets/{id}/access \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output access_nonexistent_shared_secret_404.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/backend/skyramp \
// 		--overwrite \
// 		--path-params id=bm9uZXhpc3RlbnRfc2t5cmFtcF9pZA \
// 		--provider \
// 		--request-data {"password":"skyramp-nonexistent"} \
// 		--response-status-code 404 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

// contract test for /api/v1/shared-secrets/{id}/access POST
test('testAccessPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const id = "bm9uZXhpc3RlbnRfc2t5cmFtcF9pZA";

    // Request Body
    const accessPostRequestBody: string = `{
        "password": "skyramp-nonexistent"
    }`;

    // Execute Request
    const accessPostResponse = await client.sendRequest({
        url: URL,
        path: "/api/v1/shared-secrets/{id}/access",
        method: "POST",
        body: accessPostRequestBody,
        headers: headers,
        pathParams: {"id": id}
    });

    // Generated Assertions
    expect(accessPostResponse.statusCode, 'status code').toBe(404);
    expect(getValue(accessPostResponse, "statusCode"), 'body statusCode').toBe(404);
    expect(getValue(accessPostResponse, "error"), 'error').toBe("NotFound");
    expect(getValue(accessPostResponse, "message"), 'message').toBe("Shared secret with ID 'bm9uZXhpc3RlbnRfc2t5cmFtcF9pZA' not found");
});
