// Generated by Skyramp v1.3.40 on 2026-08-27 14:27:52.608721255 +0000 UTC m=+628.320995673
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output notify_on_access_persists_on_create.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/backend/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/backend/skyramp/scenario_notify-on-access-persists-on-create.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const sharedSecretsPostRequestBody: string = `{
        "accessType": "organization",
        "expiresIn": "1h",
        "notifyOnAccess": true,
        "secretValue": "notify-secret-val"
    }`;

    // Execute Request
    const sharedSecretsPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/shared-secrets",
        method: "POST",
        body: sharedSecretsPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(sharedSecretsPostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(sharedSecretsPostResponse, "notifyOnAccess"), 'notifyOnAccess').toBe(true);
    expect(getResponseValue(sharedSecretsPostResponse, "accessType"), 'accessType').toBe("organization");
    expect(getResponseValue(sharedSecretsPostResponse, "type"), 'type').toBe("share");
    expect(getResponseValue(sharedSecretsPostResponse, "sharedSecretLink"), 'sharedSecretLink').toMatch(/^https?:\/\//);

    // Execute Request
    const sharedSecretsSharedSecretsGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/shared-secrets/{shared-secrets}",
        method: "GET",
        headers: headers,
        pathParams: {"shared-secrets": getResponseValue(sharedSecretsPostResponse, "id")}
    });

    // Generated Assertions
    expect(sharedSecretsSharedSecretsGetResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(sharedSecretsSharedSecretsGetResponse, "id"), 'id').toBe(getResponseValue(sharedSecretsPostResponse, "id"));
    expect(getResponseValue(sharedSecretsSharedSecretsGetResponse, "notifyOnAccess"), 'notifyOnAccess persisted').toBe(true);
    expect(getResponseValue(sharedSecretsSharedSecretsGetResponse, "accessType"), 'accessType').toBe("organization");
    expect(getResponseValue(sharedSecretsSharedSecretsGetResponse, "isPasswordProtected"), 'isPasswordProtected').toBe(false);

    // Execute Request
    const sharedSecretsSharedSecretsDeleteResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/shared-secrets/{shared-secrets}",
        method: "DELETE",
        headers: headers,
        pathParams: {"shared-secrets": getResponseValue(sharedSecretsPostResponse, "id")}
    });

    // Generated Assertions
    expect(sharedSecretsSharedSecretsDeleteResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(sharedSecretsSharedSecretsDeleteResponse, "id"), 'deleted id').toBe(getResponseValue(sharedSecretsPostResponse, "id"));
});
