# Generated by Skyramp v1.3.40 on 2026-08-27 15:00:42.629709886 +0000 UTC m=+595.350834445
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output cross_project_ref_invalid_syntax_graceful_integration_test.py \
# 		--output-dir /home/runner/work/infisical/infisical/.skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/infisical/infisical/.skyramp/scenario_cross-project-ref-invalid-syntax-graceful.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Declaration of variables
    secrets = "HOST_SECRET_TEST"

    # Request Body
    secrets_POST_request_body = r'''{
        "environment": "dev",
        "projectId": "PLACEHOLDER_PROJECT_ID",
        "secretPath": "/",
        "secretValue": "postgres://user:pass@host:5432/db"
    }'''

    # Execute Request
    secrets_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v4/secrets/{secrets}",
        method="POST",
        body=secrets_POST_request_body,
        path_params={"secrets": secrets}
    )

    # Generated Assertions
    assert secrets_POST_response.status_code == 200
    assert skyramp.get_response_value(secrets_POST_response, "secret.secretKey") == "HOST_SECRET_TEST"
    assert skyramp.get_response_value(secrets_POST_response, "secret.secretValue") == "postgres://user:pass@host:5432/db"
    assert skyramp.get_response_value(secrets_POST_response, "secret.secretPath") is not None
    assert skyramp.check_schema(secrets_POST_response, '{"secret": {"id": "non-null-placeholder"}}')

    # Execute Request
    secrets_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v4/secrets/{secrets}",
        method="GET",
        path_params={"secrets": secrets},
        query_params={
            "environment": ["dev"],
            "expandSecretReferences": ["true"],
            "projectId": ["PLACEHOLDER_PROJECT_ID"],
            "secretPath": ["/"]
        }
    )

    # Generated Assertions
    assert secrets_GET_response.status_code == 200
    assert skyramp.get_response_value(secrets_GET_response, "secret.secretKey") == "HOST_SECRET_TEST"
    assert skyramp.get_response_value(secrets_GET_response, "secret.secretValue") == "postgres://user:pass@host:5432/db"
    assert skyramp.get_response_value(secrets_GET_response, "secret.secretPath") == "/"


if __name__ == "__main__":
    test_integration()
