// Generated by Skyramp v1.3.40 on 2026-08-27 15:18:20.852822621 +0000 UTC m=+1653.573947166
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output cross_project_reference_builder_ui.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/.skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/cross_project_reference_builder_ui_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4000");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1831000);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await page.goto("http://localhost:8080");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "All Projects" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    const existingProject = page.getByRole("link", { name: "test-project" });
    if (await existingProject.isVisible().catch(() => false)) {
        await existingProject.click();
    } else {
        await page.getByRole("button", { name: "Add New Project" }).click();
        await page.getByRole("textbox", { name: "Type your project name" }).fill("test-project");
        await page.getByRole("button", { name: "Create Project" }).click();
        // Wait for network activities to finish
        await page.waitForTimeout(3000);
    }

    await page.getByRole("link", { name: "Overview" }).click();
    const existingSecret = page.getByRole("row", { name: "API_KEY" });
    if (!(await existingSecret.isVisible().catch(() => false))) {
        await page.getByText("Add a New Secret").click();
        await page.getByRole("textbox", { name: "Type your secret name" }).fill("API_KEY");
        await page.getByRole("textbox", { name: "secret value" }).fill("my-api-key-value");
        await page.getByRole("button", { name: "Create Secret" }).click();
        // Wait for network activities to finish
        await page.waitForTimeout(20000);
    }

    await page.waitForLoadState('networkidle');
    await page.getByRole("row", { name: "API_KEY" }).waitFor({ state: 'visible', timeout: 10000 });
    await page.getByRole("row", { name: "API_KEY" }).hover();
    await page.locator("main").getByRole("button", { name: "Reveal Values" }).click();
    await page.getByRole("row", { name: "API_KEY" }).hover();
    await page.locator("button:nth-child(9)").click();
    await page.getByRole("row", { name: "API_KEY" }).hover();

    await page.mouse.move(1190, 363);
    // Wait for network activities to finish
    await page.waitForTimeout(1500);

    await page.locator("body").click({ position: {"x": 1190, "y": 363} });
    await page.getByRole("menuitem", { name: "Insert Cross-Project Reference" }).click();
    await expect(page.getByRole("heading", { name: "Insert cross-project" })).toContainText("Insert cross-project reference");
    await expect(page.getByText("Reference a secret stored in")).toContainText("Reference a secret stored in another project");
    await expect(page.getByRole("button", { name: "Insert reference" })).toBeVisible();
    await expect(page.getByRole("button", { name: "Cancel" })).toBeVisible();
    expect(pageErrors).toHaveLength(0);
});
