// Generated by Skyramp v1.3.30 on 2026-07-05 04:00:58.221847131 +0000 UTC m=+1261.001231796
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output cross_project_reference_insert.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/.skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/cross_project_reference_insert_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1816000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(6000);

    await page.waitForTimeout(2000);

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Add New Project" }).click();
    await page.getByRole("textbox", { name: "Type your project name" }).fill("shared-infra");
    await page.getByRole("button", { name: "Create Project" }).click();
    await page.getByText("Add Secret").click();
    await page.getByRole("textbox", { name: "Type your secret name" }).fill("TLS_CERT");
    await page.getByRole("textbox", { name: "secret value" }).fill("-----BEGIN CERTIFICATE-----test-cert-value-----END CERTIFICATE-----");
    await page.getByRole("button", { name: "Create Secret" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("link", { name: "Overview" }).click();
    await page.waitForSelector("text=Add New Project");
    await page.getByRole("button", { name: "Add New Project" }).click();
    await page.getByRole("textbox", { name: "Type your project name" }).fill("app-service");
    await page.getByRole("button", { name: "Create Project" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByText("Add Secret").click();
    await page.getByRole("textbox", { name: "Type your secret name" }).fill("SMTP_URL");
    await page.getByRole("textbox", { name: "secret value" }).fill("placeholder");
    await page.getByRole("button", { name: "Create Secret" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("row", { name: "SMTP_URL" }).hover();
    await page.getByRole("row", { name: "SMTP_URL" }).hover();
    await page.mouse.move(900, 363);
    await page.locator(".inline-flex.items-center.active\\\\:scale-\\\\[0\\\\.99\\\\].justify-center.cursor-pointer.whitespace-nowrap.text-sm.font-medium.disabled\\\\:pointer-events-none.disabled\\\\:opacity-50.\\\\[\\\\&_svg\\\\]\\\\:pointer-events-none.shrink-0.\\\\[\\\\&\\\\>svg\\\\]\\\\:shrink-0.focus-visible\\\\:ring-ring.outline-0.focus-visible\\\\:ring-2.text-foreground.hover\\\\:bg-foreground\\\\/10.border-transparent.data-\\\\[state\\\\=open\\\\]\\\\:bg-foreground\\\\/10.h-7.\\\\[\\\\&\\\\>svg\\\\]\\\\:size-4.rounded-sm.\\\\[\\\\&\\\\>svg\\\\]\\\\:stroke-\\\\[1\\\\.75\\\\].w-0").click();
    await page.locator("button:nth-child(9)").click();
    await page.keyboard.press("Escape");
    await page.keyboard.press("Escape");
    await page.getByRole("button", { name: "more" }).click();
    await page.waitForTimeout(1500);
    await page.getByRole("textbox", { name: "secret value" }).click();
    await page.getByRole("button", { name: "Insert cross-project reference" }).click();
    await page.getByRole("combobox").click();
    await page.locator("#radix-:r56:").getByRole("option", { name: "shared-infra" }).click();
    await page.getByRole("button", { name: "Insert reference" }).click();
    await page.locator("#radix-:r57:").getByRole("option", { name: "Development" }).click();
    await page.getByRole("textbox", { name: "CERTIFICATE" }).fill("TLS_CERT");
    await expect(page.getByRole("textbox")).toHaveValue("::dev.TLS_CERT}");
    await page.locator("#radix-:r4h:").getByRole("button", { name: "Insert reference" }).click();
    await expect(page.getByRole("textbox", { name: "secret value" })).toHaveValue("placeholder${shared-infra-10we::dev.TLS_CERT}");
    await page.locator("#radix-:r4k:").getByRole("button", { name: "Close" }).click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/v1/pit/batch/commit**");
    await page.locator("#dashboard").getByRole("button", { name: "Save Changes" }).click();
    const response1 = await responsePromise1;
    expect(response1.status()).toBe(200);
    await expect(page.getByText("Changes saved successfully")).toBeVisible();

    expect(pageErrors).toHaveLength(0);
});
