// Generated by Skyramp v1.3.30 on 2026-07-05 04:09:43.537393862 +0000 UTC m=+1786.316778527
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output cross_project_reference_tree_display.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/.skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/cross_project_reference_tree_display_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(188000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:8080/organizations/db7e0e08-bd1a-4085-9809-b468efb192e5/projects/secret-management/4954eb93-9c6f-4e14-8884-f7380a77ccf3/secrets/dev");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "more" }).click();
    await page.getByRole("button", { name: "Secret References" }).click();
    await expect(page.getByRole("button", { name: "dev.TLS_CERT" }).first()).toHaveText("shared-infra-10we::dev.TLS_CERT");
    await page.getByRole("button", { name: "Close" }).click();

    expect(pageErrors).toHaveLength(0);
});
