// Generated by Skyramp v1.3.40 on 2026-08-26 19:21:18.114660357 +0000 UTC m=+1100.159011480
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output webhooks_tab_delivery_history_ui.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/.skyramp/ \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/webhooks_tab_delivery_history_ui_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(895000);
    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/login`);
    // Wait for network activities to finish
    await page.waitForTimeout(9000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "All Projects" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    const existingProject = page.getByRole('link', { name: 'TestWebhookProject' });
    if (await existingProject.isVisible().catch(() => false)) {
        await existingProject.click();
    } else {
        await page.getByRole("button", { name: "Add New Project" }).click();
        await page.getByRole("textbox", { name: "Type your project name" }).fill("TestWebhookProject");
        await page.getByRole("button", { name: "Create Project" }).click();
        // Wait for network activities to finish
        await page.waitForTimeout(3000);
    }

    await page.getByRole("button", { name: "Settings" }).click();
    await page.getByRole("link", { name: "Webhooks" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(67689);

    const existingWebhook = page.getByText("https://example.com/webhook-test");
    if (!await existingWebhook.isVisible().catch(() => false)) {
        await page.getByRole("button", { name: "Create" }).click();
        await page.getByRole("textbox", { name: "/" }).fill("/");
        await page.locator("input[name=\"webhookUrl\"]").fill("https://example.com/webhook-test");
        await page.getByRole("button", { name: "Create webhook" }).click();
        // Wait for network activities to finish
        await page.waitForTimeout(3000);
    }

    await expect(page.getByText("https://example.com/webhook-")).toContainText("https://example.com/webhook-test");
    await expect(page.getByRole("row")).toHaveCount(2);
    await page.getByRole("button", { name: "Options" }).click();
    await page.getByRole("menuitem", { name: "Delivery history" }).first().click();
    await expect(page.getByRole("heading", { name: /Delivery history/ })).toBeVisible();
    await expect(page.getByText("No deliveries yet")).toBeVisible();
    expect(errors).toHaveLength(0);
});
