// Generated by Skyramp v1.3.40 on 2026-08-27 14:24:36.168522737 +0000 UTC m=+997.227656913
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output share_secret_edit_modal_ui_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/frontend/skyramp-tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/share_secret_edit_modal_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(337000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/login`);
    // Wait for network activities to finish
    await page.waitForTimeout(8250);

    await page.waitForTimeout(3000);

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Secret Sharing" }).click();
    await page.getByRole("button", { name: "Share Secret" }).click();
    await page.getByRole("textbox", { name: "API Key" }).fill("UI Seed Secret");
    await page.getByRole("textbox", { name: "Enter sensitive data to share" }).fill("seed-value-123");
    await page.getByRole("button", { name: "Create Secret Link" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Close" }).click();
    await page.getByRole("button", { name: "actions" }).click();
    await page.getByRole("menuitem", { name: "Edit" }).click();
    await page.getByRole("textbox", { name: "API Key for John" }).fill("Edited via UI");
    await page.getByRole("button", { name: "Save" }).click();
    // Wait for the update request to settle
    await page.waitForTimeout(3000);

    // Post-edit state: the shared secret row reflects the updated name persisted by PATCH /api/v1/shared-secrets/:id
    await expect(page.getByRole("cell", { name: "Edited via UI" }).first()).toHaveText("Edited via UI");
});
