// Generated by Skyramp v1.3.40 on 2026-08-27 15:24:00.49370669 +0000 UTC m=+1766.923027474
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output cross_project_reference_modal_ui_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/ui_cross_project_reference_modal_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(2358000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/`);
    // Wait for network activities to finish
    await page.waitForTimeout(11250);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "All Projects" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(20000);

    await page.getByRole("button", { name: "Add New Project" }).click();
    await page.getByRole("textbox", { name: "Type your project name" }).fill("shared");
    await page.getByRole("button", { name: "Secrets Management" }).click();
    await page.getByRole("button", { name: "Create Project" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(20000);

    await page.getByRole("button", { exact: true, name: "Organization" }).click();
    await page.getByRole("button", { name: "Add New Project" }).click();
    await page.getByRole("textbox", { name: "Type your project name" }).fill("consumer");
    await page.getByRole("button", { name: "Secrets Management" }).click();
    await page.getByRole("button", { name: "Create Project" }).click();
    await page.getByText("Add a New Secret").click();
    await page.getByRole("textbox", { name: "Type your secret name" }).fill("DATABASE_URL");
    await page.getByRole("textbox", { name: "secret value" }).fill("postgres://localhost:5432/app");
    await page.getByRole("button", { name: "Create Secret" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(20000);

    await page.getByRole("button", { name: "Reveal Values" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(65537);

    await page.getByRole("cell", { name: "postgres://localhost:5432/app" }).hover();
    // Wait for network activities to finish
    await page.waitForTimeout(120000);

    await page.getByRole("cell", { name: "postgres://localhost:5432/app" }).hover();
    // Wait for network activities to finish
    await page.waitForTimeout(120000);

    await page.getByRole("button", { name: "more" }).click();
    await page.getByRole("button", { name: "Close" }).click();
    await page.getByRole("button", { name: "Reveal" }).click();
    await page.getByRole("button", { name: "more" }).click();
    await page.getByRole("button", { name: "Insert cross-project reference" }).click();
    await page.getByRole("combobox").click();
    await page.getByRole("option", { name: "shared" }).click();
    await page.getByRole("button", { name: "Insert reference" }).click();
    await page.getByRole("option", { name: "Development" }).click();
    await page.getByRole("textbox", { name: "CERTIFICATE" }).fill("API_KEY");
    await expect(page.getByRole("textbox")).toHaveValue("::dev.API_KEY}");
    await page.getByRole("button", { name: "Insert reference" }).click();
    await expect(page.getByRole("textbox", { name: "secret value" })).toHaveValue("app${shared");
});
