// Generated by Skyramp v1.3.40 on 2026-08-27 15:10:31.799167545 +0000 UTC m=+1453.112080422
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output cross_project_reference_builder_insert_flow.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/cross_project_reference_builder_insert_flow_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

// Fixtures this flow reads. The consumer project must contain SECRET_NAME at dev:/, and a second
// Secret Manager project (SOURCE_PROJECT_NAME, slug SOURCE_PROJECT_SLUG) must exist in the same
// org so it is offered as a reference target.
const CONSUMER_PROJECT_NAME = process.env.SKYRAMP_CONSUMER_PROJECT ?? "consproj23086";
const SOURCE_PROJECT_NAME = process.env.SKYRAMP_SOURCE_PROJECT ?? "srcproj27024";
const SOURCE_PROJECT_SLUG = process.env.SKYRAMP_SOURCE_PROJECT_SLUG ?? "srcproj27024-shared";
const SECRET_NAME = process.env.SKYRAMP_SECRET_NAME ?? "LOCAL_TARGET";
const SECRET_VALUE = process.env.SKYRAMP_SECRET_VALUE ?? "b-local-value";
const SOURCE_SECRET_KEY = "SHARED_KEY";
const EXPECTED_REFERENCE = `\${${SOURCE_PROJECT_SLUG}::dev.${SOURCE_SECRET_KEY}}`;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(674000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/login`);
    await page.waitForLoadState('networkidle');

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status(), 'login status code').toBe(200);

    // Open the consumer project, then its Development secrets dashboard. The dashboard URL is
    // derived from the project's own overview URL so no project id is hardcoded.
    await page.getByText(CONSUMER_PROJECT_NAME).first().click();
    await page.waitForURL(/\/overview$/);
    await page.goto(page.url().replace(/\/overview$/, '/secrets/dev'));
    await page.waitForLoadState('networkidle');

    const revealButton = page.locator("main").getByRole("button", { name: "Reveal" });
    await revealButton.waitFor({ state: 'visible', timeout: 10000 });
    await revealButton.click();

    // Open the secret's detail sidebar and launch the cross-project reference builder.
    await page.locator("form").filter({ hasText: SECRET_VALUE }).getByLabel("more").click();
    await page.getByRole("button", { name: "Insert cross-project reference" }).click();

    // Source project and Environment are custom (Radix) selects: click the trigger, then the option.
    await page.getByRole("combobox").filter({ hasText: "Select a project" }).click();
    await page.getByRole("option", { name: SOURCE_PROJECT_NAME }).click();
    await page.getByRole("combobox").filter({ hasText: "Select an environment" }).click();
    await page.getByRole("option", { name: "Development" }).click();
    await page.getByRole("textbox", { name: "CERTIFICATE" }).fill(SOURCE_SECRET_KEY);

    // The builder composes the reference from the project and environment SLUGS (not display
    // names), and collapses the root secret path.
    const referencePreview = page.locator('[role="dialog"] input[readonly]');
    await expect(referencePreview).toHaveValue(EXPECTED_REFERENCE);

    // Insert reference is gated until project, environment and key are all supplied.
    const insertReference = page.getByRole("button", { name: "Insert reference" });
    await expect(insertReference).toBeEnabled();
    await insertReference.click();

    // The builder closes and appends the composed reference to the secret's value field.
    await expect(page.getByRole("button", { name: "Insert reference" })).toHaveCount(0);
    await expect(page.getByRole("textbox", { name: "secret value" })).toHaveValue(
        `${SECRET_VALUE}${EXPECTED_REFERENCE}`
    );
});
