// Generated by Skyramp v1.3.38 on 2026-08-19 18:00:00.481783664 +0000 UTC m=+1364.184711154
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output folder_rename_toast_reports_cascade.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/folder_rename_toast_reports_cascade_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

// Secret-manager project the rename is exercised in. Overridable so the spec is not pinned to one instance.
const projectId = process.env.SKYRAMP_TEST_PROJECT_ID ?? "57da3322-94bb-4613-b3b2-8442a82963fe";

// Folder names carry a run-unique suffix: folder names are unique per parent, so a fixed
// name would make the second run fail with a duplicate-name error instead of testing the rename.
const runSuffix = `${Date.now()}`.slice(-8);
const originalFolderName = `cascadesrc${runSuffix}`;
const renamedFolderName = `cascadedst${runSuffix}`;

// The folder list has no data-testid, so row controls are reached from the row's name button.
const folderRowControl = (page: any, folderName: string, control: string) =>
    page.getByRole("button", { name: folderName, exact: true })
        .locator(`xpath=following-sibling::*//button[@aria-label="${control}"]`);

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1086000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/login`);
    // Wait for network activities to finish
    await page.waitForTimeout(7500);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;

    expect(response0.status()).toBe(200);
    // Login must land on the org overview, which is where the orgId in the dashboard URL comes from.
    await page.waitForURL(/\/organizations\/[0-9a-f-]{36}\/projects/);
    const orgId = page.url().match(/\/organizations\/([0-9a-f-]{36})\//)![1];
    expect(orgId).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    const dashboardUrl = `${baseUrl}/organizations/${orgId}/projects/secret-management/${projectId}/secrets/dev`;
    await page.goto(dashboardUrl);
    await page.waitForLoadState('networkidle');
    await page.waitForSelector("text=Add Secret");

    await page.locator("main").getByRole("button", { name: "add-folder-or-import" }).click();
    await page.getByRole("button", { name: "Add Folder" }).click();
    await page.getByRole("textbox", { name: "Type your folder name" }).fill(originalFolderName);
    await page.getByRole("button", { name: "Add Folder" }).click();

    // The new folder row is the observable outcome of the create.
    await expect(page.getByRole("button", { name: originalFolderName, exact: true })).toBeVisible();

    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise4 = page.waitForResponse("**/api/v1/pit/batch/commit**");
    await page.getByRole("button", { name: "Save Changes" }).click();
    const response4 = await responsePromise4;

    expect(response4.status()).toBe(200);
    // Once committed, the pending bar is gone and the row becomes editable.
    await expect(page.getByRole("button", { name: "Save Changes" })).toHaveCount(0);
    await expect(folderRowControl(page, originalFolderName, "edit-folder")).toBeEnabled();

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await folderRowControl(page, originalFolderName, "edit-folder").click();
    // The Edit Folder dialog pre-fills the current name.
    await expect(page.getByRole("textbox", { name: "Type your folder name" })).toHaveValue(originalFolderName);
    await page.getByRole("textbox", { name: "Type your folder name" }).fill(renamedFolderName);
    await page.getByRole("button", { name: "Update Folder" }).click();

    // Saving the rename must reach updateFolder and surface its success toast, which this PR
    // extended to report the cascaded imports/references. FolderListView returns early into
    // addPendingChange whenever isBatchMode is set, and isBatchMode is hardcoded true with no
    // setter, so no toast is raised at all and the new copy is unreachable.
    await expect(page.getByText("Successfully saved folder")).toBeVisible();

    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise5 = page.waitForResponse("**/api/v1/pit/batch/commit**");
    await page.getByRole("button", { name: "Save Changes" }).click();
    const response5 = await responsePromise5;

    expect(response5.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    // The rename is persisted: the new name is listed and the old one no longer is.
    await expect(page.getByRole("button", { name: renamedFolderName, exact: true })).toBeVisible();
    await expect(page.getByRole("button", { name: originalFolderName, exact: true })).toHaveCount(0);
});
