// Generated by Skyramp v1.3.40 on 2026-08-27 14:44:48.801494436 +0000 UTC m=+1225.171555572
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output move_secrets_personal_overrides.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/move_secrets_personal_override_count_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(735000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);

    // Issue provisioning calls from inside the browser (via fetch) rather than Node's own
    // request context, since the test runner's network namespace cannot reach the app directly.
    const apiFetch = (path: string, options: { method?: string; token?: string; body?: unknown } = {}) =>
        page.evaluate(async ({ path, options }) => {
            const res = await fetch(path, {
                method: options.method || "GET",
                headers: {
                    "Content-Type": "application/json",
                    ...(options.token ? { Authorization: `Bearer ${options.token}` } : {})
                },
                body: options.body ? JSON.stringify(options.body) : undefined
            });
            return { status: res.status, json: await res.json().catch(() => ({})) };
        }, { path, options });

    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    await page.goto(`${baseUrl}/login`);
    // Wait for network activities to finish
    await page.waitForTimeout(10500);

    // page.goto resolves "localhost" to whatever host the browser can actually reach
    // (e.g. host.docker.internal inside a container) - reuse that resolved origin for
    // the fetch-based provisioning calls below instead of the raw baseUrl string.
    const apiOrigin: string = await page.evaluate(() => window.location.origin);

    // Provision an isolated project + shared secret + personal override via the API so this
    // UI flow does not depend on data left behind by a previous run of this test.
    const { json: loginJson } = await apiFetch(`${apiOrigin}/api/v3/auth/login`, {
        method: "POST",
        body: { email: "admin@test.com", password: "Password123!" }
    });
    const accessToken = loginJson.accessToken;

    const { json: orgsJson } = await apiFetch(`${apiOrigin}/api/v1/organization`, { token: accessToken });
    const orgId = orgsJson.organizations[0].id;

    const { json: selectOrgJson } = await apiFetch(`${apiOrigin}/api/v3/auth/select-organization`, {
        method: "POST",
        token: accessToken,
        body: { organizationId: orgId }
    });
    const orgToken = selectOrgJson.token;

    const projectName = `move-override-ui-${Date.now()}`;
    const { json: projectJson } = await apiFetch(`${apiOrigin}/api/v1/projects`, {
        method: "POST",
        token: orgToken,
        body: { projectName }
    });
    const projectId = projectJson.project.id;

    await apiFetch(`${apiOrigin}/api/v4/secrets/UI_MOVE_KEY`, {
        method: "POST",
        token: orgToken,
        body: { projectId, environment: "dev", secretPath: "/", secretValue: "shared-value", type: "shared" }
    });
    await apiFetch(`${apiOrigin}/api/v4/secrets/UI_MOVE_KEY`, {
        method: "POST",
        token: orgToken,
        body: { projectId, environment: "dev", secretPath: "/", secretValue: "personal-value", type: "personal" }
    });


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto(`${baseUrl}/organizations/${orgId}/projects/secret-management/${projectId}/overview`);
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.locator("tr").nth(1).hover();
    await page.locator("tr").nth(1).locator("[role=\"checkbox\"]").click();
    await page.getByText("Move", { exact: true }).click();
    await expect(page.getByText("Secrets with conflicting keys")).toContainText("Secrets with conflicting keys at the destination will not be overwritten");
    await expect(page.getByText("personal overrides will be moved along with the selected secrets")).toHaveText("1 personal overrides will be moved along with the selected secrets");
    await page.getByRole("combobox").filter({ hasText: "Development" }).click();
    await page.getByRole("option", { name: "Staging" }).click();
    const moveResponsePromise = page.waitForResponse("**/api/v4/secrets/move");
    await page.getByRole("button", { name: "Move Secrets" }).click();
    const moveResponse = await moveResponsePromise;
    expect(moveResponse.status()).toBe(200);
    const moveResponseBody = await moveResponse.json();
    expect(moveResponseBody.isSourceUpdated).toBe(true);
    expect(moveResponseBody.isDestinationUpdated).toBe(true);
    expect(moveResponseBody.movedOverridesCount).toBe(1);
    // Wait for network activities to finish
    await page.waitForTimeout(20000);

    await expect(page.getByText("Upload your secrets")).toBeVisible();
    await expect(page.getByRole("button", { name: "Add a New Secret" }).first()).toBeVisible();

    await page.waitForTimeout(2000);
    expect(pageErrors).toHaveLength(0);
});
