// Generated by Skyramp v1.3.40 on 2026-08-27 14:46:21.775155229 +0000 UTC m=+1146.238544676
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output move_secrets_dialog_override_count.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/move_secrets_override_count_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(225000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/`);
    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    await page.getByRole("button", { name: "Add New Project" }).click();
    await page.getByRole("textbox", { name: "Type your project name" }).fill("Override Move Companions");
    await page.getByRole("button", { name: "Create Project" }).click();
    await page.getByText("Add a New Secret").click();
    await page.getByRole("textbox", { name: "Type your secret name" }).fill("DB_PASSWORD");
    await page.getByRole("textbox", { name: "secret value" }).fill("shared-db-password");
    await page.getByRole("button", { name: "Create Secret" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(12369);

    await page.locator("#checkbox-select-all-rows").click();
    await page.getByText("Move", { exact: true }).click();
    await expect(page.getByRole("heading", { name: "Move Secrets" })).toBeVisible();
    await expect(page.getByText("Move the selected secrets to")).toContainText("Move the selected secrets to a new environment and folder location");
    await expect(page.getByText("Secrets with conflicting keys")).toContainText("Secrets with conflicting keys at the destination will not be overwritten");
    await expect(page.getByText(/personal overrides will be moved along with the selected secrets/)).toHaveText("0 personal overrides will be moved along with the selected secrets");
});
