// Generated by Skyramp v1.3.40 on 2026-08-27 15:22:45.933963226 +0000 UTC m=+958.904020311
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output multi_path_download_modal_ui.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/multi_path_download_modal_ui_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(428000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', err => pageErrors.push(err));

    await page.goto(`${baseUrl}/login`);
    // Wait for network activities to finish
    await page.waitForTimeout(7500);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    const existingProject = page.getByRole('link', { name: 'Test Project Secrets Management' });
    if (await existingProject.isVisible().catch(() => false)) {
        await existingProject.click();
    } else {
        await page.getByRole("button", { name: "Add New Project" }).click();
        await page.getByRole("textbox", { name: "Type your project name" }).fill("Test Project");
        await page.getByRole("button", { name: "Create Project" }).click();
        // Wait for network activities to finish
        await page.waitForTimeout(20000);
    }

    await page.getByRole("button").hover();
    await page.locator("button:nth-child(2) > .inline-flex").nth(0).hover();
    await page.locator("button:nth-child(2) > .inline-flex").nth(0).click();
    await expect(page.getByText("Download merged .env from")).toContainText("Download merged .env from multiple paths");
    await page.getByRole("textbox", { name: "/team-a/service" }).fill("/base");
    await page.getByRole("button", { name: "Add path" }).click();
    await expect(page.getByText("/base")).toBeVisible();
    await expect(page.getByText("highest precedence")).toBeVisible();
    await expect(page.getByRole("button", { name: "Download merged .env" })).toBeVisible();

    expect(pageErrors).toHaveLength(0);
});
