// Generated by Skyramp v1.3.30 on 2026-07-06 16:56:35.346819322 +0000 UTC m=+1148.024944186
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output multi_path_download_merge_precedence.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/multi_path_download_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1097000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(6750);

    await page.waitForTimeout(2000);

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    await page.getByRole("button", { name: "Add New Project" }).click();
    await page.getByRole("textbox", { name: "Type your project name" }).fill("multi-path-test-project");
    await page.getByRole("button", { name: "Create Project" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(20000);

    const projectSecretsUrl = page.url().replace(/\/overview$/, "/secrets/dev");

    await page.getByText("Add a New Secret").click();
    await page.getByRole("textbox", { name: "Type your secret name" }).fill("LOG_LEVEL");
    await page.getByRole("textbox", { name: "secret value" }).fill("info");
    await page.getByRole("button", { name: "Create Secret" }).click();
    await page.locator(".inline-flex.items-center.active\\:scale-\\[0\\.99\\].justify-center.border.cursor-pointer.whitespace-nowrap.rounded-md.text-sm.font-medium.transition-all.disabled\\:pointer-events-none.disabled\\:opacity-50.\\[\\&_svg\\]\\:pointer-events-none.shrink-0.\\[\\&\\>svg\\]\\:shrink-0.focus-visible\\:ring-ring.outline-0.focus-visible\\:ring-2.border-project\\/25").click();
    await page.getByRole("menuitem", { name: "Add Folder" }).click();
    await page.getByRole("textbox", { name: "Type your folder name" }).fill("svc");
    await page.getByRole("button", { name: "Add Folder" }).click();
    await page.locator("tr").nth(1).locator("td").nth(1).click();
    await page.waitForLoadState("networkidle");
    await page.getByText("Add a New Secret").waitFor({ state: "visible", timeout: 10000 });
    await page.getByText("Add a New Secret").click();
    await page.getByRole("textbox", { name: "Type your secret name" }).fill("LOG_LEVEL");
    await page.getByRole("textbox", { name: "secret value" }).fill("debug");
    await page.getByRole("button", { name: "Create Secret" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(15000);

    const page1 = await page.context().newPage();
    await page1.goto(projectSecretsUrl);
    await page1.waitForSelector("text=Add Secret");
    await page1.waitForTimeout(2000);
    await page1.locator("main").getByRole("button", { name: "add-folder-or-import" }).click();
    await page1.getByRole("button", { name: "Download Multi-Path (.env)" }).click();
    await page1.getByRole("textbox", { name: "/team-a/service" }).fill("/svc");
    await page1.getByRole("button", { name: "Add path" }).click();

    await expect(page1.getByRole("button", { name: "Remove path" })).toHaveCount(2);
    await expect(page1.getByText("highest precedence")).toBeVisible();

    const mergeResponsePromise = page1.waitForResponse(
        (resp) => resp.url().includes("/api/v4/secrets") && resp.url().includes("secretPaths")
    );
    const downloadPromise = page1.waitForEvent("download");
    await page1.getByRole("button", { name: "Download merged .env" }).click();

    const mergeResponse = await mergeResponsePromise;
    expect(mergeResponse.status()).toBe(200);
    const mergeBody = await mergeResponse.json();
    expect(mergeBody.merge.paths).toEqual(["/", "/svc"]);
    expect(mergeBody.merge.overrides).toEqual([
        {
            secretKey: "LOG_LEVEL",
            type: "shared",
            winningPath: "/svc",
            overriddenPaths: ["/"]
        }
    ]);
    expect(mergeBody.secrets).toHaveLength(1);
    expect(mergeBody.secrets[0].secretKey).toBe("LOG_LEVEL");
    expect(mergeBody.secrets[0].secretValue).toBe("debug");

    const download = await downloadPromise;
    expect(download.suggestedFilename()).toBe("dev-merged.env");
    await expect(
        page1.getByText("Downloaded 1 secrets from 2 paths (1 key overridden by later paths)")
    ).toBeVisible();

    expect(pageErrors).toHaveLength(0);
});
