// Generated by Skyramp v1.3.40 on 2026-08-27 15:22:31.375186833 +0000 UTC m=+1610.501443827
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output multi_path_download_modal_duplicate_path.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/multi_path_download_modal_duplicate_path_trace.zip

// Import of required libraries
import { test, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(2386000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/login`);
    // Wait for network activities to finish
    await page.waitForTimeout(8250);

    await page.waitForTimeout(2000);

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Add New Project" }).click();
    await page.getByRole("textbox", { name: "Type your project name" }).fill("multipath-secrets-test");
    await page.getByRole("button", { name: "Create Project" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(13744);

    await page.locator(".inline-flex.items-center.active\\\\:scale-\\\\[0\\\\.99\\\\].justify-center.border.cursor-pointer.whitespace-nowrap.rounded-md.text-sm.font-medium.transition-all.disabled\\\\:pointer-events-none.disabled\\\\:opacity-50.\\\\[\\\\&_svg\\\\]\\\\:pointer-events-none.shrink-0.\\\\[\\\\&\\\\>svg\\\\]\\\\:shrink-0.focus-visible\\\\:ring-ring.outline-0.focus-visible\\\\:ring-2.text-foreground.hover\\\\:bg-foreground\\\\/10.border-border.hover\\\\:border-foreground\\\\/20.data-\\\\[state\\\\=open\\\\]\\\\:bg-foreground\\\\/10.data-\\\\[state\\\\=open\\\\]\\\\:border-foreground\\\\/20.h-9").nth(0).click();
    await page.locator("button:nth-child(2) > .inline-flex").nth(0).click();
    await page.getByRole("button", { name: "Cancel" }).click();
    await page.locator(".inline-flex.items-center.active\\\\:scale-\\\\[0\\\\.99\\\\].justify-center.border.cursor-pointer.whitespace-nowrap.rounded-md.text-sm.font-medium.transition-all.disabled\\\\:pointer-events-none.disabled\\\\:opacity-50.\\\\[\\\\&_svg\\\\]\\\\:pointer-events-none.shrink-0.\\\\[\\\\&\\\\>svg\\\\]\\\\:shrink-0.focus-visible\\\\:ring-ring.outline-0.focus-visible\\\\:ring-2.text-foreground.hover\\\\:bg-foreground\\\\/10.border-border.hover\\\\:border-foreground\\\\/20.data-\\\\[state\\\\=open\\\\]\\\\:bg-foreground\\\\/10.data-\\\\[state\\\\=open\\\\]\\\\:border-foreground\\\\/20.h-9.w-9.\\\\[\\\\&\\\\>svg\\\\]\\\\:size-4.\\\\[\\\\&\\\\>svg\\\\]\\\\:stroke-\\\\[1\\\\.5\\\\].relative").click();
    await page.keyboard.press("Escape");
    await page.locator(".inline-flex.items-center.active\\\\:scale-\\\\[0\\\\.99\\\\].justify-center.border.cursor-pointer.whitespace-nowrap.rounded-md.text-sm.font-medium.transition-all.disabled\\\\:pointer-events-none.disabled\\\\:opacity-50.\\\\[\\\\&_svg\\\\]\\\\:pointer-events-none.shrink-0.\\\\[\\\\&\\\\>svg\\\\]\\\\:shrink-0.focus-visible\\\\:ring-ring.outline-0.focus-visible\\\\:ring-2.border-project\\\\/25").click();
    await page.getByRole("menuitem", { name: "Add Folder" }).click();
    await page.getByRole("textbox", { name: "Type your folder name" }).fill("team-a");
    await page.getByRole("button", { name: "Add Folder" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByText("Add Secret").click();
    await page.getByRole("textbox", { name: "Type your secret name" }).fill("BASE_URL");
    await page.getByRole("textbox", { name: "secret value" }).fill("https://root.example.com");
    await page.locator("#create-more").click();
    await page.getByRole("button", { name: "Create Secret" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(20000);

    await page.getByRole("textbox", { name: "Type your secret name" }).fill("LOG_LEVEL");
    await page.getByPlaceholder("Enter secret value...").fill("info");
    await page.getByRole("button", { name: "Create Secret" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(20000);

    await page.getByRole("button", { name: "Cancel" }).click();
    await page.locator("tr").nth(1).getByRole("cell", { name: "team-a" }).click();
    await page.getByText("Add Secret").click();
    await page.getByRole("textbox", { name: "Type your secret name" }).fill("LOG_LEVEL");
    await page.getByRole("textbox", { name: "secret value" }).fill("debug");
    await page.locator("#create-more").click();
    await page.getByRole("button", { name: "Create Secret" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(20000);

    await page.getByRole("textbox", { name: "Type your secret name" }).fill("API_KEY");
    await page.getByPlaceholder("Enter secret value...").fill("team-a-secret-value");
    await page.getByRole("button", { name: "Create Secret" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(20000);

    await page.getByRole("button", { name: "Cancel" }).click();
    await page.getByRole("button", { name: "Access Control" }).click();
    await page.getByRole("link", { name: "Machine Identities" }).click();
    await page.getByRole("button", { name: "Add Machine Identity to" }).click();
    await page.getByRole("button", { name: "Assign Existing" }).click();
    await page.locator("#react-select-5-input").click();
    await page.getByRole("option", { name: "Instance Admin Identity" }).click();
    await page.locator("#react-select-6-input").click();
    await page.getByRole("option", { name: "Admin" }).click();
    await page.getByRole("button", { name: "Assign to Project" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(20000);

    await page.waitForSelector("text=Project Overview");
    await page.locator("button:nth-child(2) > .inline-flex").nth(0).click();
    await page.getByRole("textbox", { name: "/team-a/service" }).fill("/team-a");
    await page.getByRole("button", { name: "Add path" }).click();
    await page.getByRole("textbox", { name: "/team-a/service" }).fill("/team-a");
    await page.getByRole("button", { name: "Add path" }).click();
    await page.getByRole("textbox", { name: "/team-a/service" }).fill("/team-a");
    await page.getByRole("button", { name: "Add path" }).click();
    await page.getByRole("button", { name: "Cancel" }).click();
});
