// Generated by Skyramp v1.3.40 on 2026-08-27 15:15:51.657955057 +0000 UTC m=+804.380009095
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output multi_path_download_merged_env.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/multi_path_download_merged_env_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(528000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Track uncaught page errors so the test fails if the page throws
    const pageErrors: string[] = [];
    page.on("pageerror", (err) => pageErrors.push(err.message));
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/login`);
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.waitForTimeout(3000);

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    // Idempotent setup: reuse the project if it already exists, otherwise create it
    const existingProject = page.getByText("Multipath Secrets").first();
    if (await existingProject.isVisible().catch(() => false)) {
        await existingProject.click();
    } else {
        await page.getByRole("button", { name: "Add New Project" }).click();
        await page.getByRole("textbox", { name: "Type your project name" }).fill("Multipath Secrets");
        await page.getByRole("button", { name: "Create Project" }).click();
    }
    // Wait for network activities to finish
    await page.waitForTimeout(20000);

    // The project id is dynamic; derive the Development secret dashboard URL from the current project URL
    const projectUrl = page.url();
    const dashboardUrl = projectUrl.includes("/overview")
        ? projectUrl.replace(/\/overview.*$/, "/secrets/dev")
        : projectUrl;
    await page.goto(dashboardUrl);

    await page.waitForTimeout(3000);
    await page.getByRole("button", { name: "Download" }).click();
    await page.locator("main").getByRole("button", { name: "add-folder-or-import" }).click();
    await page.getByRole("button", { name: "Download Multi-Path (.env)" }).click();
    await page.getByRole("textbox", { name: "/team-a/service" }).fill("/base");
    await page.getByRole("button", { name: "Add path" }).click();

    // After adding a second path, the modal shows two ordered paths and marks the last as highest precedence
    await expect(page.getByRole("button", { name: "Remove path" })).toHaveCount(2);
    await expect(page.getByText("/base")).toBeVisible();
    await expect(page.getByText("highest precedence")).toBeVisible();

    // Reorder: move /base to the top so the other path becomes the last (highest-precedence) entry
    await page.getByRole("button", { name: "Move path up" }).nth(1).click();

    // The list survives the reorder: still exactly two paths and exactly one highest-precedence marker
    await expect(page.getByRole("button", { name: "Remove path" })).toHaveCount(2);
    await expect(page.getByText("highest precedence")).toBeVisible();

    // No uncaught page errors occurred during the flow
    expect(pageErrors).toHaveLength(0);
});
