// Generated by Skyramp v1.3.40 on 2026-08-27 14:33:56.996203251 +0000 UTC m=+992.708477679
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_sharing_access_history_drawer.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_sharing_access_history_drawer_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(458000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/`);
    // Wait for network activities to finish
    await page.waitForTimeout(6000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Secret Sharing" }).click();
    await page.getByRole("button", { name: "Share Secret" }).click();
    await page.getByRole("textbox", { name: "API Key" }).fill("skyramp-access-history");
    await page.getByRole("textbox", { name: "Enter sensitive data to share" }).fill("skyramp-secret-payload");
    await page.getByRole("button", { name: "Advanced Settings" }).click();
    await page.locator("#notify-on-access").click();
    await page.getByRole("button", { name: "Create Secret Link" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Close" }).click();
    await expect(page.getByRole("cell", { name: "skyramp-access-history" }).first()).toBeVisible();
    await page.getByRole("button", { name: "actions" }).first().click();
    await page.getByRole("menuitem", { name: "Access history" }).click();
    await expect(page.getByRole("heading", { name: "Access History" })).toBeVisible();
    await expect(page.getByText("Not opened yet")).toBeVisible();
    await expect(page.getByText("Every attempt to open this")).toContainText("0 total");
});
