// Generated by Skyramp v1.3.40 on 2026-08-26 19:23:47.006542022 +0000 UTC m=+949.782159541
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output webhook_delivery_history_records_test_delivery.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/webhook_delivery_history_records_test_delivery_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1611000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/login`);
    await page.waitForLoadState('networkidle');
    // Wait for network activities to finish
    await page.waitForTimeout(8250);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Add New Project" }).click();
    await page.getByRole("textbox", { name: "Type your project name" }).fill("Webhook Delivery QA");
    await page.getByRole("button", { name: "Secrets Management" }).click();
    await page.getByRole("button", { name: "Create Project" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    // The project id is minted at run time, so derive the settings URL from the page we
    // landed on rather than replaying the recorded (now stale) absolute URL.
    await page.waitForURL(/\/projects\/secret-management\/[0-9a-f-]+\/overview/, { timeout: 30000 });
    const projectBaseUrl = page.url().replace(/\/overview.*$/, "");
    await page.goto(`${projectBaseUrl}/settings?selectedTab=tab-project-webhooks`);
    await page.waitForLoadState('networkidle');
    await page.getByRole("button", { name: "Create" }).waitFor({ state: 'visible', timeout: 10000 });
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Create" }).click();
    await page.getByRole("textbox", { name: "/" }).fill("/");
    await page.locator("input[name=\"webhookUrl\"]").fill("http://127.0.0.1:9/dead-hook");
    await page.getByRole("button", { name: "Create webhook" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    const webhookRow = page.getByRole("row").filter({ hasText: "http://127.0.0.1:9/dead-hook" });
    await expect(webhookRow).toHaveCount(1);
    await expect(webhookRow).toContainText("dev");

    const responsePromise1 = page.waitForResponse("**/api/v1/webhooks/**/test**");
    await webhookRow.getByRole("button", { exact: true, name: "Test" }).click();
    const response1 = await responsePromise1;

    expect(response1.status()).toBe(200);
    const testWebhookBody = await response1.json();
    expect(getValue(testWebhookBody, "message")).toBe("Successfully tested webhook");
    expect(getValue(testWebhookBody, "webhook.lastStatus")).toBe("failed");
    expect(getValue(testWebhookBody, "webhook.lastRunErrorMessage")).toBe("connect ECONNREFUSED 127.0.0.1:9");
    expect(getValue(testWebhookBody, "webhook.environment.slug")).toBe("dev");
    expect(getValue(testWebhookBody, "webhook.isDisabled")).toBe(false);
    const testedWebhookId = getValue(testWebhookBody, "webhook.id");
    expect(testedWebhookId).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(webhookRow).toContainText("failed");

    const deliveriesResponsePromise = page.waitForResponse("**/api/v1/webhooks/**/deliveries**");
    await webhookRow.getByRole("button", { name: "Options" }).click();
    await page.getByRole("menuitem", { name: "Delivery history" }).first().click();
    const deliveriesResponse = await deliveriesResponsePromise;

    expect(deliveriesResponse.status()).toBe(200);
    const deliveriesBody = await deliveriesResponse.json();
    expect(getValue(deliveriesBody, "message")).toBe("Successfully fetched webhook deliveries");
    expect(getValue(deliveriesBody, "totalCount")).toBe(1);
    expect(getValue(deliveriesBody, "deliveries").length).toBe(1);
    expect(getValue(deliveriesBody, "deliveries.0.webhookId")).toBe(testedWebhookId);
    expect(getValue(deliveriesBody, "deliveries.0.status")).toBe("failed");
    expect(getValue(deliveriesBody, "deliveries.0.eventType")).toBe("test");
    expect(getValue(deliveriesBody, "deliveries.0.errorMessage")).toBe("connect ECONNREFUSED 127.0.0.1:9");
    expect(getValue(deliveriesBody, "deliveries.1")).toBeUndefined();

    await expect(page.getByText("Every request sent to this")).toContainText("1 total.");
    const deliveryRow = page.getByRole("row").filter({ hasText: "connect ECONNREFUSED 127.0.0.1:9" });
    await expect(deliveryRow).toHaveCount(1);
    await expect(deliveryRow).toContainText("test");
    await expect(deliveryRow).toContainText("failed");
});
