// Generated by Skyramp v1.3.40 on 2026-08-27 15:02:09.298444627 +0000 UTC m=+455.727765411
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output cross_project_reference_resolution_permission_boundary_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/backend/e2e-test/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/backend/e2e-test/skyramp/scenario_cross-project-reference-resolution-permission-boundary.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const raw = "CONSUMER";

    // Request Body
    const apiKeyPostRequestBody: string = `{
        "environment": "dev",
        "secretPath": "/",
        "secretValue": "source-secret-value",
        "type": "shared",
        "workspaceId": "REPLACE_WITH_SOURCE_PROJECT_ID"
    }`;

    // Execute Request
    const apiKeyPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v3/secrets/raw/API_KEY",
        method: "POST",
        body: apiKeyPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(apiKeyPostResponse.statusCode, 'status code').toBe(200);
    // Echo-back: the source secret is keyed by the URL path segment and stores the literal value
    expect(getValue(apiKeyPostResponse, "secret.secretKey"), 'secretKey').toBe("API_KEY");
    expect(getValue(apiKeyPostResponse, "secret.secretValue"), 'secretValue').toBe("source-secret-value");

    // Request Body
    const rawPostRequestBody: string = `{
        "environment": "dev",
        "secretPath": "/",
        "secretValue": "${source::dev./.API_KEY}",
        "type": "shared",
        "workspaceId": "REPLACE_WITH_CONSUMER_PROJECT_ID"
    }`;

    // Execute Request
    const rawPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v3/secrets/raw/{raw}",
        method: "POST",
        body: rawPostRequestBody,
        headers: headers,
        pathParams: {"raw": raw}
    });

    // Generated Assertions
    expect(rawPostResponse.statusCode, 'status code').toBe(200);
    // Echo-back: the consumer secret is keyed by the chained path param and stores the cross-project reference literal (create does not expand)
    expect(getValue(rawPostResponse, "secret.secretKey"), 'secretKey').toBe(raw);
    expect(getValue(rawPostResponse, "secret.secretValue"), 'secretValue').toBe("${source::dev./.API_KEY}");

    // Execute Request
    const rawGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v3/secrets/raw/{raw}",
        method: "GET",
        headers: headers,
        pathParams: {"raw": raw},
        queryParams: {
            "environment": ["dev"],
            "expandSecretReferences": ["true"],
            "secretPath": ["/"],
            "workspaceId": ["REPLACE_WITH_CONSUMER_PROJECT_ID"]
        }
    });

    // Generated Assertions
    expect(rawGetResponse.statusCode, 'status code').toBe(200);
    // Core cross-project assertion: reading the consumer secret with expandSecretReferences=true resolves ${source::dev./.API_KEY}
    // to the source project's value, and the response echoes the consumer key (chained from the POST path param).
    expect(getValue(rawGetResponse, "secret.secretKey"), 'secretKey').toBe(raw);
    expect(getValue(rawGetResponse, "secret.secretValue"), 'secretValue').toBe("source-secret-value");
});
