// Generated by Skyramp v1.3.40 on 2026-08-27 15:02:06.38034652 +0000 UTC m=+452.809667295
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output cross_project_reference_missing_project_forbidden_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/backend/e2e-test/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/backend/e2e-test/skyramp/scenario_cross-project-reference-missing-project-forbidden.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const badRefPostRequestBody: string = `{
        "environment": "dev",
        "secretPath": "/",
        "secretValue": "${does-not-exist::dev./.API_KEY}",
        "type": "shared",
        "workspaceId": "REPLACE_WITH_PROJECT_ID"
    }`;

    // Execute Request
    const badRefPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v3/secrets/raw/BAD_REF",
        method: "POST",
        body: badRefPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(badRefPostResponse.statusCode, 'status code').toBe(200);
    // Echo-back: the created secret is keyed by the URL path segment and stores the reference literal verbatim (create does not expand references)
    expect(getValue(badRefPostResponse, "secret.secretKey"), 'secretKey').toBe("BAD_REF");
    expect(getValue(badRefPostResponse, "secret.secretValue"), 'secretValue').toBe("${does-not-exist::dev./.API_KEY}");

    // Execute Request
    const badRefGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v3/secrets/raw/BAD_REF",
        method: "GET",
        headers: headers,
        queryParams: {
            "environment": ["dev"],
            "expandSecretReferences": ["true"],
            "secretPath": ["/"],
            "workspaceId": ["REPLACE_WITH_PROJECT_ID"]
        }
    });

    // Generated Assertions
    expect(badRefGetResponse.statusCode, 'status code').toBe(403);
    // Error path: the fail-closed cross-project resolver rejects an unresolvable project slug with a ForbiddenRequestError message
    expect(getValue(badRefGetResponse, "message"), 'message').toContain("Cannot resolve cross-project secret reference");
});
