// Generated by Skyramp v1.3.40 on 2026-08-27 15:09:00.041402739 +0000 UTC m=+392.763456777
// Command: skyramp generate contract rest http://localhost:8080/api/v4/secrets \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output get_secrets_multipath_duplicate_path_dedup_contract.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/backend/e2e-test/skyramp \
// 		--overwrite \
// 		--provider \
// 		--query-params environment=dev,projectId=00000000-0000-4000-8000-000000000000,secretPaths=/app%2C/app/,viewSecretValue=true \
// 		--response-status-code 200 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

// contract test for /api/v4/secrets GET
test('testSecretsGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const secretsGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/v4/secrets",
        method: "GET",
        headers: headers,
        queryParams: {
            "environment": "dev",
            "projectId": "e39af8f4-3542-430e-a3f0-bf5ea675b664",
            "secretPaths": "/app,/app/",
            "viewSecretValue": "true"
        }
    });

    // Generated Assertions
    expect(secretsGetResponse.statusCode, 'status code').toBe(200);
    // /app and /app/ normalize to the same path, so the merge must collapse them to one
    expect(getValue(secretsGetResponse, "merge.paths.0"), 'deduped path').toBe("/app");
    expect(getValue(secretsGetResponse, "merge.paths.1"), 'no duplicate normalized path').toBeUndefined();
    // a path cannot override itself — deduped input must yield zero overrides
    expect(getValue(secretsGetResponse, "merge.overrides.0"), 'no spurious self-override').toBeUndefined();
});
