// Generated by Skyramp v1.3.40 on 2026-08-27 15:09:13.317275642 +0000 UTC m=+406.039329680
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output get_secrets_multipath_merge_precedence_integration.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/backend/e2e-test/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/backend/e2e-test/skyramp/scenario_get_secrets_multipath_merge_precedence.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Declaration of variables
    const viewSecretValue = "true";

    // Execute Request
    const secretsGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets",
        method: "GET",
        queryParams: {
            "environment": ["dev"],
            "expandSecretReferences": [viewSecretValue],
            "projectId": ["00000000-0000-4000-8000-000000000000"],
            "secretPaths": ["/base,/app"],
            "viewSecretValue": [viewSecretValue]
        }
    });

    // Generated Assertions
    expect(secretsGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(secretsGetResponse, "merge.paths.0"), 'first path in precedence order').toBe("/base");
    expect(getValue(secretsGetResponse, "merge.paths.1"), 'last path wins on conflicts').toBe("/app");
    expect(getValue(secretsGetResponse, "merge.paths.2"), 'exactly two paths merged').toBeUndefined();
    expect(getValue(secretsGetResponse, "merge.overrides.0.secretKey"), 'overridden key').toBe("SHARED_KEY");
    expect(getValue(secretsGetResponse, "merge.overrides.0.winningPath"), 'later path wins').toBe("/app");
    expect(getValue(secretsGetResponse, "merge.overrides.0.overriddenPaths.0"), 'earlier path shadowed').toBe("/base");
    expect(getValue(secretsGetResponse, "secrets.0.secretPath"), 'winning secret sourced from later path').toBe("/app");
    expect(getValue(secretsGetResponse, "secrets.0.secretValue"), 'winning secret value from later path').toBe("from-app");
});
