# Generated by Skyramp v1.3.38 on 2026-08-19 04:25:50.488178817 +0000 UTC m=+1985.681632255
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output secrets_tagslugs_any_of_filter_integration_test.py \
# 		--output-dir /home/runner/work/infisical/infisical/backend/e2e-test/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/infisical/infisical/backend/e2e-test/skyramp/scenario_secrets_tagslugs_any_of_filter.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    projects = "11111111-1111-1111-1111-111111111111"
    secrets = "TAGSLUGS_FILTER_SECRET"

    # Request Body
    projects_POST_request_body = r'''{
        "projectName": "tagslugs-filter-test"
    }'''

    # Execute Request
    projects_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects",
        method="POST",
        body=projects_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert projects_POST_response.status_code == 200
    assert skyramp.get_response_value(projects_POST_response, "project.name") == "tagslugs-filter-test"
    import re
    assert re.match(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", skyramp.get_response_value(projects_POST_response, "project.id"), re.IGNORECASE)

    # Request Body
    tags_POST_request_body = r'''{
        "color": "#0000FF",
        "slug": "alpha"
    }'''

    # Execute Request
    tags_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects/{projects}/tags",
        method="POST",
        body=tags_POST_request_body,
        headers=headers,
        path_params={"projects": skyramp.get_response_value(projects_POST_response, "project.id")}
    )

    # Generated Assertions
    assert tags_POST_response.status_code == 200
    assert skyramp.get_response_value(tags_POST_response, "tag.slug") == "alpha"
    assert skyramp.get_response_value(tags_POST_response, "tag.color") == "#0000FF"

    # Request Body
    tags_POST_1_request_body = r'''{
        "color": "#FF0000",
        "slug": "beta"
    }'''

    # Execute Request
    tags_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects/{projects}/tags",
        method="POST",
        body=tags_POST_1_request_body,
        headers=headers,
        path_params={"projects": skyramp.get_response_value(projects_POST_response, "project.id")}
    )

    # Generated Assertions
    assert tags_POST_1_response.status_code == 200
    assert skyramp.get_response_value(tags_POST_1_response, "tag.slug") == "beta"
    assert skyramp.get_response_value(tags_POST_1_response, "tag.color") == "#FF0000"

    # Request Body
    secrets_secrets_POST_request_body = r'''{
        "environment": "dev",
        "projectId": "11111111-1111-1111-1111-111111111111",
        "secretComment": "",
        "secretPath": "/",
        "secretValue": "value1"
    }'''

    # Execute Request
    secrets_secrets_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v4/secrets/{secrets}",
        method="POST",
        body=secrets_secrets_POST_request_body,
        headers=headers,
        path_params={"secrets": secrets},
        data_override={"projectId": skyramp.get_response_value(projects_POST_response, "project.id")}
    )

    # Generated Assertions
    assert secrets_secrets_POST_response.status_code == 200
    assert skyramp.get_response_value(secrets_secrets_POST_response, "secret.secretKey") == "TAGSLUGS_FILTER_SECRET"
    assert skyramp.get_response_value(secrets_secrets_POST_response, "secret.secretValue") == "value1"
    assert skyramp.get_response_value(secrets_secrets_POST_response, "secret.secretComment") == ""
    assert skyramp.get_response_value(secrets_secrets_POST_response, "secret.environment") == "dev"
    assert skyramp.get_response_value(secrets_secrets_POST_response, "secret.version") == 1

    # Request Body
    secrets_tags_POST_request_body = r'''{
        "environment": "dev",
        "projectId": "11111111-1111-1111-1111-111111111111",
        "secretPath": "/",
        "tagSlugs": [
            "alpha"
        ]
    }'''

    # Execute Request
    secrets_tags_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v4/secrets/{secrets}/tags",
        method="POST",
        body=secrets_tags_POST_request_body,
        headers=headers,
        path_params={"secrets": skyramp.get_response_value(secrets_secrets_POST_response, "secret.secretKey")},
        data_override={"projectId": skyramp.get_response_value(projects_POST_response, "project.id")}
    )

    # Generated Assertions
    assert secrets_tags_POST_response.status_code == 200
    assert skyramp.get_response_value(secrets_tags_POST_response, "secretName") == "TAGSLUGS_FILTER_SECRET"
    assert skyramp.get_response_value(secrets_tags_POST_response, "tags.0.slug") == "alpha"
    assert skyramp.get_response_value(secrets_tags_POST_response, "tags.0.id") == skyramp.get_response_value(tags_POST_response, "tag.id")
    assert skyramp.get_response_value(secrets_tags_POST_response, "tags.1") is None

    # Execute Request
    secrets_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v4/secrets",
        method="GET",
        headers=headers,
        query_params={
            "environment": ["dev"],
            "projectId": [skyramp.get_response_value(projects_POST_response, "project.id")],
            "secretPath": ["/"],
            "tagSlugs": ["alpha,beta"]
        }
    )

    # Generated Assertions
    assert secrets_GET_response.status_code == 200
    # Any-of semantics: the secret carries only "alpha" of the two requested slugs
    # (alpha, beta) and must still be returned by the filter.
    assert skyramp.get_response_value(secrets_GET_response, "secrets.0.secretKey") == "TAGSLUGS_FILTER_SECRET"
    assert skyramp.get_response_value(secrets_GET_response, "secrets.1") is None


if __name__ == "__main__":
    test_integration()
