# Generated by Skyramp v1.3.38 on 2026-08-19 04:22:44.157931095 +0000 UTC m=+1799.351384513
# Command: skyramp generate contract rest http://localhost:4000/api/v4/secrets/skyramp-tags-contract-secret/tags \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/infisical/infisical/backend/e2e-test/skyramp \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 422 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4000")

# contract test for /api/v4/secrets/skyramp-tags-contract-secret/tags GET
def test_tags_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    tags_GET_response = client.send_request(
        url=URL,
        path="/api/v4/secrets/skyramp-tags-contract-secret/tags",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert tags_GET_response.status_code == 422
    assert skyramp.get_response_value(tags_GET_response, "error") == "ValidationFailure"
    assert skyramp.get_response_value(tags_GET_response, "message.0.code") == "invalid_type"
    assert skyramp.get_response_value(tags_GET_response, "message.0.path.0") == "projectId"
    assert skyramp.get_response_value(tags_GET_response, "message.0.message") == "Required"
    assert skyramp.get_response_value(tags_GET_response, "message.1.code") == "invalid_type"
    assert skyramp.get_response_value(tags_GET_response, "message.1.path.0") == "environment"
    assert skyramp.get_response_value(tags_GET_response, "message.1.message") == "Required"
    assert skyramp.get_response_value(tags_GET_response, "message.2") is None


if __name__ == "__main__":
    test_tags_get()
