// Generated by Skyramp v1.3.40 on 2026-08-27 14:23:23.602659156 +0000 UTC m=+484.937827269
// Command: skyramp generate contract rest http://localhost:8080/api/v1/pam/resources/ai-insights/models \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output contract_ai_insights_models.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/backend/e2e-test/routes/v1 \
// 		--overwrite \
// 		--provider \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, checkStatusCode, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

// contract test for /api/v1/pam/resources/ai-insights/models GET
test('testModelsGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const modelsGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/v1/pam/resources/ai-insights/models",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(modelsGetResponse.statusCode, 'status code').toBe(200);
});
