// Generated by Skyramp v1.3.38 on 2026-08-19 05:49:56.778565456 +0000 UTC m=+654.315548022
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output identity_token_revoke_scope_bug_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/backend/e2e-test/routes/v1 \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/backend/e2e-test/routes/v1/scenario_identity-token-revoke-scope-bug.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue, uniqueSuffix } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const v1IdentitiesPostRequestBody: string = `{
        "name": "test-identity",
        "organizationId": "cebf9392-0e34-4aea-8363-62b37a9c8d5d",
        "role": "member"
    }`;

    // Execute Request
    const v1IdentitiesPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/identities",
        method: "POST",
        body: v1IdentitiesPostRequestBody,
        headers: headers,
        dataOverride: {"name": uniqueSuffix("test-identity")}
    });

    // Generated Assertions
    expect(v1IdentitiesPostResponse.statusCode, 'status code').toBe(200);

    // Request Body
    const identitiesPostRequestBody: string = `{
        "accessTokenMaxTTL": 7200,
        "accessTokenNumUsesLimit": 10,
        "accessTokenTTL": 3600,
        "accessTokenTrustedIps": [
            {
                "ipAddress": "0.0.0.0",
                "type": "ipv4"
            }
        ]
    }`;

    // Execute Request
    const identitiesPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/auth/token-auth/identities/{identities}",
        method: "POST",
        body: identitiesPostRequestBody,
        headers: headers,
        pathParams: {"identities": getResponseValue(v1IdentitiesPostResponse, "identity.id")}
    });

    // Generated Assertions
    expect(identitiesPostResponse.statusCode, 'status code').toBe(200);

    // Request Body
    const tokensPostRequestBody: string = `{
        "name": "token-a"
    }`;

    // Execute Request
    const tokensPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/auth/token-auth/identities/{identities}/tokens",
        method: "POST",
        body: tokensPostRequestBody,
        headers: headers,
        pathParams: {"identities": getResponseValue(v1IdentitiesPostResponse, "identity.id")}
    });

    // Generated Assertions
    expect(tokensPostResponse.statusCode, 'status code').toBe(201);

    // Request Body
    const tokensPost1RequestBody: string = `{
        "name": "token-b"
    }`;

    // Execute Request
    const tokensPost1Response = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/auth/token-auth/identities/{identities}/tokens",
        method: "POST",
        body: tokensPost1RequestBody,
        headers: headers,
        pathParams: {"identities": getResponseValue(v1IdentitiesPostResponse, "identity.id")}
    });

    // Generated Assertions
    expect(tokensPost1Response.statusCode, 'status code').toBe(201);

    // Execute Request
    const tokensGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/auth/token-auth/identities/{identities}/tokens",
        method: "GET",
        headers: headers,
        pathParams: {"identities": getResponseValue(v1IdentitiesPostResponse, "identity.id")}
    });

    // Generated Assertions
    expect(tokensGetResponse.statusCode, 'status code').toBe(200);

    // Request Body
    const revokePostRequestBody: string = `{}`;

    // Execute Request
    const revokePostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/identities/{identities}/access-tokens/{access-tokens}/revoke",
        method: "POST",
        body: revokePostRequestBody,
        headers: headers,
        pathParams: {
            "access-tokens": getResponseValue(tokensGetResponse, "tokens.1.id"),
            "identities": getResponseValue(v1IdentitiesPostResponse, "identity.id")
        }
    });

    // Generated Assertions
    expect(revokePostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(revokePostResponse, "message")).toBe("Successfully revoked access token");
    expect(getValue(revokePostResponse, "tokenId")).toBe(getResponseValue(tokensGetResponse, "tokens.1.id"));

    // Execute Request
    const accessTokensGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/identities/{identities}/access-tokens",
        method: "GET",
        headers: headers,
        pathParams: {"identities": getResponseValue(v1IdentitiesPostResponse, "identity.id")}
    });

    // Generated Assertions
    expect(accessTokensGetResponse.statusCode, 'status code').toBe(200);
    // Bug-catching: tokens sorted by createdAt desc; tokens[0]=token-b (revoked), tokens[1]=token-a (must NOT be revoked)
    // With the bug (update({ identityId }) instead of { id: tokenId, identityId }), BOTH tokens get revoked
    expect(getValue(accessTokensGetResponse, "tokens.0.isAccessTokenRevoked")).toBe(true);
    expect(getValue(accessTokensGetResponse, "tokens.1.isAccessTokenRevoked")).toBe(false);

    // Execute Request
    const identitiesIdentitiesDeleteResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/identities/{identities}",
        method: "DELETE",
        headers: headers,
        pathParams: {"identities": getResponseValue(v1IdentitiesPostResponse, "identity.id")}
    });

    // Generated Assertions
    expect(identitiesIdentitiesDeleteResponse.statusCode, 'status code').toBe(200);
});
