// Generated by Skyramp v1.3.38 on 2026-08-19 05:49:21.261767154 +0000 UTC m=+618.798749714
// Command: skyramp generate contract rest http://localhost:8080/api/v1/identities/00000000-0000-0000-0000-000000000000/access-tokens \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output identity_access_tokens_auth_required.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/backend/e2e-test/routes/v1 \
// 		--overwrite \
// 		--provider \
// 		--response-status-code 401 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

// contract test for /api/v1/identities/00000000-0000-0000-0000-000000000000/access-tokens GET
test('testAccessTokensGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const accessTokensGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/v1/identities/00000000-0000-0000-0000-000000000000/access-tokens",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(accessTokensGetResponse.statusCode, 'status code').toBe(401);
    expect(getValue(accessTokensGetResponse, "error")).toBe("UnauthorizedError");
});
