// Generated by Skyramp v1.3.40 on 2026-08-27 14:24:34.862677917 +0000 UTC m=+556.197846019
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_sharing_access_logs_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/backend/e2e-test/routes/v1 \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/backend/e2e-test/routes/v1/scenario_secret-sharing-access-logs-integration.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const sharedSecretsPostRequestBody: string = `{
        "expiresIn": "1d",
        "notifyOnAccess": false,
        "secretValue": "my-test-secret-value"
    }`;

    // Execute Request
    const sharedSecretsPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/shared-secrets",
        method: "POST",
        body: sharedSecretsPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(sharedSecretsPostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(sharedSecretsPostResponse, "id")).not.toBeNull();
    expect(getResponseValue(sharedSecretsPostResponse, "sharedSecretLink")).toMatch(/^https?:\/\//);
    expect(getResponseValue(sharedSecretsPostResponse, "notifyOnAccess")).toBe(false);

    // Execute Request
    const accessLogsGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/shared-secrets/{shared-secrets}/access-logs",
        method: "GET",
        headers: headers,
        pathParams: {"shared-secrets": getResponseValue(sharedSecretsPostResponse, "id")}
    });

    // Generated Assertions
    expect(accessLogsGetResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(accessLogsGetResponse, "accessLogs").length).toBe(0);
    expect(getResponseValue(accessLogsGetResponse, "accessLogs.0")).toBeUndefined();
    expect(getResponseValue(accessLogsGetResponse, "totalCount")).toBe(0);
    expect(getResponseValue(accessLogsGetResponse, "totalCount")).toBe(getResponseValue(accessLogsGetResponse, "accessLogs").length);
});
