// Generated by Skyramp v1.3.40 on 2026-08-27 15:16:02.758988451 +0000 UTC m=+555.729045526
// Command: skyramp generate contract rest http://localhost:8080/api/v3/secrets/raw/id/{secretId} \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output contract_get_secret_by_id.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/backend/e2e-test/routes/v3 \
// 		--overwrite \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect, SkyrampClient, checkStatusCode, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

// contract test for /api/v3/secrets/raw/id/{secretId} GET
test('testIdSecretIdGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const secretId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890";

    // Execute Request
    const idSecretIdGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/v3/secrets/raw/id/{secretId}",
        method: "GET",
        headers: headers,
        pathParams: {"secretId": secretId}
    });

    // Generated Assertions
    expect(idSecretIdGetResponse.statusCode).toBe(404);
    expect(getValue(idSecretIdGetResponse, "message")).not.toBeNull();
});
