// Generated by Skyramp v1.3.30 on 2026-07-04 16:46:35.996714966 +0000 UTC m=+854.552001573
// Command: skyramp generate contract rest http://localhost:8080/api/v4/secrets/bulk-import \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output secret_bulk_import_auth_boundary_contract_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/backend/e2e-test/routes/v4 \
// 		--overwrite \
// 		--provider \
// 		--request-data {"projectId":"73e99c52-6af4-4614-936d-e5c7ce43f4d4","environment":"dev","secretPath":"/","format":"env","data":"UNAUTHENTICATED_PROBE=value","dryRun":true,"overwriteExisting":false} \
// 		--response-status-code 401 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

// contract test for /api/v4/secrets/bulk-import POST
test('testBulkImportPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Intentionally no Authorization header — this test asserts the endpoint's auth boundary,
    // so the request must never carry a token even when SKYRAMP_TEST_TOKEN is set in the environment.
    const headers: Record<string, string> = {};

    // Request Body
    const bulkImportPostRequestBody: string = `{
        "data": "UNAUTHENTICATED_PROBE=value",
        "dryRun": true,
        "environment": "dev",
        "format": "env",
        "overwriteExisting": false,
        "projectId": "73e99c52-6af4-4614-936d-e5c7ce43f4d4",
        "secretPath": "/"
    }`;

    // Execute Request
    const bulkImportPostResponse = await client.sendRequest({
        url: URL,
        path: "/api/v4/secrets/bulk-import",
        method: "POST",
        body: bulkImportPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(bulkImportPostResponse.statusCode, 'status code').toBe(401);
    expect(getValue(bulkImportPostResponse, "error"), 'error').toBe("UnauthorizedError");
    expect(getValue(bulkImportPostResponse, "message"), 'message').toBe("Token missing");
    expect(getValue(bulkImportPostResponse, "reqId"), 'reqId').not.toBeNull();
});
