// Generated by Skyramp v1.3.40 on 2026-08-27 15:00:03.582214057 +0000 UTC m=+2139.952275194
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_move_carries_personal_override_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/backend/e2e-test/routes/v4 \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/backend/e2e-test/routes/v4/scenario_secret_move_carries_personal_override.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue, uniqueSuffix } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();

    // Personal secret overrides can only be owned by a user actor (see
    // "Must be user to create personal secret" in secret-v2-bridge-service.ts) - a machine
    // identity access token cannot create them, so authenticate as a real user instead.
    const loginResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v3/auth/login",
        method: "POST",
        body: `{"email": "admin@test.com", "password": "Password123!"}`,
        headers: {}
    });
    expect(loginResponse.statusCode, 'status code').toBe(200);
    const accessToken = getResponseValue(loginResponse, "accessToken");

    const orgsResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/organization",
        method: "GET",
        headers: { "Authorization": "Bearer " + accessToken }
    });
    expect(orgsResponse.statusCode, 'status code').toBe(200);
    const organizationId = getResponseValue(orgsResponse, "organizations.0.id");

    const selectOrgResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v3/auth/select-organization",
        method: "POST",
        body: JSON.stringify({ organizationId }),
        headers: { "Authorization": "Bearer " + accessToken }
    });
    expect(selectOrgResponse.statusCode, 'status code').toBe(200);

    // Definition of authentication header
    const headers: Record<string, string> = {
        "Authorization": "Bearer " + getResponseValue(selectOrgResponse, "token")
    };

    // Declaration of variables
    const environment = "dev";
    const secretPath = "/";
    const secrets = "MOVE_KEY";
    const type = "shared";
    const projectName = uniqueSuffix("secret-move-override-project");

    // Request Body
    const projectsPostRequestBody: string = `{
        "projectName": "secret-move-override-project"
    }`;

    // Execute Request
    const projectsPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/projects",
        method: "POST",
        body: projectsPostRequestBody,
        headers: headers,
        dataOverride: {"projectName": projectName}
    });

    // Generated Assertions
    expect(projectsPostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(projectsPostResponse, "project.name"), 'project.name').toBe(projectName);
    expect(getResponseValue(projectsPostResponse, "project.id"), 'project.id').toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);

    const projectId = getResponseValue(projectsPostResponse, "project.id");

    // Request Body
    const secretsPostRequestBody: string = `{
        "environment": "dev",
        "projectId": "11111111-1111-4111-8111-111111111111",
        "secretPath": "/",
        "secretValue": "shared-value-v1",
        "type": "shared"
    }`;

    // Execute Request
    const secretsPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets/{secrets}",
        method: "POST",
        body: secretsPostRequestBody,
        headers: headers,
        pathParams: {"secrets": secrets},
        dataOverride: {
            "projectId": projectId,
            "secretPath": secretPath
        }
    });

    // Generated Assertions
    expect(secretsPostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(secretsPostResponse, "secret.secretKey"), 'secret.secretKey').toBe(secrets);
    expect(getResponseValue(secretsPostResponse, "secret.type"), 'secret.type').toBe("shared");
    expect(getResponseValue(secretsPostResponse, "secret.secretValue"), 'secret.secretValue').toBe("shared-value-v1");
    expect(getResponseValue(secretsPostResponse, "secret.id"), 'secret.id').toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);

    // Request Body
    const secretsPost1RequestBody: string = `{
        "environment": "dev",
        "projectId": "11111111-1111-4111-8111-111111111111",
        "secretPath": "/",
        "secretValue": "personal-value-v1",
        "type": "personal"
    }`;

    // Execute Request
    const secretsPost1Response = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets/{secrets}",
        method: "POST",
        body: secretsPost1RequestBody,
        headers: headers,
        pathParams: {"secrets": getResponseValue(secretsPostResponse, "secret.secretKey")},
        dataOverride: {
            "projectId": projectId,
            "secretPath": secretPath
        }
    });

    // Generated Assertions
    expect(secretsPost1Response.statusCode, 'status code').toBe(200);
    expect(getResponseValue(secretsPost1Response, "secret.secretKey"), 'secret.secretKey').toBe(secrets);
    expect(getResponseValue(secretsPost1Response, "secret.type"), 'secret.type').toBe("personal");
    expect(getResponseValue(secretsPost1Response, "secret.secretValue"), 'secret.secretValue').toBe("personal-value-v1");

    // Request Body
    const movedSecretId = getResponseValue(secretsPostResponse, "secret.id");
    const movePostRequestBody: string = `{
        "destinationEnvironment": "staging",
        "destinationSecretPath": "/",
        "projectId": "${projectId}",
        "secretIds": [
            "${movedSecretId}"
        ],
        "shouldOverwrite": false,
        "sourceEnvironment": "dev",
        "sourceSecretPath": "${secretPath}"
    }`;

    // Execute Request
    const movePostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets/move",
        method: "POST",
        body: movePostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(movePostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(movePostResponse, "isSourceUpdated"), 'isSourceUpdated').toBe(true);
    expect(getResponseValue(movePostResponse, "isDestinationUpdated"), 'isDestinationUpdated').toBe(true);
    expect(getResponseValue(movePostResponse, "movedOverridesCount"), 'movedOverridesCount').toBe(1);

    // Execute Request
    const secretsGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets/{secrets}",
        method: "GET",
        headers: headers,
        pathParams: {"secrets": getResponseValue(secretsPostResponse, "secret.secretKey")},
        queryParams: {
            "environment": ["staging"],
            "projectId": [projectId],
            "secretPath": [secretPath],
            "type": ["personal"]
        }
    });

    // Generated Assertions
    expect(secretsGetResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(secretsGetResponse, "secret.secretKey"), 'secret.secretKey').toBe(secrets);
    expect(getResponseValue(secretsGetResponse, "secret.type"), 'secret.type').toBe("personal");
    expect(getResponseValue(secretsGetResponse, "secret.secretValue"), 'secret.secretValue').toBe("personal-value-v1");
    expect(getResponseValue(secretsGetResponse, "secret.id"), 'secret.id').toBe(getResponseValue(secretsPost1Response, "secret.id"));

    // Execute Request
    const secretsGet1Response = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets/{secrets}",
        method: "GET",
        headers: headers,
        pathParams: {"secrets": getResponseValue(secretsPostResponse, "secret.secretKey")},
        queryParams: {
            "environment": ["dev"],
            "projectId": [projectId],
            "secretPath": [secretPath],
            "type": ["shared"]
        }
    });

    // Generated Assertions
    expect(secretsGet1Response.statusCode, 'status code').toBe(404);
    expect(getResponseValue(secretsGet1Response, "message"), 'message').toBe(`Secret with name '${secrets}' not found`);
    expect(getResponseValue(secretsGet1Response, "error"), 'error').toBe("NotFound");
});
