// Generated by Skyramp v1.3.30 on 2026-07-04 16:46:16.931372758 +0000 UTC m=+835.486659375
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_bulk_import_lifecycle_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/backend/e2e-test/routes/v4 \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/backend/e2e-test/routes/v4/scenario_secret_bulk_import_lifecycle.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Unique per-run secretPath/key so re-running this test never collides with a secret
    // left behind by a previous run (the endpoint is not idempotent: a second run against a
    // fixed path/key would see the secret already existing and report "skip" instead of "create").
    const runId = Date.now();
    const secretPath = `/testbot-lifecycle-${runId}`;
    const secretKey = `LIFECYCLE_SECRET_${runId}`;

    // Request Body
    const bulkImportPostRequestBody: string = `{
        "data": "${secretKey}=v1",
        "dryRun": false,
        "environment": "dev",
        "format": "env",
        "overwriteExisting": false,
        "projectId": "73e99c52-6af4-4614-936d-e5c7ce43f4d4",
        "secretPath": "${secretPath}"
    }`;

    // Request Body
    const bulkImportPost1RequestBody: string = `{
        "data": "${secretKey}=v2",
        "dryRun": true,
        "environment": "dev",
        "format": "env",
        "overwriteExisting": false,
        "projectId": "73e99c52-6af4-4614-936d-e5c7ce43f4d4",
        "secretPath": "${secretPath}"
    }`;

    // Request Body
    const bulkImportPost2RequestBody: string = `{
        "data": "${secretKey}=v2",
        "dryRun": false,
        "environment": "dev",
        "format": "env",
        "overwriteExisting": true,
        "projectId": "73e99c52-6af4-4614-936d-e5c7ce43f4d4",
        "secretPath": "${secretPath}"
    }`;

    // Steps must run sequentially, not in parallel: step 2 depends on step 1 having already
    // created the secret (it asserts a "skip" conflict), and step 3 depends on step 1 as well
    // (it overwrites the secret step 1 created). Running them via Promise.all would race step 1
    // against steps 2/3 and make the classification assertions non-deterministic.
    const bulkImportPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets/bulk-import",
        method: "POST",
        body: bulkImportPostRequestBody,
        headers: headers
    });

    const bulkImportPost1Response = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets/bulk-import",
        method: "POST",
        body: bulkImportPost1RequestBody,
        headers: headers
    });

    const bulkImportPost2Response = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v4/secrets/bulk-import",
        method: "POST",
        body: bulkImportPost2RequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(bulkImportPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(bulkImportPostResponse, "dryRun")).toBe(false);
    expect(getValue(bulkImportPostResponse, "created")).toBe(1);
    expect(getValue(bulkImportPostResponse, "overwritten")).toBe(0);
    expect(getValue(bulkImportPostResponse, "skipped")).toBe(0);
    expect(getValue(bulkImportPostResponse, "imported")).toBe(getValue(bulkImportPostResponse, "created") + getValue(bulkImportPostResponse, "overwritten"));
    expect(getValue(bulkImportPostResponse, "parseErrors.0")).toBeNull();
    expect(getValue(bulkImportPostResponse, "items.0.environment")).toBe("dev");
    expect(getValue(bulkImportPostResponse, "items.0.secretPath")).toBe(secretPath);
    expect(getValue(bulkImportPostResponse, "items.0.secretKey")).toBe(secretKey);
    expect(getValue(bulkImportPostResponse, "items.0.action")).toBe("create");
    expect(getValue(bulkImportPostResponse, "items.1")).toBeNull();

    // Generated Assertions
    expect(bulkImportPost1Response.statusCode, 'status code').toBe(200);
    expect(getValue(bulkImportPost1Response, "dryRun")).toBe(true);
    expect(getValue(bulkImportPost1Response, "secretsToCreate")).toBe(0);
    expect(getValue(bulkImportPost1Response, "secretsToOverwrite")).toBe(0);
    expect(getValue(bulkImportPost1Response, "secretsToSkip")).toBe(1);
    expect(getValue(bulkImportPost1Response, "foldersToCreate.0")).toBeNull();
    expect(getValue(bulkImportPost1Response, "items.0.secretKey")).toBe(getValue(bulkImportPostResponse, "items.0.secretKey"));
    expect(getValue(bulkImportPost1Response, "items.0.secretPath")).toBe(getValue(bulkImportPostResponse, "items.0.secretPath"));
    expect(getValue(bulkImportPost1Response, "items.0.action")).toBe("skip");
    expect(getValue(bulkImportPost1Response, "items.0.reason")).toBe("Secret already exists");
    expect(getValue(bulkImportPost1Response, "items.1")).toBeNull();

    // Generated Assertions
    expect(bulkImportPost2Response.statusCode, 'status code').toBe(200);
    expect(getValue(bulkImportPost2Response, "dryRun")).toBe(false);
    expect(getValue(bulkImportPost2Response, "created")).toBe(0);
    expect(getValue(bulkImportPost2Response, "overwritten")).toBe(1);
    expect(getValue(bulkImportPost2Response, "imported")).toBe(getValue(bulkImportPost2Response, "created") + getValue(bulkImportPost2Response, "overwritten"));
    expect(getValue(bulkImportPost2Response, "parseErrors.0")).toBeNull();
    expect(getValue(bulkImportPost2Response, "items.0.secretKey")).toBe(getValue(bulkImportPostResponse, "items.0.secretKey"));
    expect(getValue(bulkImportPost2Response, "items.0.action")).toBe("overwrite");
    expect(getValue(bulkImportPost2Response, "items.1")).toBeNull();
});
